### ISSUE TITLE
批量下载

### ISSUE THREAD

**Issue by mytk2012** [Johnserf-Seed/TikTokDownload#1]
可以按照搜索关键字批量下载吗，我尝试了，只可以按照复制链接

**Comment by Johnserf-Seed** [comment]
现在添加了主页作品批量解析下载的功能（加了函数还没写处理），搜索的话之后更新

**Comment by gsc0824** [comment]
你好，不知道具体操作，可以来个简易操作介绍吗

**Comment by Johnserf-Seed** [comment]
> 你好，不知道具体操作，可以来个简易操作介绍吗

已经更新使用教程了哦~ 请移步仓库页面查看
