### ISSUE TITLE
[BUG]下载到一半就报错了怎么办呀？

### ISSUE THREAD

**Issue by ma3252788** [Johnserf-Seed/TikTokDownload#101]
**描述出现的错误**
对bug的清晰而简洁的描述。
下载了23个视频就报错了。

**bug复现**
复现这次行为的步骤：

uid = https://v.douyin.com/N8AmF82/

直接批量下载

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。
![](https://ypyssl.machunjie.com/machunjie/20220304130747.png)

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]  macos 10.15.3
-vpn代理[例如开启、关闭]
-版本[如1.2.3]

**附文**
在此处添加有关此问题的文字。

**Comment by ma3252788** [comment]
看起来是获取不到全部的视频信息。比如这个“https://www.douyin.com/user/MS4wLjABAAAA7EKo_lBub8KInuZgG92yuvyRqMJg8fDW4vzVFcDGHDW_ikp74iJsKToHXjoCmVoE”
只能获取29个视频

**Comment by Grand2018** [comment]
同问，大概下载到第31 或 32的提示一样的错误代码.

**Comment by wheat009** [comment]
同问，我也是此问题

**Comment by Yuhyeong** [comment]
+1

**Comment by Johnserf-Seed** [comment]
#105
