### ISSUE TITLE
[BUG]在centos7.8中使用python3运行TikTokMulti.py，出错

### ISSUE THREAD

**Issue by xuzhihans83** [Johnserf-Seed/TikTokDownload#103]
你好，如题
TikTokDownload V1.2.5，windows版本批量下载视频OK
使用源代码在CentOS7.8中使用python3执行，不OK，
`python3 TikTokMulti.py -u https://v.douyin.com/NLpMsWD/`
如下提示：
“[  提示  ]:未输入命令，自动退出!”

判断：对某些视频比较多的就不OK，比较少的OK(Windows版本的全都OK)
比如：
https://v.douyin.com/NLpMsWD/        不OK
https://v.douyin.com/N2QgjNv/         OK

**Comment by xuzhihans83** [comment]
补充一下，打开了TikTokMulti.py中的：
print(e)

不OK时，提示：
`'aweme_list'`

**Comment by gangchenxi** [comment]
我也这样，解决了吗
