### ISSUE TITLE
[Feature]能否将批量下载后的“已完成批量下载，输入任意键后退出”取消？便于批处理

### ISSUE THREAD

**Issue by xuzhihans83** [Johnserf-Seed/TikTokDownload#104]
如题，谢谢

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/159408348-be756d9a-1c68-4abf-b532-4242635aef32.png)
可自行删除此处代码为，重新使用build.bat编译
