### ISSUE TITLE
输入用户账号批量下载时每次下载30个左右就出错停止下载[BUG]

### ISSUE THREAD

**Issue by uloveqian2021** [Johnserf-Seed/TikTokDownload#105]
**描述出现的错误**
对bug的清晰而简洁的描述。

[  提示  ]:未输入命令或意外出错，自动退出!

**bug复现**
复现这次行为的步骤：
1. 在 TikTokMulti.py 脚本里 .添加抖音账号 parser.add_argument('--user', '-u', default='https://v.douyin.com/NMSMsvK/'）
2. 点击运行 TikTokMulti.py
3.“……”

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/88141320/158020196-a53e7944-1bda-4437-9d47-222f7e0d6fc0.png)

**桌面（请填写以下信息）：**
-操作系统：windows10 64bit
-vpn代理[关闭]
-版本1.2.5

**附文**
在此处添加有关此问题的文字。
输入用户账号批量下载时每次下载30个左右就出错停止下载

**Comment by Grand2018** [comment]
在mac 出现这个问题，
win 下一切正常。

**Comment by wheat009** [comment]
Windows7 has this problem, debian9.10 has this problem, and ubuntu has this problem

**Comment by lei334453** [comment]
me too

**Comment by Yuhyeong** [comment]
+1

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/159407320-3bf01157-cfca-4e02-9372-42b4a0c897af.png)
此问题现已修复，上次更新测试不完善，可以 https://github.com/Johnserf-Seed/TikTokDownload/releases/tag/v1.2.5 
重新下载，此次更新加入了升级脚本
