### ISSUE TITLE
下载单个视频出错[BUG]

### ISSUE THREAD

**Issue by fangwaii** [Johnserf-Seed/TikTokDownload#107]
----没有检测到配置文件，生成中----
----生成成功----
批量下载直接回车，单一视频下载直接粘贴视频链接：9.46 Vlc:/ “痛苦伴随着回报，经历绝境才能重生！”%精神氮泵 %自律 %格斗   https://v.douyin.com/NSur9A2/ 复制此链接，打开Dou音搜索，直接观看视频！
----读取配置完成----
----为您下载单个视频----
https://www.douyin.com/video/7058182846715907342?previous_page=app_code_link
Traceback (most recent call last):
  File "TikTokMulti.py", line 361, in <module>
  File "TikTokMulti.py", line 101, in __init__
  File "TikTokMulti.py", line 137, in judge_link
AttributeError: module 'TikTokDownload' has no attribute 'main'
[6408] Failed to execute script 'TikTokMulti' due to unhandled exception!

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/159407998-6cfa2e77-f145-42d3-bc45-2c9117f4b83c.png)
![image](https://user-images.githubusercontent.com/40727745/159408039-e6fe5b17-2708-4a89-a4f4-5bdbd305ee72.png)
本地测试没问题，TikTokDownload -u https://www.douyin.com/video/7058182846715907342?previous_page=app_code_link
