### ISSUE TITLE
下载的视频不对

### ISSUE THREAD

**Issue by lanhaizhizhou** [Johnserf-Seed/TikTokDownload#109]
大佬为什么我输入的是某人的主页链接，而下载的却是另外一个人的视频呢？╮(╯﹏╰）╭  还有，下载下来的不是最高分辨率啊！请修复一下！

**Comment by Johnserf-Seed** [comment]
提供一下链接

**Comment by Johnserf-Seed** [comment]
能否提供一下链接

**Comment by lanhaizhizhou** [comment]
所有视频都是那样啊！你让我提供什么链接？

JohnserfSeed ***@***.***> 于2022年3月29日周二 08:28写道：

**Comment by Johnserf-Seed** [comment]
> 所有视频都是那样啊！你让我提供什么链接？ JohnserfSeed ***@***.***> 于2022年3月29日周二 08:28写道：
> […](#)

有没有一种可能是我要你提供用户主页的链接我本地测试一下 🤔

**Comment by Johnserf-Seed** [comment]
不回复做删除处理
