### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NobeiAI** [Johnserf-Seed/TikTokDownload#111]
**描述出现的错误**
对bug的清晰而简洁的描述。
[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  提示  ]:读取本地配置完成!
[  提示  ]:批量下载直接回车：
[  提示  ]:为您下载多个视频!
[  提示  ]:用户的sec_id=MS4wLjABAAAAPxAOd0n5D6cRt7FRt0WJmvYCJ-G4cyQ-szZHmXLBzkt!
[  提示  ]:未输入命令，自动退出!

**Comment by Johnserf-Seed** [comment]
用户主页提供一下

**Comment by Dongdong0112** [comment]
> 用户主页提供一下
我也是同样的情况  主页 https://v.douyin.com/8Tn76Nv/
麻烦大佬解决一下 谢谢

**Comment by Dongdong0112** [comment]
现在有些长地址是107位的 
程序默认的长地址是83位的 
所以返回key的值是错的
