### ISSUE TITLE
Linux下载时路径错误

### ISSUE THREAD

**Issue by Extremenne** [Johnserf-Seed/TikTokDownload#112]
大佬，我使用的是linux系统，在修改了conf.ini文件的保存位置后还是出现路径错误，错误如下图，请问该怎么修改啊？![](https://tuchuan2.oss-cn-shenzhen.aliyuncs.com/图床/20220325142002.png)

**Comment by Johnserf-Seed** [comment]
用了正斜杠 / 也报错吗

**Comment by Johnserf-Seed** [comment]
下次更新加入操作系统的判断，是代码里还是反斜杠

**Comment by Extremenne** [comment]
用了正斜杠还是不会下载到相应文件夹中，但是会在文件名前面加入`post\抖音名`

**Comment by Johnserf-Seed** [comment]
我指的是代码中
