### ISSUE TITLE
[BUG]pip安装依赖报错

### ISSUE THREAD

**Issue by Jakob-Boy** [Johnserf-Seed/TikTokDownload#113]
**描述出现的错误**
git clone 后运行源码安装pip3 install -r requirements.txt 报错

**报错代码截图**
<a href="https://imgtu.com/i/qsNAq1"><img src="https://s1.ax1x.com/2022/03/28/qsNAq1.png" alt="qsNAq1.png" border="0" /></a>
**桌面（请填写以下信息）：**
-操作系统：arm64
-版本 latest

**Comment by Johnserf-Seed** [comment]
本地的问题
