### ISSUE TITLE
[BUG]local variable 'key' referenced before assignment

### ISSUE THREAD

**Issue by xuzhihans83** [Johnserf-Seed/TikTokDownload#114]
视频无法下载，打开了“print(e)”
显示：local variable 'key' referenced before assignment

**Comment by Johnserf-Seed** [comment]
具体是哪部分的代码？ 本地从来没有报过这个错

**Comment by xuzhihans83** [comment]
执行：TikTokMulti.py -u https://v.douyin.com/NjrFGVX/
显示：
[  提示  ]:读取命令完成!
[  提示  ]:为您下载多个视频!
[  提示  ]:未输入命令，自动退出!

然后我编辑TikTokMulti.py，把print(e)前面的注释“#”删除，再次执行，则显示：

local variable 'key' referenced before assignment

**Comment by Johnserf-Seed** [comment]
已经修复该bug
