### ISSUE TITLE
[BUG]现在不能批量下载了，主页的链接可能加密了，只能一个也给视频下载了，求更新

### ISSUE THREAD

**Issue by sunwenbo1987** [Johnserf-Seed/TikTokDownload#115]
**描述出现的错误**
对bug的清晰而简洁的描述。

**bug复现**
复现这次行为的步骤：
1.更改了什么什么
2.点击了什么什么
3.“……”

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]
-vpn代理[例如开启、关闭]
-版本[如1.2.3]

**附文**
在此处添加有关此问题的文字。

**Comment by Johnserf-Seed** [comment]
下载没问题，用户主页链接提供一下

**Comment by Johnserf-Seed** [comment]
已经修复该bug  不是抖音的问题，是我代码问题

**Comment by sunwenbo1987** [comment]
> 下载没问题，用户主页链接提供一下

https://v.douyin.com/Ng9tYKs/，还是不能批量下载，修改conf.ini里面的主页链接地址，然后命令行用titokmulti.py，显示错误退出了，如果用单个视频的链接地址，使用titokdownload。py是可以下载单个视频的，求更新

**Comment by Johnserf-Seed** [comment]
![24A30F80-E2EC-4D1C-9FC0-8D477F62B414](https://user-images.githubusercontent.com/40727745/161738029-974eb1a5-310c-4c55-b0f6-3670d9ec2195.png)
这个主页就是有问题的 怎么可能下的成功

**Comment by sunwenbo1987** [comment]
> https://v.douyin.com/Ng9tYKs/

![b982e7d31ba82832038b113335173d1](https://user-images.githubusercontent.com/1742002/162103236-52cab939-531e-48d7-b2d8-c88c35a1acea.jpg)

**Comment by sunwenbo1987** [comment]
> 

![b4b06ec22a5c3765007eb9bc2e3208f](https://user-images.githubusercontent.com/1742002/162104473-0942cd2f-bd26-4fa9-b3ac-b0dee9d4bebd.png)
![edcd6e7c21d5f33a6e1d176e1487c60](https://user-images.githubusercontent.com/1742002/162104490-9825d3e2-8c74-42bd-9891-159b306c577f.png)
