### ISSUE TITLE
[BUG] 03-31最新测试显示失效

### ISSUE THREAD

**Issue by boluohong** [Johnserf-Seed/TikTokDownload#116]
pull最新的源文件
windows7 64bit
测试主页：https://v.douyin.com/NQ7nxxj/
py TikTokMulti.py 
报错如下：

![捕获](https://user-images.githubusercontent.com/58325940/160964666-4f99b9de-b9e2-4379-9834-106c99e0a70d.PNG)

**Comment by cor961** [comment]
只是app分享的短链接失效，网页长链接还是正常的。

**Comment by boluohong** [comment]
> 只是app分享的短链接失效，网页长链接还是正常的。

长链接同样失效

链接 https://www.douyin.com/user/MS4wLjABAAAAxcHTpCJOOvgVpI0aSQFSma3klU9p2qOhIBr5kp28M6A
py  TikTokMulti.py

![捕获](https://user-images.githubusercontent.com/58325940/160966844-97bdf794-9b98-46d2-b2f6-ca43229cbf48.PNG)

**Comment by cor961** [comment]
我这似乎长链接可用。
![image](https://user-images.githubusercontent.com/14720569/160969190-901ceb3c-0505-4e14-9b06-7d83ffe4d853.png)

**Comment by Johnserf-Seed** [comment]
已经修复该bug  不是抖音的问题，是我代码问题
