### ISSUE TITLE
[BUG] Linux下使用TikTokMulti.py时，会报错：local variable 'creat_time' referenced before assignment 

### ISSUE THREAD

**Issue by xuzhihans83** [Johnserf-Seed/TikTokDownload#117]
TikTokMulti.py -u https://v.douyin.com/Njkkqgp/

报错如下：
[  提示  ]:正在对 1530617716000 页进行第 1 次尝试！
[  提示  ]:1527748753000页抓获数据成功!
[  警告  ]:下载视频出错!
[  警告  ]: local variable 'creat_time' referenced before assignment 
[  警告  ]:下载视频出错!
[  警告  ]: local variable 'creat_time' referenced before assignment 
[  警告  ]:下载视频出错!
[  警告  ]: local variable 'creat_time' referenced before assignment 
[  警告  ]:下载视频出错!
[  警告  ]: local variable 'creat_time' referenced before assignment 
[  警告  ]:下载视频出错!
[  警告  ]: local variable 'creat_time' referenced before assignment 
[  提示  ]:正在对 1527748753000 页进行第 1 次尝试！

**Comment by xuzhihans83** [comment]
发现很多链接都会出现这个报错，又比如：
python3 TikTokMulti.py -u https://v.douyin.com/N4FVUj8/

**Comment by Johnserf-Seed** [comment]
Linux目前有bug

**Comment by xuzhihans83** [comment]
短期内不考虑修复？

**Comment by nevertoday** [comment]
我的macos 也有遇到这个问题，这个问题也导致，具体帐号的视频，无法全部被下载，只能部分。
