### ISSUE TITLE
[BUG]TikTokMulti无法批量下载视频了

### ISSUE THREAD

**Issue by xuzhihans83** [Johnserf-Seed/TikTokDownload#120]
[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  提示  ]:读取本地配置完成!
[  提示  ]:批量下载直接回车：
[  提示  ]:为您下载多个视频!
[  提示  ]:用户的sec_id=MS4wLjABAAAAo0hDbJvN_-xEvV3BP6mQJ7azqbhmErfLoPcQES5Lkq4
[  提示  ]:未输入命令或意外出错，自动退出!

**Comment by Johnserf-Seed** [comment]
可以下，要提issues就好好描述问题
