### ISSUE TITLE
未检测到命令

### ISSUE THREAD

**Issue by SingleRottenChips** [Johnserf-Seed/TikTokDownload#124]
下了几个用户，但不知道手残改了哪个文件的哪行，出现：

[  警告  ]:未检测到命令，将使用配置文件进行批量下载!

看了TikTokMulti.py里有相关的，但是看不懂...：

        if uid != None:
            if uid == None:
                print('[  警告  ]:--user不能为空')
                pass
            else:
                self.uid = uid;self.save = dir;self.count=count;self.musicarg=music;self.mode=mode
                print('[  提示  ]:读取命令完成!\r')
                self.judge_link()
        # 没有接收到命令
        else:
            print('[  警告  ]:未检测到命令，将使用配置文件进行批量下载!')

请问是哪里出了问题？

**Comment by Johnserf-Seed** [comment]
配置文件里用户主页的链接

**Comment by SingleRottenChips** [comment]
> 配置文件里用户主页的链接
<img width="279" alt="115截图20220407230904" src="https://user-images.githubusercontent.com/63144489/162231945-96713e8c-a47a-4ad9-a215-a97ecb72e3d3.png">

我看不出来问题呢....

**Comment by Johnserf-Seed** [comment]
具体报什么错呢

**Comment by SingleRottenChips** [comment]
我不知道哪里看报什么错：

[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  提示  ]:读取本地配置完成!
[  提示  ]:批量下载直接回车：
[  提示  ]:为您下载多个视频!
[  提示  ]:用户的sec_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[  提示  ]:未输入命令或意外出错，自动退出!

我之前是用的是大佬给的exe 现在是在pycharm里运行Tiktokmulti.py 
再下了一遍，还是成功下了两三个用户之后就又报错诶......

**Comment by SingleRottenChips** [comment]
[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  提示  ]:读取本地配置完成!
[  提示  ]:批量下载直接回车：
[  提示  ]:为您下载多个视频!
[  提示  ]:用户的sec_id=MS4wLjABAAAAFlX9iE4dABpyBl4im76mr8ULdiIHBa0N789nqzX-1lo
[  提示  ]:未输入命令或意外出错，自动退出!

**Comment by SingleRottenChips** [comment]
![image](https://user-images.githubusercontent.com/63144489/162374014-7692f022-70e5-446c-b9d2-b4504bb4ad5b.png)

呃，上一条的文字居然没显示出来

**Comment by SingleRottenChips** [comment]
之前成功的几次也有[警告]，但是正常下载，未出现提示。

**Comment by yuzhezz** [comment]
> 之前成功的几次也有[警告]，但是正常下载，未出现提示。

我今天也发现了这个问题 测试后发现部分用户的sec_uid从56位变为77位 想必bug的原因是这个 使用最新的Tiktokmulti.py就可以获取到了

**Comment by yuzhezz** [comment]
> > 之前成功的几次也有[警告]，但是正常下载，未出现提示。
> 
> 我今天也发现了这个问题 测试后发现部分用户的sec_uid从56位变为77位 老的脚本正则取不到改变后的sec_uid 想必bug的原因是这个 使用最新的Tiktokmulti.py就可以获取到了

**Comment by SingleRottenChips** [comment]
> > 之前成功的几次也有[警告]，但是正常下载，未出现提示。
> 
> 我今天也发现了这个问题 测试后发现部分用户的sec_uid从56位变为77位 想必bug的原因是这个 使用最新的Tiktokmulti.py就可以获取到了

"最新的"指的是最新的版本吗？我用的就是最新的诶

**Comment by yuzhezz** [comment]
> > > 之前成功的几次也有[警告]，但是正常下载，未出现提示。
> > 
> > 
> > 我今天也发现了这个问题 测试后发现部分用户的sec_uid从56位变为77位 想必bug的原因是这个 使用最新的Tiktokmulti.py就可以获取到了
> 
> "最新的"指的是最新的版本吗？我用的就是最新的诶

https://github.com/Johnserf-Seed/TikTokDownload/blob/main/TikTokMulti.py

**Comment by SingleRottenChips** [comment]
> > > > 之前成功的几次也有[警告]，但是正常下载，未出现提示。
> > > 
> > > 
> > > 我今天也发现了这个问题 测试后发现部分用户的sec_uid从56位变为77位 想必bug的原因是这个 使用最新的Tiktokmulti.py就可以获取到了
> > 
> > 
> > "最新的"指的是最新的版本吗？我用的就是最新的诶
> 
> https://github.com/Johnserf-Seed/TikTokDownload/blob/main/TikTokMulti.py

还是不行呢......

**Comment by ForLuoLi** [comment]
我也是一直显示未检测到命令，点击回车之后会闪退

**Comment by Johnserf-Seed** [comment]
最新版本已经修复，重新拉一下
