### ISSUE TITLE
[BUG]TikTokMulti 下载的分辨率和TikTokDownload不一样

### ISSUE THREAD

**Issue by 8RedBulls** [Johnserf-Seed/TikTokDownload#125]
TikTokMulti.exe 下载的单个视频大小和TikTokDownload不一样
一个是分辨率一个1024x576 一个是1280x720
电脑网页拉的dy的视频一般都是1280*720。

**Comment by Johnserf-Seed** [comment]
两个程序里下载作品信息接口都是一样的 具体没测试过作品清晰度问题。是相同视频两种分辨率吗

**Comment by 8RedBulls** [comment]
> 

是的，同一个视频的清晰度分辨率有点差别。

我试过网页版抖音用插件下载和TikTokDownload单个下载的是一样的文件大小和分辨率

只有批量的时候会变。

**Comment by double-point** [comment]
刚试了下，确实批量下载的分辨率是1024x576，而单个下载的分辨率是1280x720

**Comment by cor961** [comment]
我这里测试网页直接用工具下载是1920，dy app和TikTokDownload下载是1280，TikTokMulti下载是1024，分辨率依次递减。

**Comment by Johnserf-Seed** [comment]
新版已经支持下载1080p视频
