### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sym9518** [Johnserf-Seed/TikTokDownload#128]
1、like模式，视频重复下载，不能跳过已下载视频。
2、下载自己主页里所有点赞视频时，视频保存目录文件夹的建立是以最后点赞用户ID确定的，每次有新点赞，都会建立新的文件夹，重复下载。

**Comment by Dongdong0112** [comment]
> 1、like模式，视频重复下载，不能跳过已下载视频。 2、下载自己主页里所有点赞视频时，视频保存目录文件夹的建立是以最后点赞用户ID确定的，每次有新点赞，都会建立新的文件夹，重复下载。

我改了一下
https://github.com/Dongdong0112/douyin
就是194行这里面的“”改成你喜欢的就行了

**Comment by sym9518** [comment]
> 



> > 1、like模式，视频重复下载，不能跳过已下载视频。 2、下载自己主页里所有点赞视频时，视频保存目录文件夹的建立是以最后点赞用户ID确定的，每次有新点赞，都会建立新的文件夹，重复下载。
> 
> 我改了一下 https://github.com/Dongdong0112/douyin 就是194行这里面的“”改成你喜欢的就行了

已解决，棒
