### ISSUE TITLE
连接不上,好像废了???

### ISSUE THREAD

**Issue by at89s52rc** [Johnserf-Seed/TikTokDownload#13]
![QQ截图20210527095117](https://user-images.githubusercontent.com/20987907/119753472-695bd380-bed1-11eb-9bf1-1ebb4c1e8b50.png)
![QQ截图20210527095021](https://user-images.githubusercontent.com/20987907/119753491-737dd200-bed1-11eb-9af9-e70e32e81dd5.png)

**Comment by Johnserf-Seed** [comment]
你本地网络环境问题，请自行paichga

**Comment by Johnserf-Seed** [comment]
你本地网络环境问题，请自行排查

**Comment by at89s52rc** [comment]
> 您本地网络环境问题，请自行排查

请问作者,这个是要梯子吗,但用了梯子后,出现这种错误


![QQ截图20210527100441](https://user-images.githubusercontent.com/20987907/119754382-fd7a6a80-bed2-11eb-9c20-143b1d13fe1f.png)

**Comment by Johnserf-Seed** [comment]
千不该万不该加代理哈哈哈，有代理关代理，有fidder等抓包软件都要关掉

**Comment by Johnserf-Seed** [comment]
接口完全都是抖音官方的，连接失败就是本地的网络环境问题了

**Comment by at89s52rc** [comment]
> 接口完全都是抖音官方的，连接失败就是本地的网络环境问题了

作者是win10测试的吗,我是win7,测试失败,如果是这样的话,那可能就是win7的TLS的锅了

**Comment by Johnserf-Seed** [comment]
是win10 测试的，但是我本人也在win7中测试过，也没有遇到什么问题。可以ping一下 www.iesdouyin.com

**Comment by at89s52rc** [comment]
> 是win10 测试的，但是我本人也在win7中测试过，也没有遇到什么问题。可以ping一下 [www.iesdouyin.com](http://www.iesdouyin.com)

作者大大,我弱弱的问一下,这个是下抖音的,还是tiktok海外版的,我看了源码后,发了个抖音连接就可以,但tiktok就不行,因为要梯子才能打开,你这个项目是下载抖音的吧,tiktok不行的吧,我看着写着tiktok以为是下载海外版的,是这样吗

**Comment by Johnserf-Seed** [comment]
> > 是win10 测试的，但是我本人也在win7中测试过，也没有遇到什么问题。可以ping一下 [www.iesdouyin.com](http://www.iesdouyin.com)
> 
> 作者大大,我弱弱的问一下,这个是下抖音的,还是tiktok海外版的,我看了源码后,发了个抖音连接就可以,但tiktok就不行,因为要梯子才能打开,你这个项目是下载抖音的吧,tiktok不行的吧,我看着写着tiktok以为是下载海外版的,是这样吗

目前还只有国内抖音的解析，之后会加入海外版的😉
