### ISSUE TITLE
[BUG]运行时出现未找到命令

### ISSUE THREAD

**Issue by luodingquan** [Johnserf-Seed/TikTokDownload#130]
![image](https://user-images.githubusercontent.com/47214142/163504655-bc7283bb-0773-445a-b470-fcf3ece9dbc0.png)
运行时出现未找到命令是什么原因 重装系统之后就好像不行了 之前可以正常用

**Comment by Johnserf-Seed** [comment]
本地测试并无该情况

**Comment by Johnserf-Seed** [comment]
建议直接使用exe
