### ISSUE TITLE
视频命名问题 emoji去除

### ISSUE THREAD

**Issue by sym9518** [Johnserf-Seed/TikTokDownload#131]
视频下载 保存的文件名含有Unicode字符的emoji 可否加个匹配直接替换掉 谢

![微信截图_20220416093033](https://user-images.githubusercontent.com/19207579/163656754-3d40e714-9e1b-48dc-a925-7629c60f5f23.png)

**Comment by Johnserf-Seed** [comment]
https://pypi.org/project/emoji/
参考这个库

**Comment by sym9518** [comment]
> https://pypi.org/project/emoji/ 参考这个库

好咧 谢谢
