### ISSUE TITLE
[BUG]图文类型视频下载后没有内容的问题

### ISSUE THREAD

**Issue by yuzhezz** [Johnserf-Seed/TikTokDownload#135]
批量下载后发现有部分在客户端分类为图集的视频 下载后只有音乐没有内容 
举例"aweme_id": "7055241867968924967"
分析后发现作品类型由aweme_type字段来区分 aweme_type=2则作品为图集 图片下载链接可以在[官方接口](https://www.iesdouyin.com/web/api/v2/aweme/iteminfo/?item_ids=7055241867968924967)中获取到
可否在接下来的更新中做一些判断 将图集类型下载为图片 
![image](https://user-images.githubusercontent.com/59724132/163721556-c7dd972b-7da3-4231-b4d8-d51d310b08fa.png)
![image](https://user-images.githubusercontent.com/59724132/163721580-085d1fe9-36fd-4b6b-941b-d8e75247780f.png)

**Comment by Johnserf-Seed** [comment]
图集下载功能马上更新

**Comment by Johnserf-Seed** [comment]
已经更新图集下载功能
