### ISSUE TITLE
[BUG] 无法进行全部作品下载

### ISSUE THREAD

**Issue by hyakkiyakous** [Johnserf-Seed/TikTokDownload#139]
**无法进行全部作品下载**
目前版本好像无法将一个作者的所有作品进行一次性多个下载..数量停留在了33-35个，然后显示首页没有xxx个视频，跳过下载。之前二月使用的版本貌似可以下载全部，想问一下Johnserf这个是否跟官方api接口有关？还是跟目前版本代码有关？

**bug复现**
复现这次行为的步骤：
1.重新下载了新版本的1.2.5

**截图**
么得截图..

**桌面（请填写以下信息）：**
-操作系统：Windows 11 64 bits
-vpn代理：关闭
-版本 1.2.5

**Comment by Johnserf-Seed** [comment]
目前本地测试没有出现过抓取失败的情况 可否提供一下链接 我测试

**Comment by 8RedBulls** [comment]
> 目前本地测试没有出现过抓取失败的情况 可否提供一下链接 我测试

[  提示  ]:该页视频资源没有 35 个,已为您跳过！
[  提示  ]:正在对 1615212000000 页进行第 1 次尝试！
[  提示  ]:1608904801000页抓获数据成功!


大概是这个样子的：
1.2.5开始的时候能全部下载资源，但是批量下载我之前提交Bug说和单个下载分辨率不一样，
你升级能下载1080p后，我又把之前的下载都下载一遍，然后用Duplicate Cleaner清除重复标题的，发现原下载里还剩余好多，试了一下，对比了一下大概就在上面的提示时的跳过的视频没下载。有时候连续跳过，有时候偶尔一两个。
测试链接：
[https://www.douyin.com/user/MS4wLjABAAAANXnhmiKiWKeq-HNVJkhhuxC8T44umDa040HCNs06X08](url)

**Comment by Johnserf-Seed** [comment]
并没有你描述的这种情况，我用一台没装任何环境的电脑测试，甚至连报错都没有。有很多issue我本地测试均通过.建议使用目录下的update.bat获取最新编译版本
![无标题](https://user-images.githubusercontent.com/40727745/165423397-e6d35e8c-d8c8-4083-a836-42316b1e67d9.png)

**Comment by 8RedBulls** [comment]
> 并没有你描述的这种情况，我用一台没装任何环境的电脑测试，甚至连报错都没有。有很多issue我本地测试均通过.建议使用目录下的update.bat获取最新编译版本 ![无标题](https://user-images.githubusercontent.com/40727745/165423397-e6d35e8c-d8c8-4083-a836-42316b1e67d9.png)

我是用的console下载的，直接双击TikTokMulti.exe也一样会丢，后面我把count改成1了就能下载之前的下丢的。
