### ISSUE TITLE
Metadata by Username

### ISSUE THREAD

**Issue by Kikiss18** [Johnserf-Seed/TikTokDownload#14]
Hello Johnserf-Seed,

Thank you for your work!

Is it possible to have only the metadata of TikToks by Username? 
Like all the data from Milo大人 ... video title, text, music title, artist name, likes_counts, views_counts, comment_counts, etc?

Please can you provide one clear example? 

谢谢!

**Comment by Johnserf-Seed** [comment]
If you download videos with user names, you will use many tiktok users, so you can download them only by the unique jitter, which is the link shared by the user homepage
如果用用户名去下载视频的话就会用很多重名的用户，所以只能通过唯一的抖音号，即用户主页分享的链接来下载
