### ISSUE TITLE
如何下载1080p

### ISSUE THREAD

**Issue by EddyN8** [Johnserf-Seed/TikTokDownload#142]
有没有下载1080P功能，之前用过一解析网站，能下载1920x1080 谢谢！

https://user-images.githubusercontent.com/37077917/164722389-c53c9452-8d78-477c-aacf-7b99f04d2ce2.mp4

**Comment by Johnserf-Seed** [comment]
我的问题，下次更新加入  是可以解析的😊

**Comment by Johnserf-Seed** [comment]
新版已经支持下载1080p视频
