### ISSUE TITLE
[BUG]出现IndexError: list index out of range 下载单个视频时出现

### ISSUE THREAD

**Issue by lingr7** [Johnserf-Seed/TikTokDownload#143]
**描述出现的错误**
确定是单个视频链接，但仍然出现了IndexError: list index out of range的错误

**bug复现**
使用pip安装的，在venv环境下运行pip安装好的脚本
```
D:\github_room\testtiktokdownload\venv\Scripts\python.exe D:/github_room/testtiktokdownload/venv/Lib/site-packages/TikTokDownload/TikTokDownload.py
请输入抖音链接:https://v.douyin.com/FdCpfch/

```
将链接更改为该脚本中的样例 https://v.douyin.com/JtcjTwo/ 同样报错
**截图**
![image](https://user-images.githubusercontent.com/37898999/164910333-3eb39e08-d0dd-4813-8802-79414bd40262.png)

**桌面（请填写以下信息）：**
-操作系统：windows10 64bit
-vpn代理:[关闭]
-版本:1.2.3

**附文**
在此处添加有关此问题的文字。

**Comment by Johnserf-Seed** [comment]
![1650724375(1)](https://user-images.githubusercontent.com/40727745/164910413-e37bb4a3-24bb-432a-96df-f9a3f28ce6bf.png)
测试过，可以下载   。实例链接已经挂了，可能是视频作者删除了

**Comment by lingr7** [comment]
我这边运行确实出现了这个问题，这个Bug确实出现了，我这边运行并不能下载。实例链接报的错也先是报IndexError: list index out of range的错。
我通过web项目实现了下载，那边遇到了配置环境问题，我写了一个Dockerfile来解决，相关issue和PR：https://github.com/Johnserf-Seed/TikTokWeb/issues/1， https://github.com/Johnserf-Seed/TikTokWeb/pull/2

**Comment by lingr7** [comment]
本环境使用Pycharm社区版venv创建虚拟环境 python 3.8
软件包          版本    
TikTokDownload	1.2.3
certifi	2021.10.8
charset-normalizer	2.0.12
idna	3.3
pip	21.3.1
requests	2.27.1
retrying	1.3.3
setuptools	60.2.0
six	1.16.0	1.16.0
urllib3	1.26.9
wheel	0.37.1
![env环境如下](https://user-images.githubusercontent.com/37898999/164955382-5b83e4ae-8079-4de9-bdcf-df2157f14ca6.png)

**Comment by Johnserf-Seed** [comment]
请检查是否为最新版代码 用git工具重新pull一遍

**Comment by lingr7** [comment]
使用本项目最新代码，安装依赖，问题不再出现，正常保存视频，问题应该是出在pip安装的包上，那里的代码可能有问题。
