### ISSUE TITLE
[BUG]能够下载抖音主页发布的视频，但无法下载抖音点赞视频

### ISSUE THREAD

**Issue by tangshihai999** [Johnserf-Seed/TikTokDownload#147]
**描述出现的错误**

修改好配置文件后，mode = post,打开程序TiktokMulti.exe,程序可正常下载视频。
修改好配置文件后，mode = like,打开程序TiktokMulti.exe,程序闪退

**bug复现**
复现这次行为的步骤：
1.更改了什么什么
2.点击了什么什么
3.“……”

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]
-vpn代理[例如开启、关闭]
-版本[如1.2.3]

**附文**
在此处添加有关此问题的文字。

**Comment by Johnserf-Seed** [comment]
需要开放抖音权限才可以

**Comment by Johnserf-Seed** [comment]
用户没开放点赞列表就无法下载

**Comment by tangshihai999** [comment]
> 需要开放抖音权限才可以

我下载的是自己账号的点赞视频，要怎么开放权限

**Comment by Johnserf-Seed** [comment]
> > 需要开放抖音权限才可以
> 
> 我下载的是自己账号的点赞视频，要怎么开放权限

需要自己账号打开所有人可以看见你的点赞

**Comment by tangshihai999** [comment]
> > > 需要开放抖音权限才可以
> > 
> > 
> > 我下载的是自己账号的点赞视频，要怎么开放权限
> 
> 需要自己账号打开所有人可以看见你的点赞

我权限开放了，可以下载，但是是下载别的用户的视频，这是怎么回事？

**Comment by Johnserf-Seed** [comment]
> > > > 需要开放抖音权限才可以
> > > 
> > > 
> > > 我下载的是自己账号的点赞视频，要怎么开放权限
> > 
> > 
> > 需要自己账号打开所有人可以看见你的点赞
> 
> 我权限开放了，可以下载，但是是下载别的用户的视频，这是怎么回事？

你点赞的视频不就是别人发布的吗

**Comment by tangshihai999** [comment]
> 



> > > > > 需要开放抖音权限才可以
> > > > 
> > > > 
> > > > 我下载的是自己账号的点赞视频，要怎么开放权限
> > > 
> > > 
> > > 需要自己账号打开所有人可以看见你的点赞
> > 
> > 
> > 我权限开放了，可以下载，但是是下载别的用户的视频，这是怎么回事？
> 
> 你点赞的视频不就是别人发布的吗

好的，谢谢楼主了

**Comment by tangshihai999** [comment]
> > 
> 
> > > > > > 需要开放抖音权限才可以
> > > > > 
> > > > > 
> > > > > 我下载的是自己账号的点赞视频，要怎么开放权限
> > > > 
> > > > 
> > > > 需要自己账号打开所有人可以看见你的点赞
> > > 
> > > 
> > > 我权限开放了，可以下载，但是是下载别的用户的视频，这是怎么回事？
> > 
> > 
> > 你点赞的视频不就是别人发布的吗
> 
> 好的，谢谢楼主了

下载中断后，重新下载还会将原来的视频下载一次，这个要怎么解决
