### ISSUE TITLE
[BUG] 保存文件的路径对Mac和Linux不友好

### ISSUE THREAD

**Issue by aephi** [Johnserf-Seed/TikTokDownload#150]
问题：在Mac下，整个路径变成了文件名的一部分，没有自动建立post 、用户名的目录
建议：保存路径部分的代码 + "\\" +  改为直接用Python的path拼接，或者用正斜线（印象中Windows是兼容正斜线的）

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/commit/e779f4a9e0aec48348dd3b8fa42c974394b81dda
