### ISSUE TITLE
下载了那个zip文件，解压后不会使用，看这些配置什么的也看不懂，双击build文件提示PIP不是内部命令

### ISSUE THREAD

**Issue by gitbird88** [Johnserf-Seed/TikTokDownload#153]
**描述您想要的功能**
对你想要加入的功能的清晰而简洁的描述。
下载了那个zip文件，解压后不会使用，看这些配置什么的也看不懂，双击build文件提示PIP不是内部命令

**描述你想要替换的功能或需要修改的解决方案**
对您考虑过的任何替代解决方案或功能的清晰简洁的描述。
要是那些简单的EXE文件打开安装就好了
**附文**
在此处添加有关功能请求的任何其他文字或屏幕截图。

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/releases/tag/v1.2.5
