### ISSUE TITLE
[Feature] 我点赞过/收藏过的视频

### ISSUE THREAD

**Issue by zjplab** [Johnserf-Seed/TikTokDownload#155]
很多视频没点赞过/没收藏过的没啥意思 可以过滤

`webbrowser` 包据说可以调用默认浏览器 不知道能不能实现查看视频页面-查询是否点赞过-过滤的功能

**Comment by Johnserf-Seed** [comment]
抖音有现成接口，不过需要登录

**Comment by zjplab** [comment]
> 抖音有现成接口，不过需要登录

可以要求登录啊

**Comment by zjplab** [comment]
> 抖音有现成接口，不过需要登录

请问有具体接口说明吗
