### ISSUE TITLE
[BUG] IndexError: list index out of range

### ISSUE THREAD

**Issue by sadazs** [Johnserf-Seed/TikTokDownload#156]
I just try on win10 and ubuntu but all get issue IndexError: list index out of range
try to check url all ok

**Comment by Johnserf-Seed** [comment]
video links, and user home page link is different

**Comment by sadazs** [comment]
> video links, and user home page link is different

I use user home page link

**Comment by Johnserf-Seed** [comment]
> > video links, and user home page link is different
> 
> I use user home page link

do you show me see these home page links, please

**Comment by sadazs** [comment]
> > > video links, and user home page link is different
> > 
> > 
> > I use user home page link
> 
> do you show me see these home page links, please

Exp: https://v.douyin.com/FfTVJYQ/
