### ISSUE TITLE
去水印没有效果呀 大佬

### ISSUE THREAD

**Issue by ytrlmy521** [Johnserf-Seed/TikTokDownload#160]
通过单个视频下载的视频，水印还是一直在的。这是还有什么配置没打开嘛，求解答下。下图：
![image](https://user-images.githubusercontent.com/19338049/169938703-0c819dd1-062c-47df-b148-7ac2dea34a82.png)

**Comment by Johnserf-Seed** [comment]
这是人家作者加在视频里的水印，不是抖音官方生成的分享水印 何来去除一说
