### ISSUE TITLE
某些链接报错：未输入命令或意外出错，自动退出!

### ISSUE THREAD

**Issue by hostemail** [Johnserf-Seed/TikTokDownload#162]
1.2.5版本，遇到某些链接会报错，比如其中一个：
 https://v.douyin.com/FWRpdsU/
 
 
[  提示  ]:读取命令完成!
[  提示  ]:为您下载多个视频!
[  提示  ]:用户的sec_id=MS4wLjABAAAA7F9srUZmSoxPRcywewClYslUk8ysERHVrz6srz0eNow
[  提示  ]:未输入命令或意外出错，自动退出!

**Comment by hostemail** [comment]
[  提示  ]:读取命令完成!
[  提示  ]:为您下载多个视频!
[  提示  ]:用户的sec_id=MS4wLjABAAAA7F9srUZmSoxPRcywewClYslUk8ysERHVrz6srz0eNow
[  提示  ]:未输入命令或意外出错，自动退出!

**Comment by hostemail** [comment]
用户的sec_id=MS4wLjABAAAA7F9srUZmSoxPRcywewClYslUk8ysERHVrz6srz0eNow
未输入命令或意外出错，自动退出!

**Comment by Johnserf-Seed** [comment]
是因为一些用户名的非法字符没有做过滤，下次推送更新
