### ISSUE TITLE
[BUG]运行update.bat出现错误

### ISSUE THREAD

**Issue by mj900912** [Johnserf-Seed/TikTokDownload#165]
**描述出现的错误**
前一个星期还用的好好的。这两天重装系统之后。直接解压后，运行update.bat批处理文件，出现相关错误提示。因为是原文件直接解压的，重新下载，比对错误提示行，也没发现问题。

**bug复现**
复现这次行为的步骤：
1.重装了windows系统
2.点击update.bat处理文件

**截图**

![微信图片_20220603162546](https://user-images.githubusercontent.com/101454871/171817935-95329e6a-73e3-43f2-ad16-4a9546e170c0.png)

![微信图片_20220603162601](https://user-images.githubusercontent.com/101454871/171817940-d8f4cea7-2742-4e6c-af77-291bd82648ef.png)

**桌面（请填写以下信息）：**
-操作系统：[windows8 64bit]
-无VPN,但是因为无法打开github，修改了hosts文件
-版本[如1.2.3]

**附文**

**Comment by Johnserf-Seed** [comment]
重装系统后可能是msxml3.dll组件版本低，或者文件可能损坏。如果访问https://github.com/Johnserf-Seed/TikTokDownload/releases 界面正常那可能是前面的问题。
