### ISSUE TITLE
tiktok 链接不起作用，请帮助我如何使用此下载 tiktok 视频。我非常需要它。

### ISSUE THREAD

**Issue by munazza3242** [Johnserf-Seed/TikTokDownload#166]
我正在尝试从 tiktok 应用程序下载视频，例如这种类型的链接 
https://www.tiktok.com/@tngaa45

 但这给了我错误，所以如果您没有在此添加此功能，请添加如果您立即为没有水印的 tiktok 视频制作另一个这样的代码会更好。谢谢你

**Comment by qiankunxienb** [comment]
This project is used to download Douyin which is Chinese version of Tiktok. The name of this project is confused.

**Comment by zjplab** [comment]
别的项目支持:https://github.com/Evil0ctal/Douyin_TikTok_Download_API/blob/main/scraper.py

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/f2
