### ISSUE TITLE
可单独设置下载视频和音频

### ISSUE THREAD

**Issue by tjj2577097637** [Johnserf-Seed/TikTokDownload#17]
每次下载时都把音频下载了，希望conf.ini里可以设置是否下载音频的功能

**Comment by Johnserf-Seed** [comment]
配置文件中有的哦 musicarg = no 就可以了

**Comment by tjj2577097637** [comment]
我在配置文件里面这样设置的，结果还是会下载音频
[url]
uid = https://v.douyin.com/egFM5jb/

[music]
musicarg = no

[count]
count = 999

[save]
url = .\Download\

[mode]
mode = post

**Comment by Johnserf-Seed** [comment]
已经修复

**Comment by Johnserf-Seed** [comment]
更新一下仓库
