### ISSUE TITLE
部分视频会直接闪退

### ISSUE THREAD

**Issue by 1dunTNT** [Johnserf-Seed/TikTokDownload#171]
视频地址：https://v.douyin.com/YHoSMrR/

闪退录屏截图
![image](https://user-images.githubusercontent.com/57804867/175562593-04654659-4451-46ed-ba01-8b30a66bfea1.png)

![image](https://user-images.githubusercontent.com/57804867/175562674-b2090978-fe4e-4f6b-a2db-3e8fad5101c4.png)

**Comment by Johnserf-Seed** [comment]
> 地址填错了，地址应该是主页地址，问题可以关了。 提两个小建议
> 
> 1. 文件夹名可以再用户名的基础上加抖音ID，例：张三-123456
> 2. 具备增量下载的功能，如昨天下载了用户的所有视频，今天用户新增了一条视频，只需要提示并下载新增的即可

1的建议很好，2已经具备
