### ISSUE TITLE
可以添加抖音播放列表视频批量下载功能吗？

### ISSUE THREAD

**Issue by Dragon-97** [Johnserf-Seed/TikTokDownload#174]
可以添加抖音播放列表视频批量下载功能吗？ . 我想选择此播放列表的第一集 ID。 从那里，下一集的下载视频将自动出现。
我希望您进一步开发此功能。
非常感谢

**Comment by Johnserf-Seed** [comment]
因为获取你的推荐播放列表需要登陆账号，为了账号的安全考虑不会开发，抱歉啦 如果因为爬虫被封号 那太不好了

**Comment by Johnserf-Seed** [comment]
新版支持了
