### ISSUE TITLE
什么时候可以批量下载图文呢

### ISSUE THREAD

**Issue by WangDrama** [Johnserf-Seed/TikTokDownload#179]
什么时候可以批量下载图文呢

**Comment by Johnserf-Seed** [comment]
我太bai懒lan了

**Comment by Dongdong0112** [comment]
可以试试我的 原本作者还没出图集下载的时候自己 自学了一点python 照着作者写了一个（写的不好但是能用 在[Releases](https://github.com/Dongdong0112/PicDownload/releases)里面）

**Comment by WangDrama** [comment]
我模范下载视频的写了一个批量下载图集，谢谢发自我的iPhone------------------ 原始邮件 ------------------发件人: JohnserfSeed  ***@***.***>发送时间: 2022年7月20日 01:25收件人: Johnserf-Seed/TikTokDownload ***@***.***>抄送: WangDrama ***@***.***>, Author ***@***.***>主题: Re: [Johnserf-Seed/TikTokDownload] 什么时候可以批量下载图文呢 (Issue #179)

可以试试我的 原本作者还没出图集下载的时候自己 自学了一点python 照着作者写了一个（写的不好但是能用 在Releases里面）

你写了这么多 我以为你完成了用户主页的图集批量下载，5月底我已经更新了图集下载功能了 只不过由于网页用户主页不能获取到所有的图集视频 就暂时没做批量

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Johnserf-Seed/TikTokDownload/issues/179#issuecomment-1189360701",
"url": "https://github.com/Johnserf-Seed/TikTokDownload/issues/179#issuecomment-1189360701",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Johnserf-Seed** [comment]
现已支持批量下载用户主页时，下载所有图集

**Comment by gaawinglf** [comment]
> 现已支持批量下载用户主页时，下载所有图集

试用TikTokMulti批量下载用户主页时，图集下载失败
![image](https://user-images.githubusercontent.com/64972644/187445653-d6740f5e-ab72-424c-8047-0baa48fb3487.png)

**Comment by Johnserf-Seed** [comment]
> > 现已支持批量下载用户主页时，下载所有图集
> 
> 试用TikTokMulti批量下载用户主页时，图集下载失败
> ![image](https://user-images.githubusercontent.com/64972644/187445653-d6740f5e-ab72-424c-8047-0baa48fb3487.png)
> 

用tiktoktool，multi不会更新了

**Comment by gaawinglf** [comment]
> > > 现已支持批量下载用户主页时，下载所有图集
> > 
> > 
> > 试用TikTokMulti批量下载用户主页时，图集下载失败
> > ![image](https://user-images.githubusercontent.com/64972644/187445653-d6740f5e-ab72-424c-8047-0baa48fb3487.png)
> 
> 用tiktoktool，multi不会更新了

换成tool后能正确读取到用户，但是下载会报错，exe和python都试过执行了……
![image](https://user-images.githubusercontent.com/64972644/187449745-1a4204e6-055c-4f2c-b976-332b4b427798.png)

**Comment by Johnserf-Seed** [comment]
> > > > 现已支持批量下载用户主页时，下载所有图集
> > > 
> > > 
> > > 试用TikTokMulti批量下载用户主页时，图集下载失败
> > > ![image](https://user-images.githubusercontent.com/64972644/187445653-d6740f5e-ab72-424c-8047-0baa48fb3487.png)
> > 
> > 用tiktoktool，multi不会更新了
> 
> 换成tool后能正确读取到用户，但是下载会报错，exe和python都试过执行了……
> ![image](https://user-images.githubusercontent.com/64972644/187449745-1a4204e6-055c-4f2c-b976-332b4b427798.png)
> 

没有考虑到有的作品是不带定位的😵

**Comment by Johnserf-Seed** [comment]
> > > > 现已支持批量下载用户主页时，下载所有图集
> > > 
> > > 
> > > 试用TikTokMulti批量下载用户主页时，图集下载失败
> > > ![image](https://user-images.githubusercontent.com/64972644/187445653-d6740f5e-ab72-424c-8047-0baa48fb3487.png)
> > 
> > 用tiktoktool，multi不会更新了
> 
> 换成tool后能正确读取到用户，但是下载会报错，exe和python都试过执行了……
> ![image](https://user-images.githubusercontent.com/64972644/187449745-1a4204e6-055c-4f2c-b976-332b4b427798.png)
> 

可以重新拉一下新代码 已经修复

**Comment by gaawinglf** [comment]
> 

很感谢你修复bug，但是😂现在会报如图所示的bug，大部分图片获取不到
![image](https://user-images.githubusercontent.com/64972644/187466141-b3d3b37a-7679-47b6-9396-b40d71d32a68.png)

**Comment by Johnserf-Seed** [comment]
> > 
> 
> 很感谢你修复bug，但是😂现在会报如图所示的bug，大部分图片获取不到
> ![image](https://user-images.githubusercontent.com/64972644/187466141-b3d3b37a-7679-47b6-9396-b40d71d32a68.png)
> 

为什么我本地测速了可以
[]!(http://img04.sogoucdn.com/app/a/200678/8198c9691875172f1a757fe4fc0e41ef.jpg)

**Comment by Johnserf-Seed** [comment]
> > 
> 
> 很感谢你修复bug，但是😂现在会报如图所示的bug，大部分图片获取不到 ![image](https://user-images.githubusercontent.com/64972644/187466141-b3d3b37a-7679-47b6-9396-b40d71d32a68.png)



> > 
> 
> 很感谢你修复bug，但是😂现在会报如图所示的bug，大部分图片获取不到 ![image](https://user-images.githubusercontent.com/64972644/187466141-b3d3b37a-7679-47b6-9396-b40d71d32a68.png)

本地测试没有下载出错的问题
![image](https://user-images.githubusercontent.com/40727745/187467894-a728bceb-cd32-46c6-91de-1d4efb032c84.png)

![image](https://user-images.githubusercontent.com/40727745/187468027-dd745809-7c32-4264-a673-b9ef9cde1024.png)

**Comment by Johnserf-Seed** [comment]
> > 
> 
> 很感谢你修复bug，但是😂现在会报如图所示的bug，大部分图片获取不到 ![image](https://user-images.githubusercontent.com/64972644/187466141-b3d3b37a-7679-47b6-9396-b40d71d32a68.png)

![image](https://user-images.githubusercontent.com/40727745/187468232-9b5bd5ec-ba7a-4155-83ee-1690efb7553e.png)

**Comment by Johnserf-Seed** [comment]
可以清理一下pic文件夹再试试

**Comment by gaawinglf** [comment]
> 可以清理一下pic文件夹再试试

😂生成的exe不能成功下载图集，直接运行python下载没问题 才发现
