### ISSUE TITLE
支持tiktok下载吗

### ISSUE THREAD

**Issue by dahuilanggit** [Johnserf-Seed/TikTokDownload#180]
支持tiktok下载吗

**Comment by Johnserf-Seed** [comment]
最近准备更新了

**Comment by RIP-GitHub** [comment]
期待...

**Comment by HelloZhou3301** [comment]
现在可以了吗

**Comment by liuliuzx** [comment]
> 最近准备更新了

催更了老哥

**Comment by HelloZhou3301** [comment]
> > 最近准备更新了
> 
> 催

> > 最近准备更新了
> 
> 催更了老哥

想搞搬运，嘿嘿

**Comment by zjplab** [comment]
别的项目的代码可以参考: https://github.com/Evil0ctal/Douyin_TikTok_Download_API/blob/main/scraper.py

**Comment by By-Tian** [comment]
> 最近准备更新了

现在可以了吗？支持tiktok国际版的下载，和批量下载

**Comment by HelloZhou3301** [comment]
好耶！




周楚程
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Johnserf-Seed/TikTokDownload"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月12日(星期一) 下午3:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Johnserf-Seed/TikTokDownload] 支持tiktok下载吗 (Issue #180)





  
最近准备更新了
  
现在可以了吗？支持tiktok国际版的下载，和批量下载
