### ISSUE TITLE
请求再添加一个搜索下载的功能[Feature]

### ISSUE THREAD

**Issue by msadg** [Johnserf-Seed/TikTokDownload#183]
**描述您想要的功能**
通过搜索内容，下载搜索页中指定数量的视频，按搜索名分类视频

**Comment by Johnserf-Seed** [comment]
嘿，这个问题和我们在 [#421](https://github.com/users/Johnserf-Seed/projects/1/views/1?pane=issue&itemId=35037885) 的那个问题一样。为了让所有的讨论都在一个地方，我要把这个问题关闭了。去那边看看吧！
