### ISSUE TITLE
[Feature]下载抖音视频的封面

### ISSUE THREAD

**Issue by lxyer** [Johnserf-Seed/TikTokDownload#187]
**描述您想要的功能**
可以下载抖音视频的封面吗

**Comment by lxyer** [comment]
我看你之前没有实现完，我刚才自己完成了

**Comment by lxyer** [comment]
from urllib.request import urlretrieve
urlretrieve(dynamic_cover[i], '/Users//Downloads/douyin/'+author_list[i]+'.png')

**Comment by JDZW2018** [comment]
老铁，这个是加到哪里！~

**Comment by lxyer** [comment]
> 老铁，这个是加到哪里！~

TikTokMulti.py这个文件

**Comment by Johnserf-Seed** [comment]
> 我看你之前没有实现完，我刚才自己完成了

这个是自行取消注释就可以下载的
