### ISSUE TITLE
[Feature]期望添加关键字批量下载功能

### ISSUE THREAD

**Issue by Linux2010** [Johnserf-Seed/TikTokDownload#189]
**描述您想要的功能**
以关键字 进行搜索，然后批量下载前N条视频，若已下载则跳过。
示例链接：
https://www.douyin.com/search/%E5%A4%A7%E9%95%96%E5%AE%A22?publish_time=0&sort_type=0&source=switch_tab&type=general

**该功能优势**
以关键字下载，可以跟踪最新最热的某一类视频，更具吸引力

**附文**
谢谢！~
PS: 希望作者开通打赏功能，我用行动支持一下作者！！

**Comment by Johnserf-Seed** [comment]
嘿，这个问题和我们在 [#421](https://github.com/users/Johnserf-Seed/projects/1/views/1?pane=issue&itemId=35037885) 的那个问题一样。为了让所有的讨论都在一个地方，我要把这个问题关闭了。去那边看看吧！
