### ISSUE TITLE
无法下载无法保存抖音视频

### ISSUE THREAD

**Issue by tjj2577097637** [Johnserf-Seed/TikTokDownload#19]
大佬，其实很多视频，在抖音上无法保存，所以导致爬虫无法爬取。
但是我知道一个网站，他可以保存下载抖音视频。只需要链接即可。
无论是否可以在抖音上保存。都可以下载。
https://vtool.pro
我想大佬你这个爬虫代码，可不可有这样的功能。
https://v.douyin.com/epjBcGV/ 
这个抖音链接放在爬虫代码里，会直接报错的，但是放在我发的那个网站，他就可以直接下载了。
能不能优化一下代码。

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/125104697-41869f00-e110-11eb-9982-67a2c2377de8.png)
仔细看说明啦，批量下载给的是用户主页链接，单个视频直接复制到exe中

**Comment by tjj2577097637** [comment]
没有用啊，大佬还是下载不了，无论跑哪个程序，代码都会报错，你可以测试一下

**Comment by Johnserf-Seed** [comment]
> 没有用啊，大佬还是下载不了，无论跑哪个程序，代码都会报错，你可以测试一下

排查了一下，抖音将视频接口的参数替换了，所以修改了一下正则
![image](https://user-images.githubusercontent.com/40727745/125152806-d5dd1a00-e181-11eb-96b4-af7894e091c2.png)

![image](https://user-images.githubusercontent.com/40727745/125152792-c8c02b00-e181-11eb-9774-30368f0b1140.png)
![image](https://user-images.githubusercontent.com/40727745/125153024-957e9b80-e183-11eb-9d1d-9b012cb65593.png)

**Comment by Johnserf-Seed** [comment]
> 没有用啊，大佬还是下载不了，无论跑哪个程序，代码都会报错，你可以测试一下

新建环境变量可以直接命令行
![image](https://user-images.githubusercontent.com/40727745/125153041-bcd56880-e183-11eb-92e0-cb46b7ed317d.png)

**Comment by Johnserf-Seed** [comment]
网页版近期会发布，可以期待一下😁
