### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lxyer** [Johnserf-Seed/TikTokDownload#195]
[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  提示  ]:读取本地配置完成!
[  提示  ]:为您下载多个视频!
[  提示  ]:用户的sec_id=MS4wLjABAAAA5YwYcwOAohhIjZW-nCvNc1m_0TrOvcZ0qT6mPY9b_f4
[  提示  ]:正在进行第 1 次尝试
[  用户  ]: 不正经讲数码 
[  提示  ]:抓获数据成功!
[  提示  ]:等待替换文案非法字符!
[  提示  ]:等待替换作者非法字符!
[  提示  ]:这个视频未下载过，现在进行下载!
[ 第1个视频  ]:2022-08-11 16.15.55给soc换个全景天窗不过分吧？#手机 #手机壳 [文件 大小]:2.46 MB
[  警告  ]:下载视频出错!
[  警告  ]: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)> 
[  提示  ]:这个视频未下载过，现在进行下载!

**Comment by Johnserf-Seed** [comment]
和网络环境有关
