### ISSUE TITLE
[BUG]下载视频内容很多都是一样的，但是标题和日期显示都是正常的。

### ISSUE THREAD

**Issue by qdldqdf** [Johnserf-Seed/TikTokDownload#199]
![QQ截图20220824131841](https://user-images.githubusercontent.com/64909126/186335206-6d937e7d-857c-4642-819f-21bd9be4847d.jpg)
**描述出现的错误**
               在python3.8.3环境下，使用命令行操作方法，可以把一个账户的全部视频全部下载，标题没问题，但是视频内容很多都是重复的，请问这个改如何解决，非常感谢。
             同时，按照教程方法，使用配置文件操作方法，双击闪退，右键运行后，出现：[  提示  ]:生成失败,正在为您下载配置文件!  然后一直卡着不动了。同求解，非常感谢！

**Comment by singee77** [comment]
同上 Python 3.10.4

**Comment by singee77** [comment]
@Johnserf-Seed 
52e663c 修复检查视频时跳过重新下载

TikTokMulti:444

`self.new_video_list = [] `
改为
`new_video_list = [] `

**Comment by qdldqdf** [comment]
> @Johnserf-Seed [52e663c](https://github.com/Johnserf-Seed/TikTokDownload/commit/52e663c3fd44873c794344be316bd5308b243706) 修复检查视频时跳过重新下载
> 
> TikTokMulti:444
> 
> `self.new_video_list = [] ` 改为 `new_video_list = [] `

非常感谢，现在正常了。
