### ISSUE TITLE
用户主页的ID怎么来的？

### ISSUE THREAD

**Issue by xxxwei** [Johnserf-Seed/TikTokDownload#20]
你好，我们看到的id和配置里面的id不一样，请教一下是哪里获取的哪个数据？

**Comment by Johnserf-Seed** [comment]
一个是视频内的分享链接，一个是用户主页内的分享链接

**Comment by Johnserf-Seed** [comment]
用户主页内右上角分享主页
![image](https://user-images.githubusercontent.com/40727745/126056206-a6c41e04-6922-4111-80ab-281548e6ae01.png)
视频信息中复制链接
![image](https://user-images.githubusercontent.com/40727745/126056211-5106be09-4b89-4753-b17a-60a2638cc47f.png)

**Comment by Jieoz** [comment]
有单独用电脑获取的办法吗，不想用手机app
