### ISSUE TITLE
[BUG] No section: 'save' 可以复制此报错内容发issues

### ISSUE THREAD

**Issue by yjxfox** [Johnserf-Seed/TikTokDownload#201]
**描述出现的错误**
[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  警告  ]: No section: 'save' 可以复制此报错内容发issues
[  提示  ]:未输入命令或意外出错，自动退出!

**bug复现**
复现这次行为的步骤：
在终端运行“python3 TikTokMulti.py”

**截图**
<img width="872" alt="image" src="https://user-images.githubusercontent.com/18301809/186550293-4ffa91b2-4839-4310-96df-3a695e822c6e.png">

**桌面（请填写以下信息）：**
-操作系统：Mac
-vpn代理[例如开启、关闭]：开启
-版本：最新版本

**Comment by Johnserf-Seed** [comment]
拉一下新代码，已经修复了

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/commit/45ad4370f0d21edd6dcfeb8f99b83ca56ae4aafa
