### ISSUE TITLE
[BUG]我想知道这个uid怎么拿的到

### ISSUE THREAD

**Issue by MengQH123** [Johnserf-Seed/TikTokDownload#205]
大佬可以告诉我怎么过去作者的uid吗

**Comment by Whichbfj28** [comment]
> 大佬可以告诉我怎么过去作者的uid吗

PC端可以获取。地址栏可以看到

**Comment by Johnserf-Seed** [comment]
app点分享链接，网页直接点开主页复制地址栏

**Comment by MengQH123** [comment]
> 

![image](https://user-images.githubusercontent.com/37174029/188158448-b48bb7e7-93cf-4c6c-aab2-60fe866be99b.png)
我还是不太懂，这个PC的地址栏哪里可以看到uid，大佬可以帮忙提示下吗

**Comment by Johnserf-Seed** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/37174029/188158448-b48bb7e7-93cf-4c6c-aab2-60fe866be99b.png)
> 我还是不太懂，这个PC的地址栏哪里可以看到uid，大佬可以帮忙提示下吗

这个就是

**Comment by Johnserf-Seed** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/37174029/188158448-b48bb7e7-93cf-4c6c-aab2-60fe866be99b.png)
> 我还是不太懂，这个PC的地址栏哪里可以看到uid，大佬可以帮忙提示下吗

配置文件支持这种链接

**Comment by MengQH123** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/37174029/188158448-b48bb7e7-93cf-4c6c-aab2-60fe866be99b.png)
> > 我还是不太懂，这个PC的地址栏哪里可以看到uid，大佬可以帮忙提示下吗
> 
> 配置文件支持这种链接

我这边可以下载了，非常感谢大佬的耐心解答
