### ISSUE TITLE
release里的1.3.0版本，主文件依旧是1.2.5

### ISSUE THREAD

**Issue by caiyouzai** [Johnserf-Seed/TikTokDownload#207]
release里的1.3.0版本，主文件依旧是1.2.5

**Comment by Johnserf-Seed** [comment]
1.3.0不再更新TikTokMulti，故为1.2.5
以TikTokTool版本为主
可执行文件暂时未打包上传

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/releases/tag/v1.3.0-beta
