### ISSUE TITLE
批量视频下载不了

### ISSUE THREAD

**Issue by tjj2577097637** [Johnserf-Seed/TikTokDownload#21]
每一次都是跳过  提示该音频目前不可用
![image](https://user-images.githubusercontent.com/63137907/125214808-a77b4e00-e2eb-11eb-8464-764d7b062704.png)
下载的抖音主页有200个视频，最多只能下载120个，会自动跳过。即使是可以在抖音里保存的，也不可能批量爬下来。
就是一直报错，提示该音频目前不可用

**Comment by tjj2577097637** [comment]
有的用户主页可以全部爬下来，有的只能爬一半，有的只能爬几十个

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/125239124-c6dd9f80-e31a-11eb-86e1-f5a9daa5cbd9.png)
可以将 238行代码取消注释后查看一下是什么报错信息

**Comment by Johnserf-Seed** [comment]
已经修复

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/releases/tag/1.2
