### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ttangxing950125** [Johnserf-Seed/TikTokDownload#212]
[  提示  ]：获取用户昵称失败! 请重新运行本程序！
list index out of range

**Comment by small-white-rabbit** [comment]
同样的问题

**Comment by Johnserf-Seed** [comment]
抖音的问题，多试几次

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/188814571-eab4ccae-0b3a-4497-ae71-b380ad7fd216.png)

**Comment by feiying13720** [comment]
[   💻   ]:Windows平台
[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  提示  ]:读取本地配置完成!
[  提示  ]:为您下载多个视频!
[  提示  ]:用户的sec_id=MS4wLjABAAAAcXCYN0YuCo0gRtLpb5hZBEvFehxyEkzXeo2oxrbr8W8
[  提示  ]：获取用户昵称失败! 请重新运行本程序！
[2022-09-11 19:23:20,422] - Log.py] - ERROR: [  提示  ]：获取用户昵称失败! 请重新运行本程序！
[2022-09-11 19:23:20,423] - Log.py] - ERROR: list index out of range
[  提示  ]：按任意键退出程序!

试了好多次还是不行

**Comment by feiying13720** [comment]
[   💻   ]:Windows平台
[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  提示  ]:读取本地配置完成!
[  提示  ]:为您下载多个视频!
[  提示  ]:用户的sec_id=MS4wLjABAAAAcXCYN0YuCo0gRtLpb5hZBEvFehxyEkzXeo2oxrbr8W8

**Comment by Johnserf-Seed** [comment]
已经修复，拉一下最新代码
