### ISSUE TITLE
[  错误  ]:[Errno 2] No such file or directory: 'Download\\pic\\尤物社\\2022-08-31 10.08.00中森明菜壁纸，中森明菜是你的 菜吗？#中森明菜 #神仙颜值 #中森明菜壁纸   \\2022-08-31 10.08.00中森明菜壁纸，中森明菜是你的菜吗？#中森明菜 #神仙颜值 #中森明菜壁纸   _4.jpeg' [  提示  ]:发生了点意外![BUG]

### ISSUE THREAD

**Issue by apple12358lp** [Johnserf-Seed/TikTokDownload#216]
[  错误  ]:[Errno 2] No such file or directory: 'Download\\pic\\尤物社\\2022-08-31 10.08.00中森明菜壁纸，中森明菜是你的 菜吗？#中森明菜 #神仙颜值 #中森明菜壁纸   \\2022-08-31 10.08.00中森明菜壁纸，中森明菜是你的菜吗？#中森明菜 #神仙颜值 #中森明菜壁纸   _4.jpeg'
[  提示  ]:发生了点意外!

实际路径为  ：2022-08-31 10.08.00中森明菜壁纸，中森明菜是你的菜吗？#中森明菜 #神仙颜值 #中森明菜壁纸

尾部空格问题

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/190385756-dad80c09-cf54-47ca-9888-895a29c0a4dc.png)
测试了，并无bug

**Comment by apple12358lp** [comment]
好的，谢谢，我再检查检查
