### ISSUE TITLE
AttributeError:no attribute 'video_download'

### ISSUE THREAD

**Issue by KiLien** [Johnserf-Seed/TikTokDownload#22]
根目录添加示例 conf.ini 使用示例报错。。
![image](https://user-images.githubusercontent.com/13886339/125377218-2d1bfe00-e3bf-11eb-88ec-1cc3775cea93.png)

**Comment by Johnserf-Seed** [comment]
应该去除模块判断条件

**Comment by KiLien** [comment]
示例可以改下。。
![image](https://user-images.githubusercontent.com/13886339/125377846-43768980-e3c0-11eb-82f2-2f1a28c6fdc0.png)

**Comment by Johnserf-Seed** [comment]
示例没有问题

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/releases/tag/1.2
