### ISSUE TITLE
在线等

### ISSUE THREAD

**Issue by king-box** [Johnserf-Seed/TikTokDownload#221]
运行报错，提示没有sec属性。
![image](https://user-images.githubusercontent.com/97398286/192313131-98b932b9-7dc4-44e8-8306-427caf7a478a.png)

![image](https://user-images.githubusercontent.com/97398286/192313269-34033cb8-4edc-48df-ab76-2f19907afc1f.png)

![image](https://user-images.githubusercontent.com/97398286/192313349-388d5c04-9d7e-40c1-a506-9cd237970b28.png)

**Comment by Johnserf-Seed** [comment]
你这个是合集链接，目前只支持作品页
