### ISSUE TITLE
Linux下文件路径拼接不正确,导致下载文件没有存放在目录中,文件名变成 "文件夹\文件名.mp4"

### ISSUE THREAD

**Issue by wangyifan349** [Johnserf-Seed/TikTokDownload#227]
linux下路径拼接不正确。
在windows下和Linux下都可以用  /   不必windows下用\  

在linux下即使修改了conf.ini和conf.conf前面路径拼接正确后面的仍然用了windows的拼接方式。
直接用拼接函数比较好。
我在windows下用了以下,感觉程序相当不错。由于我平时向用服务器来批量爬所以.........还是很需要Linux的版本的

**Comment by Johnserf-Seed** [comment]
感谢反馈，明天我重新测试一下
