### ISSUE TITLE
用TikTokTool 和 TikTokDownload 下载视频的清晰度不一样。

### ISSUE THREAD

**Issue by happyaguang** [Johnserf-Seed/TikTokDownload#229]
用 TikTokTool.exe 批量下载的所有视频都是1080p，
用 TikTokDownload.exe下载的单个视频是720p，能否也上1080p？

测试抖音主页：https://v.douyin.com/MdRBCPk/

**Comment by Johnserf-Seed** [comment]
会修复这个问题。单个视频下载推荐使用[tiktokweb](https://github.com/Johnserf-Seed/TikTokWeb)项目

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/commit/76ba9c306c09f3ce0e4f6c12bf8705028d1361df
