### ISSUE TITLE
[BUG]下载的很多都是一个空的文本文档

### ISSUE THREAD

**Issue by liulegex** [Johnserf-Seed/TikTokDownload#235]
**描述出现的错误**
对bug的清晰而简洁的描述。
下载的文件有很多是一个空的文本而不是视频
形如这样：file1.mp4 file2.mp4
**bug复现**
复现这次行为的步骤：
1.更改了什么什么
正常使用，只修改了配置文件的下载链接
2.点击了什么什么
正常使用，只修改了配置文件的下载链接
3.“……”

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]
linux mint xfce 64 bit
-vpn代理[例如开启、关闭]
关闭
-版本[如1.2.3]
1.3.0beta

**附文**
在此处添加有关此问题的文字。

**Comment by Johnserf-Seed** [comment]
可以提供一下用户主页吗

**Comment by liulegex** [comment]
> 可以提供一下用户主页吗
![TikD_文件目录](https://user-images.githubusercontent.com/43005428/196364100-97929e5a-dc97-4243-8e18-8ac1a2d6404f.png)

第一个文件就是那样的，这个不是偶然的，特定的视频才会出现那种情况。重新启动下载好几次，每次都是固定的视频是空文本

**Comment by Johnserf-Seed** [comment]
> > 可以提供一下用户主页吗
> > ![TikD_文件目录](https://user-images.githubusercontent.com/43005428/196364100-97929e5a-dc97-4243-8e18-8ac1a2d6404f.png)
> 
> 第一个文件就是那样的，这个不是偶然的，特定的视频才会出现那种情况。重新启动下载好几次，每次都是固定的视频是空文本

我本地测试了，没有这种情况出现。这个项目到现在第一次看见这个情况

![image](https://user-images.githubusercontent.com/40727745/196647522-ff20e1ab-8633-452a-8d79-4e3d4021709d.png)
用web项目也可以正常解析
![image](https://user-images.githubusercontent.com/40727745/196647657-39cfb5b1-dc4d-428e-a04a-df9c202d9f35.png)
