### ISSUE TITLE
大佬好，求解[获取用户昵称失败————主页若空作品则无法下载喜欢页]

### ISSUE THREAD

**Issue by 2936747557** [Johnserf-Seed/TikTokDownload#236]
**获取用户昵称失败**
下载自己喜欢的作品显示获取用户昵称失败，隐私已全部开放，喜欢列表也已经开启，不知道问题出在了哪里，应该是账号的问题，因为下载他人主页作品完全正常，但是我实在是不知道自己的账号哪里的问题，隐私设置里面已经全部开放了（除了直播我没有）

**bug复现**
复现这次行为的步骤：
1.更改了ini的链接地址（自己的主页链接），mode填的是like，music填的是no
2.点击了tiktoktool文件运行
3.显示获取用户昵称失败

**截图**
![image](https://user-images.githubusercontent.com/102228434/196414901-d2c5145c-0fcc-4605-b011-a324fa399a7f.png)

**桌面（请填写以下信息）：**
-操作系统：[windows10 64bit]
-vpn代理[关闭]
-版本[如1.3.0]

**附文**
在此处添加有关此问题的文字。

**Comment by Johnserf-Seed** [comment]
我试着搜了一下你的sec_id 显示用户不存在

**Comment by 2936747557** [comment]
大佬，大佬什么是sec_id（网上差不到是什么），如果是说我的账号ID的话，我的账号是正常存在的，你看https://v.douyin.com/MUrcBs7/

**Comment by Johnserf-Seed** [comment]
> 大佬，大佬什么是sec_id（网上差不到是什么），如果是说我的账号ID的话，我的账号是正常存在的，你看https://v.douyin.com/MUrcBs7/

你可以主页随便发布一个视频，因为没有作品 接口返回的时候没有你的用户昵称

**Comment by Johnserf-Seed** [comment]
> 大佬，大佬什么是sec_id（网上差不到是什么），如果是说我的账号ID的话，我的账号是正常存在的，你看https://v.douyin.com/MUrcBs7/

因为网页js分离，最初获取的网页信息没有经过js渲染，无法获取like模式下的用户名，故均用post模式获取用户名。而没有发布过作品则无法从post获取，故报错

**Comment by 2936747557** [comment]
＼(☆o☆)／多谢大佬，问题成功解决了，大佬给力！

**Comment by LTalong** [comment]
为什么我一按回车，就下载Milo大人的视频，就是你系统配置的那个人的视频

**Comment by LTalong** [comment]
解决了1.3.0下载需要配置conf.conf  这里面的下载链接，而不是conf.ini里面的连接
