### ISSUE TITLE
[bug和需要帮助]解决脚本闪退后遭遇脚本报错，无奈下载exe版本再遇新难题！

### ISSUE THREAD

**Issue by ye8dongdaima** [Johnserf-Seed/TikTokDownload#238]
**描述出现的错误**
下载源代码后，按照要求修改conf.ini链接后打开TikTokTool.py出现cmd窗口后直接闪退，还原conf.ini后一样闪退。遂怀疑环境问题，卸载重装python重装并勾选添加path后依旧闪退，检查系统环境也没问题，电脑就只有一个python，电脑的环境变量path路径也是正常的python安装路径和python下的Scripts文件夹。
![无标题](https://user-images.githubusercontent.com/116237640/196950890-a9c507e2-099d-4a8c-93b6-9336d0c3bbf0.png)
然后用idle打开TikTokTool.py运行，发现错误是
`ModuleNotFoundError: No module named 'requests'`
引起的。提示是找不到模块requests，python安装目录里的Lib\site-packages\pip文件夹里面也有这个，感觉这个应该不属于第三方库，是python自带的吧。我看说明文档也没提到这个，然后我查阅资料后试着
`pip install requests `
能打开了，想请问下这个是本来就需要的步骤，因为太小白所以教程就没提还是属于不正常的范畴。

然后我打开后，把conf.ini里面的链接替换成自己想要下载的主页链接，跑起来一段时间后没下载完成就又闪退了，重试也不行。还是在idle里面运行，报错代码是
`Traceback (most recent call last):`
  `File "D:\常用软件\TikTokDownload\TikTokTool.py", line 29, in <module>
    profile.getProfile(cmd.setting())`
 ` File "D:\常用软件\TikTokDownload\Util\Profile.py", line 103, in getProfile
    self.getData(self.api_post_url)`
 ` File "D:\常用软件\TikTokDownload\Util\Profile.py", line 142, in getData
    self.getVideoInfo(result)`
`  File "D:\常用软件\TikTokDownload\Util\Profile.py", line 245, in getVideoInfo
    self.getNextData()`
 ` File "D:\常用软件\TikTokDownload\Util\Profile.py", line 184, in getNextData
    self.getVideoInfo(result)`
 ` File "D:\常用软件\TikTokDownload\Util\Profile.py", line 245, in getVideoInfo
    self.getNextData()`
`  File "D:\常用软件\TikTokDownload\Util\Profile.py", line 184, in getNextData
    self.getVideoInfo(result)`
 ` File "D:\常用软件\TikTokDownload\Util\Profile.py", line 242, in getVideoInfo
    datas = Util.Images().get_all_images(self.image_list)`
 ` File "D:\常用软件\TikTokDownload\Util\Images.py", line 49, in get_all_images
    self.position = js['item_list'][0]['aweme_poi_info']['poi_name']`
`KeyError: 'aweme_poi_info'`
![无标题1](https://user-images.githubusercontent.com/116237640/196950903-82a1c5a3-8a57-439a-bd2b-4913d3ceac41.png)
怀疑路径问题，改成英文路径依然不行

花费了数小时各种研究无果，只好用打包好的TikTokTool.exe（之前就看到有这个了，主要想知道报错的原理）。替换好自己想要下载的链接，这次不报错了，视频也能正常下载，但是图文下载出来会有很多空文件夹，试验过多次，是碰到固定文件夹就会这样，不是随机空文件夹，字符显示是 **提示：发生了点意外**，后面发现用TikTokPic.exe能一个个单独下载，就花一下午把空文件夹给下载了。。
特意注册账号来报这个issue，希望能够告知原因。可以测试，她的个人主页链接是https://v.douyin.com/Mf9Endf/

![无标题2](https://user-images.githubusercontent.com/116237640/196950907-fd311d90-e27a-4476-8178-9e8cd5f2e5a9.png)
话说这个怎么变来变去的，今天到现在变了三次了。

**截图**
已添加

**桌面（请填写以下信息）：**
-操作系统：[windows10 64bit]
-python版本：3.10
-代理[关闭]（看见有的issue的bug是这个引起的，没开代理）
-版本[最新源代码]

**附文**
盼复，感谢！

**Comment by ye8dongdaima** [comment]
话说打开其他的py文件也是提示各种
`ModuleNotFoundError:No module named XXXX ` 
我后面全都单独pip的，什么retrying这种也基础的也要pip install

**Comment by ye8dongdaima** [comment]
> 欢迎提交bug 环境问题项目提供了requirements.txt 输入pip install -r requirements.txt解决闪退问题 图文空文件夹的原因是回车制表符没替换干净所致，稍后修改修改

ok。特别感谢大佬，辛苦你修改了，这个项目真的帮了大忙。因为她时不时就会删除视频，如果这个空文件夹解决了，就能电脑就能设置任务计划程序每过10分钟运行一次，再不用时不时的去蹲守了。

**Comment by ye8dongdaima** [comment]
大佬你好，刚才按照你给的
`pip install -r requirements.txt`
后执行批量下载的时候依然会报错。为了严谨，特地把python再次卸载，还单独手动删除了残留的Lib和Scripts文件夹。再次安装后执行
`pip install -r requirements.txt`
依旧如此，按理来说需要的东西都已经装上了，为什么还会这样呢。我就想着把批量下载最后的input注释掉，完成下载后自动关闭。就打开bulid.bat自己构建一个exe试试，但最后依旧提示缺少模块，如下图所示。还请大佬再次不吝赐教

这是执行了pip的结果，因为已经执行过一次，所以显示都已经装上了
![无标题3](https://user-images.githubusercontent.com/116237640/197198672-8db0730d-a1db-46a3-9cbc-d1f1c33ce7fe.png)
这是批量下载依旧报错的代码
![无标题4](https://user-images.githubusercontent.com/116237640/197198679-0cef0beb-fd24-4a3d-b21d-22f91f895457.png)
这是执行bulid.bat构建的结果
![无标题5](https://user-images.githubusercontent.com/116237640/197198687-2d46b4be-5e47-4c03-86b7-42bc6e3533fa.png)

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/197200127-51a26c2c-c8c0-49da-b44f-f9d0fc8d2a9d.png)
拉取最新代码即可，如果你本地没有git工具就重新下载一下这个项目

**Comment by ye8dongdaima** [comment]
下载最新代码后，提示
`ModuleNotFoundError: No module named 'lxml'`
经过
`pip install lxml`
后可以正常运行了，但速度有明显问题，一个2M视频下载10分钟也下不完，并未开代理什么的，每次读条只有百分之0.0几
![无标题6](https://user-images.githubusercontent.com/116237640/197204858-862d12f4-f3d4-48a5-b1db-b8b7db485b6a.png)

**Comment by Johnserf-Seed** [comment]
> 下载最新代码后，提示 `ModuleNotFoundError: No module named 'lxml'` 经过 `pip install lxml` 后可以正常运行了，但速度有明显问题，一个2M视频下载10分钟也下不完，并未开代理什么的，每次读条只有百分之0.0几 ![无标题6](https://user-images.githubusercontent.com/116237640/197204858-862d12f4-f3d4-48a5-b1db-b8b7db485b6a.png)

这是两个月前更新的模块，很好奇为什么会这样

**Comment by Johnserf-Seed** [comment]
用cmd去运行一下

**Comment by Johnserf-Seed** [comment]
> 下载最新代码后，提示 `ModuleNotFoundError: No module named 'lxml'` 经过 `pip install lxml` 后可以正常运行了，但速度有明显问题，一个2M视频下载10分钟也下不完，并未开代理什么的，每次读条只有百分之0.0几 ![无标题6](https://user-images.githubusercontent.com/116237640/197204858-862d12f4-f3d4-48a5-b1db-b8b7db485b6a.png)

不要用自带的ide

**Comment by ye8dongdaima** [comment]
ok，cmd速度正常，但下载图片依旧存在提示：发生意外，打开下载文件夹检查后发现是空文件夹

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/commit/2d78d1f74d624fb41aa67c55b4c035a39ddcb073
根据这个提交修改一下```Util/__init__.py```里```replaceT```函数的代码即可
![1666359302962](https://user-images.githubusercontent.com/40727745/197208608-9694d54d-1fa8-452f-8431-16bf24dae498.png)

**Comment by ye8dongdaima** [comment]
好的好的。一路折腾了这么久，总算解决了用cmd下载就会闪退或者报错的问题，真心感谢大佬如此耐心的回复和积极帮忙解决问题，程序员届的灯塔了属于是。这必须点个star啊。然后我刚才也悟过来为什么会发生这些情况了。闪退还是因为环境的问题，因为使用教程没提`pip install -r requirements.txt`这个，其实之前我自己安装模块的时候，也发现了这个文件，打开后就觉得这些是必须安装的模块，自己手动一个一个的pip了，那时候就已经不闪退了。后来下载时会报错`KeyError: 'aweme_poi_info'`是因为我下载的是Assets里面8月30号的Source code，应该从主页code里面download zip完整的，这个多了些内容，可能修复了`KeyError: 'aweme_poi_info'`这问题。现在已经能正常跑起来了，到目前可以关闭了，要是后面有人同样有这些问题的话，能看到这个isses的话，希望我的这个能对你有所帮助。
