### ISSUE TITLE
现在无法批量下载了

### ISSUE THREAD

**Issue by tjj2577097637** [Johnserf-Seed/TikTokDownload#24]
我已经在配置文件中，已经设置好链接，可是现在下载不了，都是单一视频下载了。现在无法批量下载了
![image](https://user-images.githubusercontent.com/63137907/126020142-7fc7f134-4a41-4a3b-8ef6-9d0445d3a1ac.png)
![image](https://user-images.githubusercontent.com/63137907/126020171-306e0aad-5181-4fd3-9ec9-cad19838c4b1.png)

**Comment by Johnserf-Seed** [comment]
经过排查发现，网页版访问主页链接增加了验证码
![image](https://user-images.githubusercontent.com/40727745/126020450-c502a9a6-2e2b-4cdf-b7b3-a024a1ef5698.png)
但是接口还是正常的
![image](https://user-images.githubusercontent.com/40727745/126020492-a2a2fe54-5d0d-418a-8f3c-c4148d3bf2a0.png)
我修复一下，稍后重新push

**Comment by Johnserf-Seed** [comment]
已经修复

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/releases/tag/1.2
