### ISSUE TITLE
大佬救命啊[tiktoktool闪退]

### ISSUE THREAD

**Issue by 2936747557** [Johnserf-Seed/TikTokDownload#241]
**tiktoktool闪退**
下载抖音喜欢列表，数量大概一万多，但每次都是下载到三千左右直接闪退（不会弹出报错信息，而是直接闪退关闭），喜欢列表无法全部下载。

**bug复现**
复现这次行为的步骤：
1.更改了ini文件的链接地址（自己的主页链接）
2.点击了tiktoktool
3.“下载近3000个视频后直接闪退”

**截图**

**桌面（请填写以下信息）：**
-操作系统：[windows10 64bit]
-vpn代理[关闭]
-版本[如1.3.0]

**附文**
在此处添加有关此问题的文字。

**Comment by Johnserf-Seed** [comment]
日志最后贴一下

**Comment by 2936747557** [comment]
大佬，什么是日志最后贴一下(O_O)?
是要在ini文件中添加什么东西还是什么别的

**Comment by Johnserf-Seed** [comment]
logs文件夹里最后一个文件的奔溃地方

**Comment by 2936747557** [comment]
大佬找到了，打开后显示最后替换非法字符中中断的，大佬你的意思是这个可以用来解决问题是吗，但要怎么使用这个？

**Comment by Johnserf-Seed** [comment]
可以关注一下内存使用情况，我暂时也不清楚是不是性能问题导致闪退

**Comment by Johnserf-Seed** [comment]
> 大佬找到了，打开后显示最后替换非法字符中中断的，大佬你的意思是这个可以用来解决问题是吗，但要怎么使用这个？

你可以看一下是在第几页之后奔溃的

**Comment by 2936747557** [comment]
在第1658812247000页崩溃的，
![Uploading IMG_20221021_203322.jpg…]()

**Comment by 2936747557** [comment]
在第1658812247000页崩溃的，
![Uploading IMG_20221021_203322.jpg…]()

**Comment by 2936747557** [comment]
[Uploading 2022-10-21_171448.log…]()

**Comment by Johnserf-Seed** [comment]
你的文件和图片都没传完

**Comment by 2936747557** [comment]
[2022-10-21_171448.log](https://github.com/Johnserf-Seed/TikTokDownload/files/9839057/2022-10-21_171448.log)

**Comment by iquping** [comment]
@Johnserf-Seed 我这里同样的问题，下载数量超过一万中途就闪退
