### ISSUE TITLE
[BUG] ⭐我发现⭐ 不能在同个网络地址上边使用抖音/王者荣耀相关联的app边使用您的任何tiktok工具包，否则会出现闪退的问题~

### ISSUE THREAD

**Issue by quantoh7162** [Johnserf-Seed/TikTokDownload#253]
我发现了闪退的问题几率很大在于，不能在同一wifi ip address 内使用任何与腾讯/抖音/王者荣耀等的app，否则会一直闪退；假设我在家里的wifi 使用您的工具，家人之间有在同一的wifi ip 上使用抖音/王者荣耀等，几乎都会出现闪退的问题~

**Comment by Johnserf-Seed** [comment]
闪退的大部分原因是网络问题，这个和使用频率有关。最好的办法是路由器ip过期时间短一点

**Comment by quantoh7162** [comment]
感谢大佬解答！
