### ISSUE TITLE
[BUG] 部分视频下载后大小为0或者几字节

### ISSUE THREAD

**Issue by mr-lz** [Johnserf-Seed/TikTokDownload#254]
**描述出现的错误**
部分视频链接使用TikTokDownload下载后大小为0KB。
例如：
https://www.douyin.com/video/6562330645249395981
https://www.douyin.com/video/6568686843892600072
https://www.douyin.com/video/6563515392998771975

**bug复现**
TikTokDownload -u https://www.douyin.com/video/6563515392998771975

**桌面（请填写以下信息）：**
- 操作系统
win10 64、ubuntu 16.04
- vpn代理
关闭
- 版本
1.3.0

**Comment by Johnserf-Seed** [comment]
抖音接口问题
![image](https://user-images.githubusercontent.com/40727745/204128891-1617db58-ecfa-48d2-a0fd-0f9e427dbb2b.png)
