### ISSUE TITLE
TiktokDownload.exe下载图片时未替换特殊字符导致下载失败

### ISSUE THREAD

**Issue by d930fc** [Johnserf-Seed/TikTokDownload#257]
[  错误  ]:[Errno 2] No such file or directory: 'Download\\pic\\职场江湖\\2022-09-20 18.57.23如何礼貌的拒绝领导的敬酒请求。#职场 #人际交往 #酒文化 #酒局 #职场那些事 \\2022-09-20 18.57.23如何礼貌的拒绝领导的敬酒请求。#职场 #人际交往 #酒文化 #酒局 #职场那些事 _2.jpeg'
[  提示  ]:发生了点意外!

[  错误  ]:[Errno 2] No such file or directory: 'Download\\pic\\职场江湖\\2022-09-20 18.57.23如何礼貌的拒绝领导的敬酒请求。#职场 #人际交往 #酒文化 #酒局 #职场那些事 \\2022-09-20 18.57.23如何礼貌的拒绝领导的敬酒请求。#职场 #人际交往 #酒文化 #酒局 #职场那些事 _3.jpeg'
[  提示  ]:发生了点意外!

[  错误  ]:[Errno 2] No such file or directory: 'Download\\pic\\职场江湖\\2022-09-20 18.57.23如何礼貌的拒绝领导的敬酒请求。#职场 #人际交往 #酒文化 #酒局 #职场那些事 \\2022-09-20 18.57.23如何礼貌的拒绝领导的敬酒请求。#职场 #人际交往 #酒文化 #酒局 #职场那些事 _4.jpeg'
[  提示  ]:发生了点意外!

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/204128378-d8f0add7-37de-49a6-a585-b9dd978fa63e.png)
我本地测试没有出现问题

**Comment by Johnserf-Seed** [comment]
字符没有问题
