### ISSUE TITLE
批量下载时会报错停止。

### ISSUE THREAD

**Issue by tjj2577097637** [Johnserf-Seed/TikTokDownload#26]
批量下载超过33个之后就报错。  可是我在配置文件中设置count=999 。
你可以测试一下三个链接。
在抖音，记录美好生活！ https://v.douyin.com/etnDuF9/,
在抖音，记录美好生活！ https://v.douyin.com/etnfyGq/,
在抖音，记录美好生活！ https://v.douyin.com/etn8Pef/,
会报错：该音频目前不可用
![image](https://user-images.githubusercontent.com/63137907/126102161-823dec77-67ed-40c8-896f-adbc90cdaa76.png)
![image](https://user-images.githubusercontent.com/63137907/126102172-c3494ed7-f1ef-4e21-9d4a-2262c0424789.png)

**Comment by Johnserf-Seed** [comment]
目前修复完成，可以使用最新1.2.2版本
