### ISSUE TITLE
[Feature]您好，能否告知一下文件名的更名规则，因为下载新版本后发现命名规则改变，导致已存在的文件又重新被下载了一遍

### ISSUE THREAD

**Issue by flyshu** [Johnserf-Seed/TikTokDownload#262]
**描述您想要的功能**
告知文件名字符串的替换规则，以便自行将旧文件的文件名先替换一遍，防止重复下载

**描述你想要替换的功能或需要修改的解决方案**
无

**附文**
例如我发现1.30.33版本中把文件中的空格变成了下划线_，导致之前下载的所有文件命名规则和现在不同了，都会被重新下载一遍

**Comment by Johnserf-Seed** [comment]
在```Util/__init__.py:47```的```replaceT(obj)```
