### ISSUE TITLE
[BUG]今天开始闪退了，新旧版本都闪退

### ISSUE THREAD

**Issue by zhiben5201** [Johnserf-Seed/TikTokDownload#263]
**描述出现的错误**
今天Tiktoktool主程序开始频繁闪退，有的时候一打开就闪退，有的时候解析完用户名就闪退，有的时候则是下载几条之后闪退。

**bug复现**
复现这次行为的步骤：
1.ini文件粘贴用户主页链接
2.打开主程序
3.随机高频闪退无提示信息

同时会出现这样的错误信息：
![1670337942908](https://user-images.githubusercontent.com/103325310/205943335-7d81b9b2-3c0c-4584-952b-23a11cff3738.png)

**桌面（请填写以下信息）：**
-操作系统：windows10 64bit
-vpn代理开启关闭都试过，都会闪退。
-版本1.3.0.33

**附文**
在此处添加有关此问题的文字。
[2022-12-06_231936.log](https://github.com/Johnserf-Seed/TikTokDownload/files/10167744/2022-12-06_231936.log)
[2022-12-06_231931.log](https://github.com/Johnserf-Seed/TikTokDownload/files/10167745/2022-12-06_231931.log)

**Comment by Johnserf-Seed** [comment]
本地测试没有出现闪退问题，可能是你的网络问题没有获取到数据 清理一下dns缓存再试试，报的是json的错误

**Comment by zhiben5201** [comment]
> 本地测试没有出现闪退问题，可能是你的网络问题没有获取到数据 清理一下dns缓存再试试，报的是json的错误

好的，昨晚各种尝试，尝试到倒数第二种方法，重启路由器后就好了

**Comment by m1zukii** [comment]
我也是报这个错 dns也刷新过了 还是不行 怎么办

**Comment by Johnserf-Seed** [comment]
已经成功解决加密参数，等待下个版本更新
