### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zhangsan-feng** [Johnserf-Seed/TikTokDownload#266]
我抄了一部分你的代码 主要来爬取我喜欢点赞的一些抖音视频但是 
接口有问题  图集没有下载链接  我抓了返回的接口数据 就没有图集的视频数据
![image](https://user-images.githubusercontent.com/54844110/206607493-64160458-a0b8-4384-b949-efc4365f3780.png)
前面有2个图片视频的  但是直接返回了第三个视频的接口数据
![image](https://user-images.githubusercontent.com/54844110/206607680-827f620f-0764-472a-84dd-24a07450b10d.png)

**Comment by zhangsan-feng** [comment]
![image](https://user-images.githubusercontent.com/54844110/206609408-159b3fa2-9d00-4f2d-b6be-22b1d8b5f8c2.png)

**Comment by Evil0ctal** [comment]
你好，请问你可以把提交的链接发到这个issue里吗？

**Comment by zhangsan-feng** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/issues/266
我有点没懂你的意思




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Johnserf-Seed/TikTokDownload"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月9日(星期五) 中午11:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Johnserf-Seed/TikTokDownload] [BUG] (Issue #266)





 
你好，请问你可以把提交的链接发到这个issue里吗？

**Comment by Evil0ctal** [comment]
> https://github.com/Johnserf-Seed/TikTokDownload/issues/266
> 
> 我有点没懂你的意思
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 
> 发件人:                                                                                                                        "Johnserf-Seed/TikTokDownload"                                                                                    ***@***.***&gt;;
> 
> 发送时间:&nbsp;2022年12月9日(星期五) 中午11:53
> 
> ***@***.***&gt;;
> 
> ***@***.******@***.***&gt;;
> 
> 主题:&nbsp;Re: [Johnserf-Seed/TikTokDownload] [BUG] (Issue #266)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  
> 
> 你好，请问你可以把提交的链接发到这个issue里吗？
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

抱歉，我回错issue了😂
