### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by liyan998** [Johnserf-Seed/TikTokDownload#268]
[  提示  ]:读取命令完成!
[  提示  ]:为您下载多个视频!
[  提示  ]:用户的sec_id=MS4wLjABAAAAVViqx6FAAojVMzyBYVFeb3XG0jLhgSvJZZE_jBPGZEw
[  警告  ]: Expecting value: line 1 column 1 (char 0) 可以复制此报错内容发issues
[  提示  ]:未输入命令或意外出错，自动退出!

**Comment by Evil0ctal** [comment]
抖音的API限速了，请求过快会返回空，手动限制一下请求速率。

**Comment by Johnserf-Seed** [comment]
TikTokMulti不再维护，用TikTokTool
