### ISSUE TITLE
[BUG]大佬tiktoktool.py突然开始闪退

### ISSUE THREAD

**Issue by 2936747557** [Johnserf-Seed/TikTokDownload#269]
**描述出现的错误**
双击tiktoktool.py，无法正常运行直接闪退

**bug复现**
复现这次行为的步骤：
1.更改了conf.ini的抖音主页链接
2.双击了tiktoktool.py
3.运行窗口出现然后闪退

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。

**桌面（请填写以下信息）：**
-操作系统：[windows10 64bit]
-vpn代理[关闭]
-版本[如1.3.0]

**附文**
尝试清除dns缓存，更换网络，都没有效果
[2022-12-22_193250.log](https://github.com/Johnserf-Seed/TikTokDownload/files/10286529/2022-12-22_193250.log)
[2022-12-22_193234.log](https://github.com/Johnserf-Seed/TikTokDownload/files/10286530/2022-12-22_193234.log)

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/issues/263
重启路由器试试

**Comment by 2936747557** [comment]
大佬我重启了两遍，还是不行

**Comment by HaipingLIU** [comment]
我也是突然闪退

**Comment by Johnserf-Seed** [comment]
目前是官方接口寄了，等待恢复

**Comment by Evil0ctal** [comment]
我已经对此问题提交了一份PR

https://github.com/Johnserf-Seed/TikTokDownload/pull/270

**Comment by chenkongming** [comment]
@Evil0ctal 没用咯

**Comment by Evil0ctal** [comment]
> @Evil0ctal 没用咯

看这个：

https://github.com/Evil0ctal/Douyin_TikTok_Download_API/issues/127#issuecomment-1363492517

**Comment by chenkongming** [comment]
@Evil0ctal 综合你两个回答，改了下请求连接，可以了!

**Comment by chenkongming** [comment]
@Evil0ctal  新连接是可以请求到，但是还要返参跟旧接口相差甚远，还需要改动一下原来的逻辑

**Comment by Evil0ctal** [comment]
嗯嗯，而且我测试了一下，不支持图文视频的解析。

**Comment by Johnserf-Seed** [comment]
正在逆向X-Bogus

**Comment by Evil0ctal** [comment]
👍🏻👍🏻👍🏻

**Comment by Evil0ctal** [comment]
昨天我找到的那个接口今天又失效了，看来一定需要突破抖音的签名才能拿数据了。

@Johnserf-Seed

**Comment by GTXT88** [comment]
> 昨天我找到的那个接口今天又失效了，看来一定需要突破抖音的签名才能拿数据了。我也去研究一下抖音的签名，有进展我在这里update。
> 
> @Johnserf-Seed
那几个在线解析无水印视频的网站（比如https://dlpanda.com/）这两天都一直能用，他们难道一直是附带签名向抖音提交数据请求的吗？所以这次的改动没受影响？

**Comment by Evil0ctal** [comment]
是的，他们应该是抓的app端的包，app端的请求有四个参数，这四个参数会随着请求参数的改变而改变，需要逆向工程。

**Comment by Evil0ctal** [comment]
对于单一视频的解析，我已经提交了一个PR，目前测试下来是稳定的，我只修改了`Util/Download.py`这个文件的JSON索引，别的文件中的索引没有做修改。

**Comment by Evil0ctal** [comment]
> 已经成功解决加密参数，等待下个版本更新

牛逼！感谢大佬！

**Comment by 2936747557** [comment]
> 已经成功解决加密参数，等待下个版本更新

大佬牛逼！感谢大佬！

**Comment by Johnserf-Seed** [comment]
该早点逆向的。现在可以实现所有抖音的功能。我需要稍微重构一下代码，加亿点点的新功能。
晚些时间测试通过再发布

**Comment by Johnserf-Seed** [comment]
> 该早点逆向的。现在可以实现所有抖音的功能。我需要稍微重构一下代码，加亿点点的新功能。 晚些时间测试通过再发布

这是暂时整理出来的接口
![image](https://user-images.githubusercontent.com/40727745/210983382-45759681-2d69-4b04-9e1c-ea42588dd7a4.png)

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/211029346-41541e9c-36a8-485d-9eba-5a3d42989130.png)
