### ISSUE TITLE
[BUG]12.23日开始无法下载视频了，之前都可以，什么都没改

### ISSUE THREAD

**Issue by king-ma1993** [Johnserf-Seed/TikTokDownload#271]
**描述出现的错误**
12.23日开始无法下载视频了，之前都可以，什么都没改

**Comment by enkzan** [comment]
好像是抖音改了api还是啥接口，等博主更新

**Comment by LinZY1004** [comment]
是不是批量不行了，抖音加了一些校验

**Comment by king-ma1993** [comment]
> 是不是批量不行了，抖音加了一些校验

单个也不行

**Comment by Evil0ctal** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/pull/274

**Comment by Johnserf-Seed** [comment]
已经成功解决加密参数，等待下个版本更新
