### ISSUE TITLE
[BUG]json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by zzylmt** [Johnserf-Seed/TikTokDownload#272]
[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  提示  ]:读取本地配置完成!
[  提示  ]:为您下载多个视频!
[  提示  ]:用户的sec_id=MS4wLjABAAAA3nckmLU8MKXB4Aao7ZOOLaHIRCJG5AzKMDRh_6WMkU4
Traceback (most recent call last):
  File "c:\Users\DELL\Desktop\TikTokDownload\TikTokTool.py", line 29, in <module>
    profile.getProfile(cmd.setting())
  File "c:\Users\DELL\Desktop\TikTokDownload\Util\Profile.py", line 73, in getProfile
    post_name_json = Util.json.loads(Util.requests.get(url = post_url, headers=self.headers).content.decode())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

最新版本，没有修改任何代码，运行就出现这个问题

**Comment by WangYan-Good** [comment]
抖音的API改了
另外之前用户主页的是以"https://www.douyin.com/user/"开头，现在也变成了”'https://www.iesdouyin.com/share/user/'
之后发送访问链接 
'https://www.iesdouyin.com/web/api/v2/aweme/%s/?sec_uid=%s&count=%s&max_cursor=%s&aid=1128&_signature=PDHVOQAAXMfFyj02QEpGaDwx1S&dytk='
这个也失败了

**Comment by Evil0ctal** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/pull/274

**Comment by yfchen97** [comment]
我也遇到了这个问题，请问您解决了吗

**Comment by Johnserf-Seed** [comment]
已经成功解决加密参数，等待下个版本更新
