### ISSUE TITLE
[BUG]line 1 column 1 (char 0) 可以复制此报错内容发issues

### ISSUE THREAD

**Issue by strugglezhang** [Johnserf-Seed/TikTokDownload#275]
这个问题怎么办 大佬

**Comment by strugglezhang** [comment]
[[[iesdouyin.com/web/api/v2/aweme/iteminfo/?item_ids=7175083035304398120]()]()](https://www.iesdouyin.com/web/api/v2/aweme/iteminfo/?item_ids=7175083035304398120) 这个接口暂时无法获取到信息,有没大佬知道这个接口的最新地址是

**Comment by Evil0ctal** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/pull/274

**Comment by hold88888888** [comment]
咋办啊我也这个问题
Expecting value: line 1 column 1 (char 0) 可以复制此报错内容发issues

**Comment by fangyingwu** [comment]
Expecting value: line 1 column 1 (char 0) 可以复制此报错内容发issues
我在输入主页链接之后，批量下载视频，提示这个报错，有什么解决办法吗

**Comment by WeileiZeng** [comment]
我也是这样

**Comment by hold88888888** [comment]
> 我也是这样
泪目。。。

**Comment by hold88888888** [comment]
> 我也是这样

泪目，前段时间还能用的

**Comment by strugglezhang** [comment]
兄弟们，看[Evil0ctal](https://github.com/Evil0ctal)大神的回复，大神已经给解决了

**Comment by strugglezhang** [comment]
> https://github.com/Johnserf-Seed/TikTokDownload/pull/274

**Comment by strugglezhang** [comment]
> > 我也是这样
> 
> 泪目，前段时间还能用的

https://github.com/Johnserf-Seed/TikTokDownload/pull/274

**Comment by strugglezhang** [comment]
> 我也是这样

https://github.com/Johnserf-Seed/TikTokDownload/pull/274

**Comment by strugglezhang** [comment]
> Expecting value: line 1 column 1 (char 0) 可以复制此报错内容发issues 我在输入主页链接之后，批量下载视频，提示这个报错，有什么解决办法吗

https://github.com/Johnserf-Seed/TikTokDownload/pull/274

**Comment by Johnserf-Seed** [comment]
已经成功解决加密参数，等待下个版本更新

**Comment by strugglezhang** [comment]
> 

感谢大佬，感谢大佬。🙏感谢

**Comment by strugglezhang** [comment]
> 已经成功解决加密参数，等待下个版本更新

感谢大佬🙏🙏
