### ISSUE TITLE
TikTokTool.py批量下载失败，Utils/Profile.py报错

### ISSUE THREAD

**Issue by aephi** [Johnserf-Seed/TikTokDownload#276]
用的项目默认的抖音主播，电脑浏览器可以正常访问用户主页，post_url本身也没问题，已经填入了 self.sec。
但是Utils/Profile.py第73行 ：Util.requests.get(url = post_url, headers=self.headers).content.decode()，出来的content是空的，导致后面json解析出错

**Comment by flyshu** [comment]
api被废了，等大佬更新吧

**Comment by Johnserf-Seed** [comment]
已经成功解决加密参数，等待下个版本更新

**Comment by jcx70100** [comment]
期待大佬更新 @Johnserf-Seed
