### ISSUE TITLE
uid = https://v.douyin.com/enTq3rp/, 'status_msg': '参数不合法' KeyError: 'aweme_list'

### ISSUE THREAD

**Issue by RobinShare** [Johnserf-Seed/TikTokDownload#28]
conf.ini

[url]
#用户主页
uid = https://v.douyin.com/enTq3rp/
[music]
#音频下载
musicarg = no

[count]
#单页下载个数 Max = 35 （无需改动）
count = 35

[save]
#保存位置 你喜欢的名字
url = /Users/Downloads/Tiktok/

[mode]
#下载模式选择 like为点赞 post为发布
mode = post

python3 exmple.py
##############################################################################################################

                                                TikTokDownload V1.2.2
    使用说明：
            1、运行软件前先打开目录下 conf.ini 文件按照要求进行配置
            2、批量下载可直接修改配置文件，单一视频下载请直接打开粘贴视频链接即可
            3、如有您有任何bug或者意见反馈请在 https://github.com/Johnserf-Seed/TikTokDownload/issues 发起
            4、后续可能会更新GUI界面，操作更简单

    注意：  单个视频链接与用户主页链接要分清，软件闪退可以通过终端运行查看报错信息（一般是链接弄错的问题）

##############################################################################################################

批量下载直接回车，单一视频下载直接粘贴视频链接：
----读取配置完成----
----为您下载多个视频----
----用户的sec_id=MS4wLjABAAAApfaNtDyykDbhylYUr5nkGjEiitEw_-mzElieQwC-cWf----
----正在进行第 1 次尝试----
html: {'extra': {'logid': '202107220837360102111780820248F1C2', 'now': 1626914256000}, 'status_code': 5, 'status_msg': '参数不合法'}
Traceback (most recent call last):
  File "/Users/Downloads/TikTokDownload-main/exmple.py", line 4, in <module>
    MTK.TikTok()
  File "/Users/Downloads/TikTokDownload-main/TikTokMulti.py", line 95, in __init__
    self.judge_link()
  File "/Users/Downloads/TikTokDownload-main/TikTokMulti.py", line 132, in judge_link
    self.get_data(api_post_url,max_cursor)
  File "/Users/Downloads/TikTokDownload-main/TikTokMulti.py", line 150, in get_data
    if html['aweme_list'] != []:
KeyError: 'aweme_list'

**Comment by zzylmt** [comment]
碰到同样的问题！

**Comment by Johnserf-Seed** [comment]
> conf.ini
> 
> [url]
> #用户主页
> uid = https://v.douyin.com/enTq3rp/
> [music]
> #音频下载
> musicarg = no
> 
> [count]
> #单页下载个数 Max = 35 （无需改动）
> count = 35
> 
> [save]
> #保存位置 你喜欢的名字
> url = /Users/Downloads/Tiktok/
> 
> [mode]
> #下载模式选择 like为点赞 post为发布
> mode = post
> 
> python3 exmple.py
> ##############################################################################################################
> 
> ```
>                                             TikTokDownload V1.2.2
> 使用说明：
>         1、运行软件前先打开目录下 conf.ini 文件按照要求进行配置
>         2、批量下载可直接修改配置文件，单一视频下载请直接打开粘贴视频链接即可
>         3、如有您有任何bug或者意见反馈请在 https://github.com/Johnserf-Seed/TikTokDownload/issues 发起
>         4、后续可能会更新GUI界面，操作更简单
> 
> 注意：  单个视频链接与用户主页链接要分清，软件闪退可以通过终端运行查看报错信息（一般是链接弄错的问题）
> ```
> 
> ##############################################################################################################
> 
> 批量下载直接回车，单一视频下载直接粘贴视频链接：
> ----读取配置完成----
> ----为您下载多个视频----
> ----用户的sec_id=MS4wLjABAAAApfaNtDyykDbhylYUr5nkGjEiitEw_-mzElieQwC-cWf----
> ----正在进行第 1 次尝试----
> html: {'extra': {'logid': '202107220837360102111780820248F1C2', 'now': 1626914256000}, 'status_code': 5, 'status_msg': '参数不合法'}
> Traceback (most recent call last):
> File "/Users/Downloads/TikTokDownload-main/exmple.py", line 4, in
> MTK.TikTok()
> File "/Users/Downloads/TikTokDownload-main/TikTokMulti.py", line 95, in **init**
> self.judge_link()
> File "/Users/Downloads/TikTokDownload-main/TikTokMulti.py", line 132, in judge_link
> self.get_data(api_post_url,max_cursor)
> File "/Users/Downloads/TikTokDownload-main/TikTokMulti.py", line 150, in get_data
> if html['aweme_list'] != []:
> KeyError: 'aweme_list'

排查是正则获取的sec_uid 的问题，现在已经修复 可以重新pull一下

**Comment by Johnserf-Seed** [comment]
> 碰到同样的问题！

现在已经修复 可以重新pull一下

**Comment by boluohong** [comment]
最新反馈！！
今天看到新issue顺便进来看看
看到作者提到有修复
我重新试了一下，这次果然成功

撒花！！！！
