### ISSUE TITLE
批量下载报错，GUI下载闪退[BUG]

### ISSUE THREAD

**Issue by goodbyebug** [Johnserf-Seed/TikTokDownload#281]
1.批量下载报错
[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  提示  ]:读取本地配置完成!
[  提示  ]:批量下载直接回车：
[  提示  ]:为您下载多个视频!
[  提示  ]:用户的sec_id=MS4wLjABAAAAo0hDbJvN_-xEvV3BP6mQJ7azqbhmErfLoPcQES5Lkq4
[  警告  ]: Expecting value: line 1 column 1 (char 0) 可以复制此报错内容发issues
[  提示  ]:未输入命令或意外出错，自动退出!

2.使用命令行报错 python TikTokMulti.py -u https://v.douyin.com/xxxxxxx/
[  提示  ]:读取命令完成!
[  提示  ]:为您下载多个视频!
[  提示  ]:用户的sec_id=MS4wLjABAAAA6_c6E-9n5whn3jOn0MAxOGQW0pKjAHlM-kVv-lgt3Mc
[  警告  ]: Expecting value: line 1 column 1 (char 0) 可以复制此报错内容发issues
[  提示  ]:未输入命令或意外出错，自动退出!

**Comment by zhiben5201** [comment]
据说是抖音更改了规则，作者之前说要等新版本

**Comment by goodbyebug** [comment]
OKOK，不知道大佬年前能不能安排上新版本

**Comment by Linux2010** [comment]
求大佬更新~
