### ISSUE TITLE
[Feature]请问在哪里可以修改窗口打开时的默认大小

### ISSUE THREAD

**Issue by zhiben5201** [Johnserf-Seed/TikTokDownload#282]
请问在哪里可以修改窗口打开时的默认大小？目前版本在4K屏幕下默认打开时占据了超过四分之一的屏幕，比较影响电脑使用，有没有地方可以进行这方面的参数调整？谢谢

**Comment by Johnserf-Seed** [comment]
用这个命令设置控制台窗口
```os.system("mode con cols=120 lines=25")```

**Comment by zhiben5201** [comment]
> 用这个命令设置控制台窗口 `os.system("mode con cols=120 lines=25")`

谢谢，我瞬间就明白是什么东西了，顿时觉得自己有点傻
