### ISSUE TITLE
[BUG]下载视频返回404

### ISSUE THREAD

**Issue by liy010** [Johnserf-Seed/TikTokDownload#283]
**描述出现的错误**
下载视频返回404错误，只能下载4个视频，之后的视频全部返回404

**Comment by Johnserf-Seed** [comment]
是最新的版本吗

**Comment by liy010** [comment]
对
https://github.com/Johnserf-Seed/TikTokDownload/blob/6c345285db18fe0dd265384c0c25d61243c3a87d/Util/Download.py#L148
我为这一行加了个 else分支，打印出来 `status_code` 为404

**Comment by liy010** [comment]
状态码返回异常也应该`log`出来，不然屏幕输出都是`print('\r')`的空行，而不知道出了什么错

**Comment by Johnserf-Seed** [comment]
提供一下报错的用户主页，我测试一下

**Comment by liy010** [comment]
https://www.douyin.com/user/MS4wLjABAAAAEKnfa654JAJ_N5lgZDQluwsxmY0lhfmEYNQBBkwGG98

**Comment by liy010** [comment]
> 提供一下报错的用户主页，我测试一下

https://www.douyin.com/user/MS4wLjABAAAAEKnfa654JAJ_N5lgZDQluwsxmY0lhfmEYNQBBkwGG98

**Comment by liy010** [comment]
我知道原因了
`
                t_video = Util.requests.get(url=self.new_video_list[0],
                               headers=self.headers)  # 视频内容
`
这一行因为`status_code`不为200，导致下面的`self.new_video_list = []`不能执行，下载器一直在下载那个404的地址。
我把改成这样了
`
                t_video = Util.requests.get(url=self.new_video_list[-1],
                               headers=self.headers)  # 视频内容
`
不过把`self.new_video_list`定义成`dict`是出于什么考虑呢？直接定义成`str`类型好像也行。
最后就是上面发的那个主页的第5个视频返回404，可能这是个广告视频
