### ISSUE TITLE
[BUG] [  警告  ]: Expecting value: line 1 column 1 (char 0) 可以复制此报错内容发issues

### ISSUE THREAD

**Issue by Linux2010** [Johnserf-Seed/TikTokDownload#284]
- 作者大大，抖音批量下载出现如下问题.

- 命令
```python
python TikTokMulti.py -u https://v.douyin.com/jqwLHjF/ -d video_test/
```
- 报错
```shell
[  提示  ]:读取命令完成!
[  提示  ]:为您下载多个视频!
[  提示  ]:用户的sec_id=MS4wLjABAAAAo0hDbJvN_-xEvV3BP6mQJ7azqbhmErfLoPcQES5Lkq4
[  警告  ]: Expecting value: line 1 column 1 (char 0) 可以复制此报错内容发issues
[  提示  ]:未输入命令或意外出错，自动退出!
```

**Comment by Johnserf-Seed** [comment]
用1.3.0.43版本，multi已经弃用

**Comment by Linux2010** [comment]
我看是昨天提交的新版本， 这个版本如何使用批量下载， 实现之前的功能呢？ 
类似批量下载首页全部内容
- python TikTokMulti.py -u https://v.douyin.com/jqwLHjF/ -d video_test/

**Comment by Linux2010** [comment]
大佬，我已经看到了最新版本使用 TikTokTool.py 进行批量下载
- 有个问题，这个版本把 -d 参数注释掉了，
- 建议下：这个参数能否在下个版本更新加回来，挺有用的一个参数, 多一个选项.

**Comment by dzapologize** [comment]
> 用1.3.0.43版本，multi已弃用

1.3.0-beta依然有这个问题

**Comment by Johnserf-Seed** [comment]
> 

![image](https://user-images.githubusercontent.com/40727745/213400890-be8d6d60-1c58-494c-98e5-d4a45260fa51.png)
现在重心在这个工具的开发上了，该有的参数都会有
