### ISSUE TITLE
批量下载数量太少。

### ISSUE THREAD

**Issue by tjj2577097637** [Johnserf-Seed/TikTokDownload#29]
抖音视频 https://v.douyin.com/eW33GDr/一共有189个作品。

只能下载21个作品

**Comment by tjj2577097637** [comment]
https://v.douyin.com/eW33GDr/

**Comment by tjj2577097637** [comment]
> 抖音视频 [https://v.douyin.com/eW33GDr/]一共有189个作品。(https://v.douyin.com/eW33GDr/%E4%B8%80%E5%85%B1%E6%9C%89189%E4%B8%AA%E4%BD%9C%E5%93%81%E3%80%82)
> 
> 只能下载21个作品

**Comment by tjj2577097637** [comment]
> 抖音视频 [https://v.douyin.com/eW33GDr/一共有189个作品。](https://v.douyin.com/eW33GDr/%E4%B8%80%E5%85%B1%E6%9C%89189%E4%B8%AA%E4%BD%9C%E5%93%81%E3%80%82)
> 
> 只能下载21个作品

**Comment by Johnserf-Seed** [comment]
看了一下发现api抓到某一页的时候是空的https://www.iesdouyin.com/web/api/v2/aweme/post/?sec_uid=MS4wLjABAAAA2On0_t7aGAF20AEduMcxBbs19Y5xu9dFWX5tuIpJI-Y&count=35&max_cursor=1609249933000&aid=1128&_signature=PDHVOQAAXMfFyj02QEpGaDwx1S&dytk=    ，所以程序认为可以结束了，这个问题我解决一下
