### ISSUE TITLE
打开TikTokTool.exe 报错

### ISSUE THREAD

**Issue by liu-runsen** [Johnserf-Seed/TikTokDownload#290]
💻   ]:Windows平台
[   🗻   ]:获取最新版本号中!
[   🌋   ]:当前不是最新版本,需要升级吗? (y/n) :nn
[   🌋   ]:当前不是最新版本,需要升级吗? (y/n) :n
[   🚩   ]:取消升级,旧版可能会出现没有修复的bug
[  提示  ]:没有检测到配置文件，生成中!
[  提示  ]:生成成功!
[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  提示  ]:读取本地配置完成!
[  提示  ]:为您下载多个视频!
[  提示  ]:用户的sec_id=66952284120
[  提示  ]：获取用户昵称失败! 请检查是否发布过作品，发布后请重新运行本程序！
[2023-01-19 10:12:52,486] - Log.py] - ERROR: [  提示  ]：获取用户昵称失败! 请检查是否发布过作品，发布后请重新运行本程序！
[2023-01-19 10:12:52,487] - Log.py] - ERROR: 'NoneType' object is not subscriptable
[  提示  ]：按任意键退出程序!

                                                TikTokTool V1.3.0.33
        使用说明：
                1、本程序目前支持命令行调用和配置文件操作，GUI预览版本已经发布
                2、命令行操作方法：1）将本程序路径添加到环境变量
                                2）控制台输入 TikTokTool -u https://v.douyin.com/jqwLHjF/

                3、配置文件操作方法：1）运行软件前先打开目录下 conf.ini 文件配置用户主页和音乐下载模式
                                2）按照控制台输出信息操作

                4、如有您有任何bug或者意见反馈请在 https://github.com/Johnserf-Seed/TikTokDownload/issues 发起
                5、GUI预览版本现已发布，操作更简单 https://github.com/Johnserf-Seed/TikTokDownload/tags 下载

        注意：  目前已经支持app内分享短链和web端长链识别。

########################################################################################################################

[   💻   ]:Windows平台
[   🗻   ]:获取最新版本号中!
[   🌋   ]:当前不是最新版本,需要升级吗? (y/n) :y
[   🚩   ]:正在为你下载 13043 版本中，升级前请确保关闭所有打开的项目文件
[   🚧   ]:网络不太通畅，请重新运行

**Comment by Johnserf-Seed** [comment]
你链接错了

**Comment by liu-runsen** [comment]
就是打开  就直接 退出了,  源码可以下载视频吗?
