### ISSUE TITLE
直接运行 example.py 报错

### ISSUE THREAD

**Issue by liu-runsen** [Johnserf-Seed/TikTokDownload#291]
[   💻   ]:Windows平台
[   🗻   ]:获取最新版本号中!
[   🚩   ]:目前 13043 版本已是最新
[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  提示  ]:读取本地配置完成!
[  提示  ]:为您下载多个视频!
[  提示  ]:用户的sec_id=MS4wLjABAAAA3nckmLU8MKXB4Aao7ZOOLaHIRCJG5AzKMDRh_6WMkU4
[  提示  ]：获取用户昵称失败! 请检查是否发布过作品，发布后请重新运行本程序！
[2023-01-19 20:25:29,460] - Log.py] - ERROR: [  提示  ]：获取用户昵称失败! 请检查是否发布过作品，发布后请重新运行本程序！
[2023-01-19 20:25:29,460] - Log.py] - ERROR: list index out of range

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/213493885-2e881276-8f29-4605-b015-1093a289074d.png)
还是你本地的问题，这个作者我保存过的

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/213494160-f7c97a2e-c925-48b5-a21c-0aeca38edc9c.png)
![image](https://user-images.githubusercontent.com/40727745/213494211-b085b63f-71fe-4819-aff5-58eeef202162.png)
