### ISSUE TITLE
[BUG]经常出现[文件 大小]:0.00 MB

### ISSUE THREAD

**Issue by esouxcon** [Johnserf-Seed/TikTokDownload#293]
**描述出现的错误**
下载主页视频，常会出现下载视频文件大为0.00MB
(不是视频文件已存在，如果已存在会显示[文件已存在，为您跳过])
手动删除0.00MB的文件再重新下载 有机会下载成功
表示不是视频有问题

**截图**
![](https://upload.cc/i1/2023/01/22/ZvySWI.jpg)

**桌面（请填写以下信息）：**
-操作系统：[windows10 64bit]
-vpn代理[关闭]
-版本[1.3.0.45]

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/commit/572875f778a6fbf4a81aa2504cbf25c555c1f48e

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/commit/7f9ec0a9625533c49e3ec2b2a0c8b2d3dbc3cf37

**Comment by Johnserf-Seed** [comment]
运行TikTokUpdata下载45版本，并用build.bat打包

**Comment by esouxcon** [comment]
大佬 跟您报告一下
我是下载最新源码重新编译的 有包含这段新代码了

**Comment by Johnserf-Seed** [comment]
用户主页贴一下

**Comment by esouxcon** [comment]
蛮多个主页都有这种情形 不是只有单一主页出现

**Comment by Johnserf-Seed** [comment]
> 蛮多个主页都有这种情形 不是只有单一主页出现 https://www.douyin.com/user/MS4wLjABAAAAOJMEE4rQ4cT3dpgwonJ4XWaABrtb6SdwVmJqap4rI6sC5wd9OhyvETW1TvzEZOPw 这是截图里的主页

好的我去测试一下

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/213908792-e4f76779-2165-461f-9e14-108d0905adb5.png)

可以下载，你还是检查一下代码版本吧

**Comment by Johnserf-Seed** [comment]
> 蛮多个主页都有这种情形 不是只有单一主页出现 https://www.douyin.com/user/MS4wLjABAAAAOJMEE4rQ4cT3dpgwonJ4XWaABrtb6SdwVmJqap4rI6sC5wd9OhyvETW1TvzEZOPw 这是截图里的主页

那就不是最新版的代码

**Comment by esouxcon** [comment]
不是每次都会出现的
感谢大佬测试
