### ISSUE TITLE
[Feature]限制下载视频的起始日期

### ISSUE THREAD

**Issue by cloudkku** [Johnserf-Seed/TikTokDownload#295]
config.ini设置日期开始往后下载，之前的时间不下载

**Comment by GTXT88** [comment]
可以在util文件夹的Download.py里加下面的代码来临时解决这个问题， 加在76行

          # 如果视频时间早于date_limit，不下载
          before_date = 你自己设置要什么最早日期，比如 “2022-1-20”
          date_format = "%Y-%m-%d %H.%M.%S"
          date_limit = datetime.strptime(before_date, "%Y-%m-%d")
          creat_date = datetime.strptime(creat_time, date_format)
          if creat_date < date_limit:
              continue

**Comment by akafanfan** [comment]
> 可以在util文件夹的Download.py里加下面的代码来临时解决这个问题， 加在76行
> 
> ```
>       # 如果视频时间早于date_limit，不下载
>       before_date = 你自己设置要什么最早日期，比如 “2022-1-20”
>       date_format = "%Y-%m-%d %H.%M.%S"
>       date_limit = datetime.strptime(before_date, "%Y-%m-%d")
>       creat_date = datetime.strptime(creat_time, date_format)
>       if creat_date < date_limit:
>           continue
> ```

不行啊 没有生效

**Comment by GTXT88** [comment]
> > 可以在util文件夹的Download.py里加下面的代码来临时解决这个问题， 加在76行
> > ```
> >       # 如果视频时间早于date_limit，不下载
> >       before_date = 你自己设置要什么最早日期，比如 “2022-1-20”
> >       date_format = "%Y-%m-%d %H.%M.%S"
> >       date_limit = datetime.strptime(before_date, "%Y-%m-%d")
> >       creat_date = datetime.strptime(creat_time, date_format)
> >       if creat_date < date_limit:
> >           continue
> > ```
> 
> 不行啊 没有生效

我这个早失效了Download.py文件之后已经被修改过很多次了
