### ISSUE TITLE
[BUG]新版本替换了符号和空格为_没法兼容以前下载的文件名

### ISSUE THREAD

**Issue by 8RedBulls** [Johnserf-Seed/TikTokDownload#298]
新版本Tools替换了符号和空格为_没法兼容以前下载的内容,以前下载的内容重复下载，
怎么知道你的替换规则，我好去把以前的文件批量重命名后再去查重....
因为本人平时追音乐up主，但是好多翻唱因为版权问题经常会被下架。

不过新版本确实下载的文件比之前的清晰许多。

**Comment by 8RedBulls** [comment]
算了，我通过文件名里的时间，批量改了所有文件的时间(一个人同一时间应该没法发两个)，然后批量修改所有文件的创建时间和修改时间，再通过查重工具去匹配文件夹名称和文件时间去查重了。

**Comment by esouxcon** [comment]
文件命名替换规则在"Util\__init__.py"的76~86行
