### ISSUE TITLE
[BUG]win10系统启动TikTokTool.exe 闪退

### ISSUE THREAD

**Issue by wzm74110** [Johnserf-Seed/TikTokDownload#299]
**描述出现的错误**
win10系统 启动TikTokTool.exe 闪退，无法正常批量下载视频

**bug复现**

**截图**
启动TikTokTool.exe后的截图
![1](https://user-images.githubusercontent.com/39322408/216051175-0007cc9b-5155-4b7a-b0ed-b9e12334304f.png)

日志：
[2023-02-01 20:44:40,692] - Log.py] - INFO: Windows
[2023-02-01 20:44:41,086] - Log.py] - INFO: [  提示  ]:为您下载多个视频!
[2023-02-01 20:44:41,087] - Log.py] - INFO: [  提示  ]:用户的sec_id=MS4wLjABAAAArTpeSspLdvV1NLFdMgp70ZA1YWrg41hQW29zVbDsUjE0hlSHH3HhM_sQTd0Q40to

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]
-vpn代理[例如开启、关闭]
-版本[如1.2.3]

**附文**
在此处添加有关此问题的文字。

**Comment by UZIOVE** [comment]
现在无法现在titok的视频了吗？我挂了全局vpn都不行。

**Comment by wzm74110** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wzm74110** [comment]
> 现在无法现在titok的视频了吗？我挂了全局vpn都不行。
和vpn没关系，我之前没用vpn一直都是正常下载抖音视频的，现在就突然闪退了

**Comment by Mak0760** [comment]
同样存在这个问题

**Comment by esouxcon** [comment]
[](https://i.imgur.com/FcXnsnV.jpg)
可以正常下载
执行的画面跟你的不太一样
你的少了检测最新版本?

**Comment by UZIOVE** [comment]
是国际抖音不能正常下载，挂全局VPN都不行哦，国内抖音正常下载

**Comment by esouxcon** [comment]
这个工具本来就不支持国际版(TikTok)
我是回复#1

作者正在开发新工具，到时新工具应该能下载国际版

**Comment by wzm74110** [comment]
> 同样存在这个问题

额，不下载源码编译安装，直接下载作者打包好的exe文件就可以正常下载视频了

**Comment by wzm74110** [comment]
> ![](https://camo.githubusercontent.com/ed836cbe893820f03771eb687f273b9b51f31fe82800d6886c0edfaf248a5d7e/68747470733a2f2f692e696d6775722e636f6d2f4663586e736e562e6a7067) 可以正常下载 执行的画面跟你的不太一样 你的少了检测最新版本?
额，不下载源码编译安装，直接下载作者打包好的exe文件就可以正常下载视频了
