### ISSUE TITLE
可以增加一个模糊搜索的功能嘛

### ISSUE THREAD

**Issue by markses** [Johnserf-Seed/TikTokDownload#3]
可以增加一个模糊搜索的功能嘛

**Comment by Johnserf-Seed** [comment]
功能模块已经在测试啦

**Comment by YinHjie** [comment]
大佬，这个功能是否已经推出来了

**Comment by nevertoday** [comment]
这个功能，真的良心刚需~~~~

**Comment by Johnserf-Seed** [comment]
嘿，这个问题和我们在 [#421](https://github.com/users/Johnserf-Seed/projects/1/views/1?pane=issue&itemId=35037885)  的那个问题一样。为了让所有的讨论都在一个地方，我要把这个问题关闭了。去那边看看吧！
