### ISSUE TITLE
批量下载数量太少。

### ISSUE THREAD

**Issue by tjj2577097637** [Johnserf-Seed/TikTokDownload#30]
抖音视频 https://v.douyin.com/eW33GDr/
一共有189个作品。
只能下载21个作品

**Comment by Johnserf-Seed** [comment]
看了一下发现api抓到某一页的时候是空的https://www.iesdouyin.com/web/api/v2/aweme/post/?sec_uid=MS4wLjABAAAA2On0_t7aGAF20AEduMcxBbs19Y5xu9dFWX5tuIpJI-Y&count=35&max_cursor=1609249933000&aid=1128&_signature=PDHVOQAAXMfFyj02QEpGaDwx1S&dytk= ，所以程序认为可以结束了，这个问题我解决一下

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/126866033-f9e4c384-b2d3-4399-8715-1b6cabc7bac8.png)
该问题已经解决

**Comment by tjj2577097637** [comment]
需要改代码的哪个部分呢？？？

**Comment by tjj2577097637** [comment]
好的，我看见代码更新了

**Comment by Johnserf-Seed** [comment]
重新拉取就好了😀

**Comment by tjj2577097637** [comment]
现在还是有三个问题，
（1）我在配置文件中设置count比较大时，会一直跑。停不下来了。
（2）比如说视频有191个
https://v.douyin.com/eWKPonE/
我设置的count=200，
程序跑一段时间后会报错：
("Connection broken: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)", ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
缓存失败，请检查！
（3）即使视频下载很多了，最多可以下载到95%，但是不可能下满。

**Comment by Johnserf-Seed** [comment]
> 现在还是有三个问题，
> （1）我在配置文件中设置count比较大时，会一直跑。停不下来了。
> （2）比如说视频有191个
> https://v.douyin.com/eWKPonE/
> 我设置的count=200，
> 程序跑一段时间后会报错：
> ("Connection broken: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)", ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
> 缓存失败，请检查！
> （3）即使视频下载很多了，最多可以下载到95%，但是不可能下满。

1、配置文件中的count个数无需修改，其含义是单页返回数据 由于官方api限制经本人测试35为最佳值 因为是通过max_cursor为0确定下载完成的
2、是因为频繁的访问造成的，现在已经修复了
3、下不满的原因依旧是官方的api返回结果的原因，每页的结果都不是指定的个数  有时候单页会少于10个 甚至0个，当出现0个的时候 程序会再尝试读取下一页 如果依旧是0 则判断下载完成 所以可能会导致下载不完全的情况，属于很蛋疼的问题

**Comment by honjiaxuan** [comment]
这个问题还是存在，不过暂时还是没有特别好的解决方法的想法

**Comment by honjiaxuan** [comment]
不知道能不能在重复下载的时候，检查同样的文件夹里面是不是有同样名字的视频，有的话就不重复下载呢

**Comment by Johnserf-Seed** [comment]
> 不知道能不能在重复下载的时候，检查同样的文件夹里面是不是有同样名字的视频，有的话就不重复下载呢

下个版本就会更新这个问题
