### ISSUE TITLE
TikTokLive和TikTokTool同时失效

### ISSUE THREAD

**Issue by boluohong** [Johnserf-Seed/TikTokDownload#302]
首先感谢作者上一次更新，该版本稳定运行至今天下午

从今天下午起，TikTokLive和TikTokTool同时失效
应该是抖音有所更新

（1）TikTokLive失效
无论任何链接都失效
报错如下

[   💻   ]:Windows平台
[   🗻   ]:获取最新版本号中!
[   🚩   ]:目前 13045 版本已是最新
[   📺   ]:输入抖音直播间web端链接，例如 https://live.douyin.com/176819813905：h
ttps://live.douyin.com/37344841394
Traceback (most recent call last):
  File "D:\20230120\TikTokLive.py", line 25, in <module>
    status = json['data']['data'][0]['status']
KeyError: 'data'

（2）TikTokTool失效
无论任何链接都失效
报错如下

[   💻   ]:Windows平台
[   🗻   ]:获取最新版本号中!
[   🚩   ]:目前 13045 版本已是最新
[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  提示  ]:读取本地配置完成!
[  提示  ]:为您下载多个视频!
[  提示  ]:用户的sec_id=MS4wLjABAAAAuVL8HzdDhO9J1ams14spwViTDfyets-cNmXn7d6O_imd
RE31RMwSg6He4VocXtcL
Traceback (most recent call last):
  File "D:\20230120\TikTokTool.py", line 29, in <module>
    profile.getProfile(cmd.setting())
  File "D:\20230120\Util\Profile.py", line 82, in getProfile
    url=post_url, headers=self.headers).content.decode())
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\json\__init__.py"
, line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\json\decoder.py",
 line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\hp\AppData\Local\Programs\Python\Python37\lib\json\decoder.py",
 line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by boluohong** [comment]
> ![image](https://user-images.githubusercontent.com/40727745/216943385-d6cc9007-d57c-484d-a6d7-90602100272a.png) 我这访问没有问题


感谢回复
重新试了一下
TikTokTool能正常运行

TikTokLive则完全失效
不知能否抽空修复一下tiktokLive，万分感谢

[   💻   ]:Windows平台
[   🗻   ]:获取最新版本号中!
[   🚩   ]:目前 13045 版本已是最新
[   📺   ]:输入抖音直播间web端链接，例如 https://live.douyin.com/176819813905：h
ttps://live.douyin.com/342686279310
Traceback (most recent call last):
  File "D:\20230120\TikTokLive.py", line 25, in <module>
    status = json['data']['data'][0]['status']
KeyError: 'data'

**Comment by zzh151223** [comment]
把直播链接改一下
原来的:https://live.douyin.com/webcast/web/enter/
新的:https://live.douyin.com/webcast/room/web/enter/
多了个room

**Comment by Johnserf-Seed** [comment]
更新已经推送
