### ISSUE TITLE
新版本无法下载[BUG]

### ISSUE THREAD

**Issue by zzylmt** [Johnserf-Seed/TikTokDownload#303]
**描述出现的错误**
最新版本无法下载，没有修改任何文件，运行TikTokTool.py，重复报错[  提示  ]:获取用户数据失败，正在重新获取

**桌面（请填写以下信息）：**
-操作系统：[windows10 64bit]
-vpn代理[关闭]
-版本[最新]

**Comment by Johnserf-Seed** [comment]
晚点时间更新加密接口

**Comment by Johnserf-Seed** [comment]
重新运行获取1.3.0.50版本更新
