### ISSUE TITLE
好像更新了还是有问题,不知道什么情况,代理都关闭了,就是获取失败

### ISSUE THREAD

**Issue by GEM123668** [Johnserf-Seed/TikTokDownload#309]
**描述出现的错误**
对bug的清晰而简洁的描述。

**bug复现**
复现这次行为的步骤：
1.更改了什么什么
2.点击了什么什么
3.“……”

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]
-vpn代理[例如开启、关闭]
-版本[如1.2.3]

**附文**
在此处添加有关此问题的文字。

**Comment by GEM123668** [comment]
![image](https://user-images.githubusercontent.com/121158914/217737224-b35bb1ce-af9b-4180-b097-eac92feee763.png)

**Comment by ATCassiopeia** [comment]
确实 还是不好用

**Comment by Johnserf-Seed** [comment]
因为旧的接口又失效了，现在更新了xb接口，请重新运行获取更新

**Comment by GEM123668** [comment]
@Johnserf-Seed 感谢作者,很好用,已经在用了
