### ISSUE TITLE
[BUG]正在对 1587816262000 页进行第 1 次尝试!

### ISSUE THREAD

**Issue by 6986552** [Johnserf-Seed/TikTokDownload#310]
**描述出现的错误**
正在对 1587816262000 页进行第 1 次尝试!

**bug复现**
复现这次行为的步骤：
这次新版本的批量下载，会在全部下载完毕后，一直重复获取1587816262000页，然后跳过文件下载，一直重复。
备注：此前版本也会在全部下载完毕后，获取xxxx页然后没有动作并且没有日志输出。

**截图**
![image](https://user-images.githubusercontent.com/35484288/217770544-361c73f5-e6ba-4c6a-b70c-50ca76970a0c.png)

**Comment by Johnserf-Seed** [comment]
感谢反馈

**Comment by Johnserf-Seed** [comment]
除此版本外之前是正常的，重复获取确保全部的作品能被获取下载。这次的版本遗漏了翻页的参数
