### ISSUE TITLE
[BUG] 想更改代码实现关注功能

### ISSUE THREAD

**Issue by ShiinaRinne** [Johnserf-Seed/TikTokDownload#319]
## 可能是个与repo并没有关系的issue...恳请赐教
**描述出现的错误**
[https://www.douyin.com/aweme/v1/web/commit/follow/user/?](https://www.douyin.com/aweme/v1/web/commit/follow/user/?)
对此接口发送请求，返回值为200，但是没有任何返回信息(`response.text`)

**bug复现**
复现这次行为的步骤：
1. 使用`Util.XBogus`调用这段参数生成XBogus，来源于关注和取消关注的接口。其中msToken直接复制和随机生成都尝试过。
> device_platform=webapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=170400&version_name=17.4.0&cookie_enabled=true&screen_width=2560&screen_height=1440&browser_language=en&browser_platform=Win32&browser_name=Edge&browser_version=110.0.1587.41&browser_online=true&engine_name=Blink&engine_version=110.0.0.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=8&platform=PC&downlink=10&effective_type=4g&round_trip_time=0&webid=71xxxxxxxxxxxxxxxxx3666&msToken={Util.generate_random_str(107)}`

2. 修改`headers`，添加`Cookie`，`Content-Type`等，cookie从请求中直接复制
3. 拼接参数发起请求，下面是最终请求的url
> https://www.douyin.com/aweme/v1/web/commit/follow/user/?device_platform=webapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=170400&version_name=17.4.0&cookie_enabled=true&screen_width=2560&screen_height=1440&browser_language=en&browser_platform=Win32&browser_name=Edge&browser_version=110.0.1587.41&browser_online=true&engine_name=Blink&engine_version=110.0.0.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=8&platform=PC&downlink=10&effective_type=4g&round_trip_time=0&webid=7198928548617733666&msToken=yAk0N6Utra5uMM5s4XqUgX0HWxxxxxxxxxxxxxxg1ZhOmsG2dR1izWS3pNYZa51MHFAEuDHHrRGVlnnafXXhsu9nfT1VreEBlfwlXrWo22RM&X-Bogus=DFSzswVuDNvANxXhShJiDF9WX7rG

会得到一个没有返回信息的结果。学艺不精，不清楚是生成XBogus时提供的参数有误，还是其他问题导致
![image](https://user-images.githubusercontent.com/45081750/218302475-2b9438ce-e878-42b5-9680-9e9791de679c.png)

网页端的请求在payload页被分为查询字符串参数和表单数据，表单数据拼接到url中或用json形式发送也都尝试过
![image](https://user-images.githubusercontent.com/45081750/218302389-ca6c3a06-ecf8-477e-ae90-82feec8b22f1.png)

**截图**
![image](https://user-images.githubusercontent.com/45081750/218302210-6c7d8f6c-9524-434f-8bc9-6e7e95a8365b.png)
![image](https://user-images.githubusercontent.com/45081750/218302717-d373b168-5d73-4552-a5a4-ae62f3982b63.png)
![image](https://user-images.githubusercontent.com/45081750/218302772-df2cf5af-7795-4563-92d1-41006c6a52e1.png)

一个关注动作似乎被分到了三个api，第一个疑似是获取`impr_id`，第二个和第三个通过在params中的`impr_id`与`to_user_id`完成关注

**桌面（请填写以下信息）：**
-操作系统：windows10 64bit
-vpn代理：关闭
-版本：latest

**附文**
在此处添加有关此问题的文字。

**Comment by Johnserf-Seed** [comment]
你漏了一个最重要的headers参数哦，referer要修改成https://www.douyin.com/user/self  详情看我发布的接口文档 https://langyue.cc/APIdocV1.0.html 里面列出了大部分接口所需要的参数和headers，如果有误还请提交issues

**Comment by Johnserf-Seed** [comment]
添加上正确的referer就可以正常获取了
![image](https://user-images.githubusercontent.com/40727745/218304338-bcc57f1e-f32a-4134-b888-65c74a2fe686.png)

**Comment by boluohong** [comment]
> 添加上正确的referer就可以正常获取了 ![image](https://user-images.githubusercontent.com/40727745/218304338-bcc57f1e-f32a-4134-b888-65c74a2fe686.png)

请问TikTokLive的失效也是因为referer吗？？？

**Comment by ShiinaRinne** [comment]
我从关注请求里直接复制了url（包括XG），现在有正常返回信息了
![image](https://user-images.githubusercontent.com/45081750/218305333-8959f1c2-c946-4ecc-b1b7-1b0127abc3ca.png)
![image](https://user-images.githubusercontent.com/45081750/218305266-ffbe2f50-2484-41c2-acdc-259f9afd25d0.png)

不加referer的情况下会提示blocked，当referer是`https://www.douyin.com/`时候也有正常的返回结果。反而是我自行更改XG参数之后才会什么都没有，我的问题应该是调用API生成XG参数时出错了

**Comment by Johnserf-Seed** [comment]
有些接口三个一个也不能少，另外xg如果出错页面是完全空白的 blocked的情况是xg过期了，但是现在抖音延长了xg的生命周期 也就是xg不再是用过就过期

**Comment by ShiinaRinne** [comment]
> 有些接口三个一个也不能少，另外xg如果出错页面是完全空白的 blocked的情况是xg过期了，但是现在抖音延长了xg的生命周期 也就是xg不再是用过就过期

对，我现在的情况就是页面完全空白xd

**Comment by ShiinaRinne** [comment]
空白了.jpg
![image](https://user-images.githubusercontent.com/45081750/218305890-5c489850-b90a-49fd-9d4d-5675bc63fa51.png)
函数中的参数是直接从原本请求中剔除api和xg参数部分，全复制进去的

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/218306140-66e801ad-a06f-4d0d-a0d9-98480a509286.png)

cookie需要 sessionid_ss；msToken；odin_tt；
referer需要对应
user-agent浏览器默认
就可以请求成功了

**Comment by Johnserf-Seed** [comment]
你得再多测试几个参数

**Comment by ShiinaRinne** [comment]
```
import Util

headers = {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36',
    'referer':'https://www.douyin.com/user/MS4wLjABAAAAFYFDSTF8VBtSOaVAl1ex8VorboYs0neWnYScMa9CdTM',
    'Cookie': '',
    "Content-Type": "application/x-www-form-urlencoded"
}

url = "https://www.douyin.com/aweme/v1/web/commit/follow/user/?device_platform=webapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=170400&version_name=17.4.0&cookie_enabled=true&screen_width=2560&screen_height=1440&browser_language=en&browser_platform=Win32&browser_name=Edge&browser_version=110.0.1587.41&browser_online=true&engine_name=Blink&engine_version=110.0.0.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=8&platform=PC&downlink=10&effective_type=4g&round_trip_time=0&webid=7198928548617733666&msToken=ddgW0IBqBMWOoFEIz8Cp6pwd65E5NrTmnZXu95YSYY1Y6BlRSFRRqf9pcwxPhUKzvUnOnz1xqvj7FPOB00g-7wkPYIY-LA347vCNujfZSkEAb00W9M9jz-geLOcgKoXB&X-Bogus=DFSzswVuMhg8s40zShjdSENSwbuY"
payload = {'type': '1', 'user_id': '62706123686'}

datas = Util.XBogus('device_platform=webapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=170400&version_name=17.4.0&cookie_enabled=true&screen_width=2560&screen_height=1440&browser_language=en&browser_platform=Win32&browser_name=Edge&browser_version=110.0.1587.41&browser_online=true&engine_name=Blink&engine_version=110.0.0.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=8&platform=PC&downlink=10&effective_type=4g&round_trip_time=0&webid=7198928548617733666&msToken=ddgW0IBqBMWOoFEIz8Cp6pwd65E5NrTmnZXu95YSYY1Y6BlRSFRRqf9pcwxPhUKzvUnOnz1xqvj7FPOB00g-7wkPYIY-LA347vCNujfZSkEAb00W9M9jz-geLOcgKoXB' )

api_follow_url = f'https://www.douyin.com/aweme/v1/web/commit/follow/user/?{datas.params}'

r = Util.requests.post(url=api_follow_url, headers=headers, data=payload)
print(r.text)
print(r.status_code)

```
确实是不行，是因为api差异吗？我使用的这个是关注用户的动作的api，不是获取用户的关注列表

**Comment by Johnserf-Seed** [comment]
不是因为api差异，是你headers的问题

**Comment by Johnserf-Seed** [comment]
cookie: xxxxx
referrer: https://www.douyin.com/
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.41
x-secsdk-csrf-token: xxxxx

**Comment by boluohong** [comment]
> cookie: xxxxx referrer: https://www.douyin.com/ user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.41 x-secsdk-csrf-token: xxxxx

大佬大佬，顺便求问一下那个TikTokLive的bug也是因为headers吗

**Comment by Johnserf-Seed** [comment]
> > cookie: xxxxx referrer: https://www.douyin.com/ user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.41 x-secsdk-csrf-token: xxxxx
> 
> 大佬大佬，顺便求问一下那个TikTokLive的bug也是因为headers吗

不是😂 单纯是没把live的接口加xg 因为之前还能用 侥幸心理 没想到后面也挂了

**Comment by Johnserf-Seed** [comment]
> 

加上xg就能用了

**Comment by ShiinaRinne** [comment]
![image](https://user-images.githubusercontent.com/45081750/218308724-75250c20-79ae-4e3e-95e7-e40550318340.png)
![](https://user-images.githubusercontent.com/45081750/218308728-07399ed8-c3b7-4fe8-be6b-18d392c8ba47.jpg)

**Comment by Johnserf-Seed** [comment]
> ![image](https://user-images.githubusercontent.com/45081750/218308724-75250c20-79ae-4e3e-95e7-e40550318340.png) ![](https://user-images.githubusercontent.com/45081750/218308728-07399ed8-c3b7-4fe8-be6b-18d392c8ba47.jpg)

![image](https://user-images.githubusercontent.com/40727745/218308982-8d180368-a28f-4d9d-a2ea-2da7f1e6bb0a.png)
不忍打破

**Comment by Johnserf-Seed** [comment]
> ![image](https://user-images.githubusercontent.com/45081750/218308724-75250c20-79ae-4e3e-95e7-e40550318340.png) ![](https://user-images.githubusercontent.com/45081750/218308728-07399ed8-c3b7-4fe8-be6b-18d392c8ba47.jpg)

你应该是漏了msToken，生成xg也要带上的

**Comment by ShiinaRinne** [comment]
![image](https://user-images.githubusercontent.com/45081750/218309053-2f69a4bb-1dde-4961-b5ca-04ea49fe8c6b.png)
mstoken在cookie、原本链接和请求xg的方法里也都有 (毕竟是直接从网络请求里复制过来的)
postman确实可以正常使用

是这段代码里`Util.XBogus`中的参数有限制吗，出问题应该就只是在这里了

> ```
> import Util
> 
> headers = {
>     'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36',
>     'referer':'https://www.douyin.com/user/MS4wLjABAAAAFYFDSTF8VBtSOaVAl1ex8VorboYs0neWnYScMa9CdTM',
>     'Cookie': '',
>     "Content-Type": "application/x-www-form-urlencoded"
> }
> 
> url = "https://www.douyin.com/aweme/v1/web/commit/follow/user/?device_platform=webapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=170400&version_name=17.4.0&cookie_enabled=true&screen_width=2560&screen_height=1440&browser_language=en&browser_platform=Win32&browser_name=Edge&browser_version=110.0.1587.41&browser_online=true&engine_name=Blink&engine_version=110.0.0.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=8&platform=PC&downlink=10&effective_type=4g&round_trip_time=0&webid=7198928548617733666&msToken=ddgW0IBqBMWOoFEIz8Cp6pwd65E5NrTmnZXu95YSYY1Y6BlRSFRRqf9pcwxPhUKzvUnOnz1xqvj7FPOB00g-7wkPYIY-LA347vCNujfZSkEAb00W9M9jz-geLOcgKoXB&X-Bogus=DFSzswVuMhg8s40zShjdSENSwbuY"
> payload = {'type': '1', 'user_id': '62706123686'}
> 
> datas = Util.XBogus('device_platform=webapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=170400&version_name=17.4.0&cookie_enabled=true&screen_width=2560&screen_height=1440&browser_language=en&browser_platform=Win32&browser_name=Edge&browser_version=110.0.1587.41&browser_online=true&engine_name=Blink&engine_version=110.0.0.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=8&platform=PC&downlink=10&effective_type=4g&round_trip_time=0&webid=7198928548617733666&msToken=ddgW0IBqBMWOoFEIz8Cp6pwd65E5NrTmnZXu95YSYY1Y6BlRSFRRqf9pcwxPhUKzvUnOnz1xqvj7FPOB00g-7wkPYIY-LA347vCNujfZSkEAb00W9M9jz-geLOcgKoXB' )
> 
> api_follow_url = f'https://www.douyin.com/aweme/v1/web/commit/follow/user/?{datas.params}'
> 
> r = Util.requests.post(url=api_follow_url, headers=headers, data=payload)
> print(r.text)
> print(r.status_code)
> ```
>

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/218318083-46473361-0dd0-4bca-941b-4b25123d065c.png)
删掉X-Bogus就可以了，就是说 有点离谱在的

**Comment by Johnserf-Seed** [comment]
```python
import Util

headers = {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36',
    'referer': 'https://www.douyin.com/',
    'Cookie': '#你的cookie',
    "Content-Type": "application/x-www-form-urlencoded"
}

url = "https://www.douyin.com/aweme/v1/web/commit/follow/user/?device_platform=webapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=170400&version_name=17.4.0&cookie_enabled=true&screen_width=2560&screen_height=1440&browser_language=en&browser_platform=Win32&browser_name=Edge&browser_version=110.0.1587.41&browser_online=true&engine_name=Blink&engine_version=110.0.0.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=8&platform=PC&downlink=10&effective_type=4g&round_trip_time=0&webid=7198928548617733666&msToken=ddgW0IBqBMWOoFEIz8Cp6pwd65E5NrTmnZXu95YSYY1Y6BlRSFRRqf9pcwxPhUKzvUnOnz1xqvj7FPOB00g-7wkPYIY-LA347vCNujfZSkEAb00W9M9jz-geLOcgKoXB"

payload='type=1&user_id=62706123686'

r = Util.requests.post(url=url, headers=headers, data=payload)
print(r.text)
print(r.status_code)

**Comment by Johnserf-Seed** [comment]
> ![image](https://user-images.githubusercontent.com/40727745/218318083-46473361-0dd0-4bca-941b-4b25123d065c.png) 删掉X-Bogus就可以了，就是说 有点离谱在的

计算带上也可以，就是你的headers和payload格式不对

**Comment by ShiinaRinne** [comment]
删掉成了，确实太离谱了
[https://baijiahao.baidu.com/s?id=1747190670465615168&wfr=spider&for=pc](https://baijiahao.baidu.com/s?id=1747190670465615168&wfr=spider&for=pc)
[https://github.com/Leon406/pyutil/blob/28814589e6d484820b1b4ab1ee9606f766f3c97d/douyin/getXBoGust.js](https://github.com/Leon406/pyutil/blob/28814589e6d484820b1b4ab1ee9606f766f3c97d/douyin/getXBoGust.js)
我甚至在想怎么逆向了...

**Comment by ShiinaRinne** [comment]
> > ![image](https://user-images.githubusercontent.com/40727745/218318083-46473361-0dd0-4bca-941b-4b25123d065c.png) 删掉X-Bogus就可以了，就是说 有点离谱在的
> 
> 计算带上也可以，就是你的headers和payload格式不对

之前做爬虫时候还没遇见过这种payload的格式，见到的基本点开payload页都只有一个request payload，抖音是第一次见![B1GPX77J)7%JDQ5CQ`20WOP](https://user-images.githubusercontent.com/45081750/218318684-56d70509-8c1c-4f96-8313-143dab7371eb.jpg)
![RVN9BP{MQEO})H){A}6IFAC](https://user-images.githubusercontent.com/45081750/218318606-04d5ae11-d256-4f07-b7d3-95bd05c9a500.png)

**Comment by ShiinaRinne** [comment]
今天真的麻烦大佬了，非常感谢！！！

**Comment by Johnserf-Seed** [comment]
> > > ![image](https://user-images.githubusercontent.com/40727745/218318083-46473361-0dd0-4bca-941b-4b25123d065c.png) 删掉X-Bogus就可以了，就是说 有点离谱在的
> > 
> > 
> > 计算带上也可以，就是你的headers和payload格式不对
> 
> 之前做爬虫时候还没遇见过这种payload的格式，见到的基本点开payload页都只有一个request payload，抖音是第一次见![B1GPX77J)7%JDQ5CQ`20WOP](https://user-images.githubusercontent.com/45081750/218318684-56d70509-8c1c-4f96-8313-143dab7371eb.jpg) ![RVN9BP{MQEO})H){A}6IFAC](https://user-images.githubusercontent.com/45081750/218318606-04d5ae11-d256-4f07-b7d3-95bd05c9a500.png)

这个是因为post方法  其次是因为Content-Type=application/x-www-form-urlencoded，所以才是这样编码

**Comment by Johnserf-Seed** [comment]
> 今天真的麻烦大佬了，非常感谢！！！

共勉之

**Comment by Johnserf-Seed** [comment]
> /x-www-form-urlencoded

https://www.cnblogs.com/wbl001/p/12050751.html

**Comment by ShiinaRinne** [comment]
受教了，中途我其实看到urlencoded这种形式之后需要用urllib中的`parse.urlencode`转一次，只是之前那个参数和headers问题，来回试过发现没变化，加上还没接触过这种请求不太确定真实性~就又删掉了~
