### ISSUE TITLE
Max retries exceeded with url

### ISSUE THREAD

**Issue by User4gith** [Johnserf-Seed/TikTokDownload#32]
下载速度很慢，在下载了几个视频之后会报如下的错误。
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='v.douyin.com', port=443): Max retries exceeded with url:

系统环境：
Mac OS Catalina
Pycharm 21
Python 3.6.3

**Comment by Johnserf-Seed** [comment]
建议更换一下本地的网络环境
