### ISSUE TITLE
[BUG]已经更新到最新版，但依旧无法获取用户数据

### ISSUE THREAD

**Issue by SakuraXiaoWen** [Johnserf-Seed/TikTokDownload#328]
![N`_HRD0(YLIG}YEKBSD)JEH](https://user-images.githubusercontent.com/46924591/220009961-9d7e2554-7caf-4ad0-bcf1-daba0d17688d.png)

**Comment by eightrivers** [comment]
遇到同样的错误，请问大概何时能升级最新版本，感谢！

**Comment by Johnserf-Seed** [comment]
接口获取的数据一切正常，就是python请求无法获取
![image](https://user-images.githubusercontent.com/40727745/220631450-9c5d36a5-d38b-4309-a033-36850d6f2e04.png)

**Comment by Johnserf-Seed** [comment]
目前测试下来是cookie的问题，自行替换__init__.py的cookie即可

**Comment by absir1949** [comment]
@Johnserf-Seed  请教下大佬，如果ttwid失效的话，替换成啥呢？这个可以随机生成吗？还是在哪里去找啊

**Comment by Johnserf-Seed** [comment]
> @Johnserf-Seed 请教下大佬，如果ttwid失效的话，替换成啥呢？这个可以随机生成吗？还是在哪里去找啊

![image](https://user-images.githubusercontent.com/40727745/220653134-f127385d-3674-4043-852a-8621bc4d868f.png)
![image](https://user-images.githubusercontent.com/40727745/220653786-52799ca8-d6bc-4930-9adf-8956b9df3915.png)
在浏览器里就可以获取了，随机生成可用性没有测试 这是服务器返回的

**Comment by absir1949** [comment]
@Johnserf-Seed 大佬，我测试了下，使用这个ttwid，依旧概率失败，而且概率比较高。

有没有更稳定的解决办法呀？

**Comment by Johnserf-Seed** [comment]
> @Johnserf-Seed 大佬，我测试了下，使用这个ttwid，依旧概率失败，而且概率比较高。
> 
> 有没有更稳定的解决办法呀？

可以试试sessionid_ss

**Comment by absir1949** [comment]
@Johnserf-Seed 我在cookies里添加了sessionid_ss,ttcid,tt_scid,都没效果

**Comment by Johnserf-Seed** [comment]
> @Johnserf-Seed 我在cookies里添加了sessionid_ss,ttcid,tt_scid,都没效果

那就是只有ttwid有效，失败概率用多次请求来弥补吧

**Comment by absir1949** [comment]
@Johnserf-Seed 大佬，可以给个您的联系方式吗？想付费咨询个问题
