### ISSUE TITLE
（已解决附方法）高频率抓取失败，获取用户数据失败，请从web端获取新ttwid[BUG]

### ISSUE THREAD

**Issue by boluohong** [Johnserf-Seed/TikTokDownload#329]
【原问题】
已测试多个账户，并多次测试（约200次）
大部分情况下抓取失败，偶尔可以抓取成功（约2%）

失败时提示如下：
[  提示  ]:获取用户数据失败，请从web端获取新ttwid

【解决方法】
由@sunyulu-hub提供
需要浏览器访问下这个用户的主页，从cookie 中获取ttwid，替换到代码Util 包下的__init__.py的header里面的ttwid(64行)就可以了

【另附提供给刚门的朋友的建议】

> 怎么获取我只会用不会改。。。。

1.获得ttwid
（1）在电脑浏览器中打开任意抖音主页
（2）按F12---->点击network选项卡--->点击doc选项
（3）再在左下角name选项卡中任选一项---->Headerr--->RequestHeaders--->cookie
（4）在cookie中找到ttwid选项
如果仍然不会，请谷歌“如何查看网页cookies”

2.将获得的ttwid填在__init__.py
（1）打开本项目文件夹
（2）打开Util文件夹
（3）打开文件__init__.py
将新获得的ttwid替代旧的ttid.

**Comment by sunyulu-hub** [comment]
同上

**Comment by absir1949** [comment]
同上

**Comment by sunyulu-hub** [comment]
需要浏览器访问下这个用户的主页，从cookie 中获取ttwid，替换到代码Util 包下的__init__.py的header里面的ttwid(64行)就可以了

**Comment by Jalen-Sun** [comment]
现在还是不能获取用户数据，而且也不会有失败时的提示，我已经更新了也不行哇

**Comment by Jalen-Sun** [comment]
我的是windows 用那个应用程序还是获取不到

**Comment by joostshao** [comment]
> cookie

1%7CJtF5F2LkGzST_X88JWFM2fKXixiyIpRHquvLY4hIklI%7C1675431248%7Cb57809ba71ad02c593a9cd13e367c466ab22cf66788381356268f3fa821ca50d

这样？ 这个格式有点奇怪，还有百分号，我以为是占位符号呢

**Comment by boluohong** [comment]
> 需要浏览器访问下这个用户的主页，从cookie 中获取ttwid，替换到代码Util 包下的__init__.py的header里面的ttwid(64行)就可以了

鸣谢@sunyulu-hub ，按照指引操作后问题解决，非常感谢。

其他朋友有同样问题请按这种方法解决。

**Comment by Jalen-Sun** [comment]
怎么获取我只会用不会改。。。。

**Comment by BuCaicai** [comment]
> 怎么获取我只会用不会改。。。。

看一下 @sunyulu-hub 上面的方法

**Comment by Jalen-Sun** [comment]
怎么从cookie中获取 我啥也不懂 就只是用了这个软件

**Comment by boluohong** [comment]
> 怎么获取我只会用不会改。。。。

1.获得ttwid
（1）在电脑浏览器中打开任意抖音主页
（2）按F12---->点击network选项卡--->点击doc选项
（3）再在左下角name选项卡中任选一项---->Headerr--->RequestHeaders--->cookie
（4）在cookie中找到ttwid选项
如果仍然不会，请谷歌“如何查看网页cookies”

2.将获得的ttwid填在__init__.py
（1）打开本项目文件夹
（2）打开Util文件夹
（3）打开文件__init__.py
将新获得的ttwid替代旧的ttid.

**Comment by Jalen-Sun** [comment]
我找到了ttwid，按照上面的指示把他粘贴在了_init_.py对应位置，但还是一直现实需要从web端更新,是我找的这个不对吗
![image](https://user-images.githubusercontent.com/126160008/220931067-07b392c7-e4b2-4ff5-b31f-24202fc6313d.png)

**Comment by Dongdong0112** [comment]
> 我找到了ttwid，按照上面的指示把他粘贴在了_init_.py对应位置，但还是一直现实需要从web端更新,是我找的这个不对吗 ![image](https://user-images.githubusercontent.com/126160008/220931067-07b392c7-e4b2-4ff5-b31f-24202fc6313d.png)

看看你改的 应该是把其它什么给删了

**Comment by Jalen-Sun** [comment]
> > 我找到了ttwid，按照上面的指示把他粘贴在了_init_.py对应位置，但还是一直现实需要从web端更新,是我找的这个不对吗 ![image](https://user-images.githubusercontent.com/126160008/220931067-07b392c7-e4b2-4ff5-b31f-24202fc6313d.png)
> 
> 看看你改的 应该是把其它什么给删了


headers = {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36',
    'referer':'https://www.douyin.com/',
    # 获取用户数据失败就自行替换ttwid
    'Cookie': f'msToken={generate_random_str(107)};ttwid=1%7Cr_Q-AxxCaVr5B3GUNRKHZLMaSNyjNYgCgpty_FbnFDU%7C1676364849%7C57a587f233d987a8c5ab15b0b6234aa34cdb7a69fbc5bf892cd892141fa12753;'
}

**Comment by Jalen-Sun** [comment]
![image](https://user-images.githubusercontent.com/126160008/220941579-28782752-b088-477b-abe6-e75ce2914ba7.png)

**Comment by Dongdong0112** [comment]
> ![image](https://user-images.githubusercontent.com/126160008/220941579-28782752-b088-477b-abe6-e75ce2914ba7.png)

重新获取个再试试？

**Comment by Jalen-Sun** [comment]
我重新获取，这个ttwid不会改变呀，而且之前无论我怎么换，失败的提示都不会出来，就一直批量显示获取用户数据失败，我就卸载重新装了一遍，现在会显示失败的提示了但就是运行不了

**Comment by Dongdong0112** [comment]
> 我重新获取，这个ttwid不会改变呀，而且之前无论我怎么换，失败的提示都不会出来，就一直批量显示获取用户数据失败，我就卸载重新装了一遍，现在会显示失败的提示了但就是运行不了
试试我用的？
        ttwid = '1%7CPBZyFB0SfV3vOlC3tNDT1P_ttjpR_jjY6DCmjMxm7eM%7C1673196516%7Cd3d3136a87a5de0cc6e8f7ae7524da6ec814e5db7f0ef635fc0cd57396c6f6b1'
        headers = {
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36',
        'referer': 'https://www.douyin.com/',
        'Cookie': f'msToken={generate_random_str(107)};ttwid=%s;' % ttwid
        }

**Comment by Jalen-Sun** [comment]
他竟然可以了，55555，万分感谢，这快折磨死我了

**Comment by Johnserf-Seed** [comment]
哈哈哈，研究了一下 找到注册ttwid的接口了，大家可以不用这么费力的去浏览器一遍遍取了，我稍后更新一下
