### ISSUE TITLE
[BUG]新版本的TikTokTool在like模式下有错误

### ISSUE THREAD

**Issue by cmpunk160** [Johnserf-Seed/TikTokDownload#330]
20230223更新版本后使用like模式一直提示用户未开放喜欢页，请开放后重新运行，尝试了三四个抖主的都失败了，但其实抖主已开放喜欢页浏览。

**Comment by edgleaf** [comment]
我like模式一直提示请从web端获取新ttwid

**Comment by Johnserf-Seed** [comment]
旧的odin_tt参数还是不能移除，我现在加回来又可以了
