### ISSUE TITLE
[BUG]获取用户数据失败，正在重新获取

### ISSUE THREAD

**Issue by zhiben5201** [Johnserf-Seed/TikTokDownload#333]
获取用户数据失败，正在重新获取，不断的重复，无论复制电脑端长链接还是手机端短连接都无法获取用户数据

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/221562714-485460f9-d223-4266-b59b-2b155fae4de1.png)
用新版
