### ISSUE TITLE
有下载带水印视频的方法吗？

### ISSUE THREAD

**Issue by lixiaoyao0** [Johnserf-Seed/TikTokDownload#338]
通过`https://www.douyin.com/aweme/v1/web/aweme/detail/?`获取到的作品数据里面找不到带水印的链接

**Comment by Johnserf-Seed** [comment]
play addr无水印
download addr有水印

**Comment by lixiaoyao0** [comment]
> 播放地址无水印 下载地址有水印
`https://www.douyin.com/aweme/v1/web/aweme/detail/?`这个链接获取到的数据里面没有download_addr

**Comment by Johnserf-Seed** [comment]
办法还有很多
```/aweme/v1/play/?video_id=```
换
```/aweme/v1/playwm/?video_id=```

**Comment by lixiaoyao0** [comment]
成功了 多谢
