### ISSUE TITLE
[HELP] TikTokTool.py 脚本下载视频时，频繁报错JSONDecodeError("Expecting value", s, err.value)

### ISSUE THREAD

**Issue by BuCaicai** [Johnserf-Seed/TikTokDownload#339]
**描述出现的错误**
用户主页链接放在了列表里面，循环用TikTokTool.py脚本进行下载，很多都有这个问题
[  提示  ]:第 1639570616000 页抓获数据成功!
[  提示  ]:正在替换当页所有作品非法字符，耐心等待!
[  提示  ]:正在替换作者非法字符，耐心等待!
[  提示  ]:正在进行第 1 次尝试
之后就报下面的错了
希望得到大佬的回答，十分感谢！

**截图**
![image](https://user-images.githubusercontent.com/90897449/223412006-bad3d612-c437-435e-8195-d161de2ca737.png)

**桌面（请填写以下信息）：**
-操作系统：例如windows10 64bit

**Comment by BuCaicai** [comment]
好像是用户开启了禁止下载视频功能了，请教下大佬，这种情况要怎么修改呢

**Comment by Johnserf-Seed** [comment]
> 好像是用户开启了禁止下载视频功能了，请教下大佬，这种情况要怎么修改呢

无视这个禁止下载功能，删掉的视频不超过24小时还可以下到

**Comment by Dongdong0112** [comment]
> > 好像是用户开启了禁止下载视频功能了，请教下大佬，这种情况要怎么修改呢
> 
> 无视这个禁止下载功能，删掉的视频不超过24小时还可以下到

现在还是在用aweme_id判断是图片还是视频吗？ 他这个aweme_id老是变

**Comment by AoneLi** [comment]
现在那个板本的的可以用

**Comment by BuCaicai** [comment]
我尝试打印 Images.py 里面的 get_all_images 函数，jx_url 可以正常获取到，但是 r 获取为空，请问大佬，这个是什么原因呢
![image](https://user-images.githubusercontent.com/90897449/223909795-1b0f33ea-e873-478e-96f4-278f605ef9fb.png)
![image](https://user-images.githubusercontent.com/90897449/223909858-ca9319ef-7bb2-49dc-a737-59908dbdda6d.png)

**Comment by Dongdong0112** [comment]
> 我尝试打印 Images.py 里面的 get_all_images 函数，jx_url 可以正常获取到，但是 r 获取为空，请问大佬，这个是什么原因呢 ![image](https://user-images.githubusercontent.com/90897449/223909795-1b0f33ea-e873-478e-96f4-278f605ef9fb.png) ![image](https://user-images.githubusercontent.com/90897449/223909858-ca9319ef-7bb2-49dc-a737-59908dbdda6d.png)

![image](https://user-images.githubusercontent.com/102731706/223912411-6ba3ae55-0fb0-448e-bbbb-0fa491c30105.png)
可以下载的

**Comment by BuCaicai** [comment]
@Dongdong0112 谢谢大佬，可能是我环境的问题

**Comment by BuCaicai** [comment]
@Dongdong0112 大佬，你用的python是哪个版本的呢

**Comment by BuCaicai** [comment]
> > @Dongdong0112 大佬，你用的python是哪个版本的呢
> 
> 应该和版本没多大关系吧 我前段时间升到了3.11 然后好些库都没更新

谢谢大佬，可能是因为公司网络的问题，在家我是可以获取到的，今天在公司试了一下是不行的

**Comment by CCMonkeyss** [comment]
我也遇到了同样的问题，上午还好的，刚才突然就这样了。

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/224259572-7cb5ca85-bfd7-4ed9-b149-0a5d0c5d9756.png)
不要着急，半小时后更新

**Comment by BuCaicai** [comment]
> ![image](https://user-images.githubusercontent.com/40727745/224259572-7cb5ca85-bfd7-4ed9-b149-0a5d0c5d9756.png) 不要着急，半小时后更新

感谢大佬！

**Comment by BuCaicai** [comment]
> 大家试过新版了吗，没有问题我close了

大佬，刚刚试了一下，直接使用的tool脚本下载，请问这个是什么问题呢
![capture_20230311105806612](https://user-images.githubusercontent.com/90897449/224461442-b15a9236-3727-4432-b447-51b2836445e3.png)

**Comment by hubbylei** [comment]
好好阅读下readme，你没启动本地接口解析 :)

**Comment by BuCaicai** [comment]
大佬，大佬，求指点
[环境]  window10，有 python3.9.6 和 python3.11.2，默认python使用的是3.9.6，python3.11.2是用绝对路径使用的
执行了 D:\JJ\ENV\python3\Scripts\pip.exe install -r .\requirements.txt
node版本 v18.12.1
[问题]  开启本地接口服务 D:\JJ\ENV\python3\python.exe .\Server.py后
执行 D:\JJ\ENV\python3\python.exe .\TikTokTool.py 报错，如图
![image](https://user-images.githubusercontent.com/90897449/225271326-1b37b577-0487-42f1-b204-11a9b58523e6.png)
接口报错：
![image](https://user-images.githubusercontent.com/90897449/225271461-7bb8f8a4-10bb-406e-8f36-b02053bc671c.png)

**Comment by BuCaicai** [comment]
大佬大佬，求指点
开始下载后，ctrl + c 终止不掉，需要杀死进程才能停止

**Comment by BuCaicai** [comment]
> 大佬大佬，求指点 开始下载后，ctrl + c 终止不掉，需要杀死进程才能停止

大佬，for循环执行TikTokTool.py脚本后，进度条不显示
![image](https://user-images.githubusercontent.com/90897449/225280379-4e2b1b25-f38f-42b8-a857-812b0301953d.png)

**Comment by BuCaicai** [comment]
> 大佬大佬，求指点 开始下载后，ctrl + c 终止不掉，需要杀死进程才能停止

请问大佬，现在是只有未下载的才显示进度条么，没有以前的xxx[已下载]，这是特意这样做的么

**Comment by AoneLi** [comment]
大佬，这个软件还能用么？

**Comment by Johnserf-Seed** [comment]
> 大佬，这个软件还能用么？

已更新1.4.0
