### ISSUE TITLE
今天下载出现了这个问题,不知道什么情况?

### ISSUE THREAD

**Issue by GEM123668** [Johnserf-Seed/TikTokDownload#341]
![Snipaste_2023-03-10_15-56-23](https://user-images.githubusercontent.com/121158914/224257072-28b77894-9439-4ed7-bf3a-2becff973710.jpg)

**Comment by Johnserf-Seed** [comment]
配置文件的问题

**Comment by GEM123668** [comment]
> 配置文件的问题

请问作者这个要怎么修改,能不能教教

**Comment by Johnserf-Seed** [comment]
用今天推送的新版，看readme按步骤操作

**Comment by GEM123668** [comment]
> 用今天推送的新版，看readme按步骤操作

谢谢作者,现在正常下载了

**Comment by GEM123668** [comment]
不过作者我还是用传统的tiktoktool进行下载的,并没有看见优化过的进度条模式
![image](https://user-images.githubusercontent.com/121158914/224365267-51696e03-1233-43f6-8e19-f84cc9335027.png)

**Comment by Johnserf-Seed** [comment]
> 不过作者我还是用传统的tiktoktool进行下载的,并没有看见优化过的进度条模式
> ![image](https://user-images.githubusercontent.com/121158914/224365267-51696e03-1233-43f6-8e19-f84cc9335027.png)
> 

用Windows Terminal终端

**Comment by GEM123668** [comment]
> > 不过作者我还是用传统的tiktoktool进行下载的,并没有看见优化过的进度条模式
> > ![image](https://user-images.githubusercontent.com/121158914/224365267-51696e03-1233-43f6-8e19-f84cc9335027.png)
> 
> 用Windows Terminal终端

使用终端运行会出现下面这个报错,不知道什么情况.说目标积极
![Snipaste_2023-03-11_07-50-53](https://user-images.githubusercontent.com/121158914/224450213-73a700fb-e005-4f32-a6fe-e848cdbc9926.jpg)

**Comment by 286615275** [comment]
> > > 不过作者我还是用传统的tiktoktool进行下载的,并没有看见优化过的进度条模式
> > > ![image](https://user-images.githubusercontent.com/121158914/224365267-51696e03-1233-43f6-8e19-f84cc9335027.png)
> > 
> > 
> > 用Windows Terminal终端
> 
> 使用终端运行会出现下面这个报错,不知道什么情况.说目标积极 ![Snipaste_2023-03-11_07-50-53](https://user-images.githubusercontent.com/121158914/224450213-73a700fb-e005-4f32-a6fe-e848cdbc9926.jpg)

https://github.com/Johnserf-Seed/TikTokDownload/issues/342

**Comment by CCMonkeyss** [comment]
> > 不过作者我还是用传统的tiktoktool进行下载的,并没有看见优化过的进度条模式
> > ![image](https://user-images.githubusercontent.com/121158914/224365267-51696e03-1233-43f6-8e19-f84cc9335027.png)
> 
> 用Windows Terminal终端

关于这个新的下载界面我发现一点，
我运行的时候，显示的下载列表会一直刷新，前面下载的文件记录会重复叠加上去，随着下载数量增加刷屏就变得越来越厉害，如下：
文件1 下载进度%
文件1 下载进度%
文件1 下载进度%
文件2 下载进度%
文件1 下载进度%
文件2 下载进度%
文件3 下载进度%
文件1 下载进度%
文件2 下载进度%
文件3 下载进度%
文件4 下载进度%

不知道是不是我配置出错了。

**Comment by Johnserf-Seed** [comment]
> > > 不过作者我还是用传统的tiktoktool进行下载的,并没有看见优化过的进度条模式
> > > ![image](https://user-images.githubusercontent.com/121158914/224365267-51696e03-1233-43f6-8e19-f84cc9335027.png)
> > 
> > 
> > 用Windows Terminal终端
> 
> 关于这个新的下载界面我发现一点， 我运行的时候，显示的下载列表会一直刷新，前面下载的文件记录会重复叠加上去，随着下载数量增加刷屏就变得越来越厉害，如下： 文件1 下载进度% 文件1 下载进度% 文件1 下载进度% 文件2 下载进度% 文件1 下载进度% 文件2 下载进度% 文件3 下载进度% 文件1 下载进度% 文件2 下载进度% 文件3 下载进度% 文件4 下载进度%
> 
> 不知道是不是我配置出错了。

可能是系统的版本问题，终端工具不是最新 安装Windows Terminal应该可以解决你的问题

**Comment by CCMonkeyss** [comment]
> > > > 不过作者我还是用传统的tiktoktool进行下载的,并没有看见优化过的进度条模式
> > > > ![image](https://user-images.githubusercontent.com/121158914/224365267-51696e03-1233-43f6-8e19-f84cc9335027.png)
> > > 
> > > 
> > > 用Windows Terminal终端
> > 
> > 
> > 关于这个新的下载界面我发现一点， 我运行的时候，显示的下载列表会一直刷新，前面下载的文件记录会重复叠加上去，随着下载数量增加刷屏就变得越来越厉害，如下： 文件1 下载进度% 文件1 下载进度% 文件1 下载进度% 文件2 下载进度% 文件1 下载进度% 文件2 下载进度% 文件3 下载进度% 文件1 下载进度% 文件2 下载进度% 文件3 下载进度% 文件4 下载进度%
> > 不知道是不是我配置出错了。
> 
> 可能是系统的版本问题，终端工具不是最新 安装Windows Terminal应该可以解决你的问题

感谢回复，我从github安装了最新的windows terminal，然后执行python tiktoktool.py，界面变好看了，不过问题还是一样哈哈，影响不大，就是下载遇到图包文件很多的时候会等很久。
