### ISSUE TITLE
更新之后出现问题 UnboundLocalError: local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by 286615275** [Johnserf-Seed/TikTokDownload#342]
更新之后出现问题

![image](https://user-images.githubusercontent.com/32392758/224314223-8dde36ff-6cd6-4535-88ad-f512990b587b.png)

![image](https://user-images.githubusercontent.com/32392758/224314384-663006e8-dd11-4411-9505-2c03f8a82d7f.png)

**Comment by 286615275** [comment]
换成py3.11.1仍然不行

**Comment by GEM123668** [comment]
> 安装npm后解决

我安装了npm,好像还是不行

**Comment by GEM123668** [comment]
> 安装npm后解决

谢了,可以用了,我刚刚配置错误了

**Comment by xx254** [comment]
> 

请问配置要如何修改呢?

**Comment by xx254** [comment]
> > 安装npm后解决
> 
> 谢了,可以用了,我刚刚配置错误了
请问配置要如何修改呢?

**Comment by xx254** [comment]
> > 安装npm后解决
> 
> 谢了,可以用了,我刚刚配置错误了
我也遇到了这个报错, 请问配置要如何修改呢

**Comment by xx254** [comment]
> > 安装npm后解决
> 
> 谢了,可以用了,我刚刚配置错误了

我也遇到了这个报错, 请问配置要如何修改呢?

**Comment by GEM123668** [comment]
> > > 安装npm后解决
> > 
> > 谢了,可以用了,我刚刚配置错误了
> 
> 我也遇到了这个报错, 请问配置要如何修改呢?

就按照作者的readme部署
