### ISSUE TITLE
今天下载又出这个问题,都按照readme进行;了部署

### ISSUE THREAD

**Issue by GEM123668** [Johnserf-Seed/TikTokDownload#344]
![Snipaste_2023-03-11_20-44-52](https://user-images.githubusercontent.com/121158914/224485288-4e764910-afe1-4ecb-8e11-42f9abfec0bd.jpg)

**Comment by liy010** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/blob/6aa5a74e7b5dcbe746ebbea1f7ed30fc8b0fe4e9/conf.ini#L6
你把这个配置截个图看看

**Comment by Johnserf-Seed** [comment]
你有没有发现和你之前提的一样，我那会是怎么回复的呢

**Comment by AoneLi** [comment]
我现在都下不了。一放拌单连接上去下就闪退了

**Comment by Johnserf-Seed** [comment]
> 我现在都下不了。一放拌单连接上去下就闪退了

怎么用都写在readme了

**Comment by GEM123668** [comment]
> 我现在都下不了。一放拌单连接上去下就闪退了

对按作者的readme仔细部署,没有问题的.可以使用
