### ISSUE TITLE
下载的视频里水印似乎并没有去掉

### ISSUE THREAD

**Issue by alitba** [Johnserf-Seed/TikTokDownload#345]
下载的视频里水印似乎并没有去掉，另外下载的时候除了退出终端还能用什么快捷键停止程序吗？
![image](https://user-images.githubusercontent.com/55194135/224537889-7eb814b2-fab1-47d3-b505-70ce86e6e3e8.png)

感谢博主分享，下载很快很强大，期待后续更强版本

**Comment by Johnserf-Seed** [comment]
你这，视频作者自己加的水印怎么可能去掉
