### ISSUE TITLE
[BUG]运行TikTokTool.py后报如下错误，请老师指点下

### ISSUE THREAD

**Issue by huyin324** [Johnserf-Seed/TikTokDownload#349]
TikTokTool V1.3.0.70
        使用说明：
                1、本程序目前支持命令行调用和配置文件操作，GUI预览版本已经发布
                2、命令行操作方法：1）将本程序路径添加到环境变量
                                2）控制台输入 TikTokTool -u https://v.douyin.com/jqwLHjF/

                3、配置文件操作方法：1）运行软件前先打开目录下 conf.ini 文件配置用户主页和音乐下载模式
                                2）按照控制台输出信息操作

                4、如有您有任何bug或者意见反馈请在 https://github.com/Johnserf-Seed/TikTokDownload/issues 发起
                5、GUI预览版本现已发布，操作更简单 https://github.com/Johnserf-Seed/TikTokDownload/tags 下载
                6、TikTokLive 输入抖音直播间web端链接，例如 https://live.douyin.com/176819813905
                7、新版工具fastdl正在开发中 ----> https://github.com/Johnserf-Seed/fastdl

        注意：  目前已经支持app内分享短链和web端长链识别。
        
########################################################################################################################

[   💻   ]:Windows平台
[   🗻   ]:获取最新版本号中!
[   🚩   ]:目前 13070 版本已是最新
[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  提示  ]:读取本地配置完成!

[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  提示  ]:读取本地配置完成!

[  提示  ]:批量获取所有视频中!

[  提示  ]:用户的sec_id=MS4wLjABAAAAnYvcBS_b1ybrFI9j7zc3PlAvbCUHxGSJ-rq2rwDYiD4

[  错误  ]:HTTPConnectionPool(host='127.0.0.1', port=8889): Max retries exceeded with url: /xg/path?url=sec_user_id=MS4wLjABAAAAnYvcBS_b1ybrFI9j7zc3PlAvbCUHxGSJ-rq2rwDYiD4%26count=35%26max_cursor=0%26aid=1128%26version_name=23.5.0%26device_platform=android%26os_version=2333 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000180135ABE10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
Traceback (most recent call last):
  File "F:\TikTokDownload-main V1.3.0.70\TikTokTool.py", line 32, in <module>
    profile.getProfile(cmd.setting())
  File "F:\TikTokDownload-main V1.3.0.70\Util\Profile.py", line 82, in getProfile
    datas = Util.XBogus('sec_user_id=%s&count=35&max_cursor=0&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333' % (
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\TikTokDownload-main V1.3.0.70\Util\XB.py", line 30, in __init__
    self.getXbogus(url)
  File "F:\TikTokDownload-main V1.3.0.70\Util\XB.py", line 50, in getXbogus
    self.params = response["result"][0]["paramsencode"]
                  ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
[Finished in 3.3s]

**Comment by SakuraXiaoWen** [comment]
本地接口解析没启动，请仔细阅读readme

**Comment by ArvineKwok** [comment]
最新版本新增了一个Server.py文件。要先使用server.bat或者server.sh开启，再运行TikTokTool.py

**Comment by luodingquan** [comment]
已经找到原因！启动的server cmd窗口被挂起了，导致本地服务不能用，回到cmd串口 按一下回车

**Comment by Agamemnon-Peng** [comment]
raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: 缺少 ';'
127.0.0.1 - - [16/Mar/2023 21:02:57] "POST /xg/path/?url=sec_user_id=MS4wLjABAAAAq56mwq2jE_su6V3tLcGNDinTec6yntBIPWUifHLptAs%26count=35%26max_cursor=0%26aid=1128%26version_name=23.5.0%26device_platform=android%26os_version=2333 HTTP/1.1" 500 -

运行了server.bat还是报错啊，这是运行server.bat的最后几行数据

**Comment by huyin324** [comment]
> 

![1](https://user-images.githubusercontent.com/99131421/225629833-cc345f2a-2035-4cf8-be64-90b3ca62d56e.png)
我也是，运行了server.bat后报错，到窗口按了回车再执行TikTokTool.py还是一样

**Comment by luodingquan** [comment]
> 

你这是没有安装模块拉 

> > 
> 
> ![1](https://user-images.githubusercontent.com/99131421/225629833-cc345f2a-2035-4cf8-be64-90b3ca62d56e.png) 我也是，运行了server.bat后报错，到窗口按了回车再执行TikTokTool.py还是一样

你这是没有安装模块拉 这次有更新  cmd执行 下这个命令 pip install -r requirements.txt

**Comment by luodingquan** [comment]
> 

不行的话按两次回车

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/225631605-b1493b69-d47a-4bdf-9d43-d9cc6bd0f614.png)

**Comment by octahedron-lh** [comment]
![image](https://user-images.githubusercontent.com/73725434/225747966-9e5d0421-9d3a-44cf-acc9-168370fb4d05.png)
请问我这是卡在这里了吗...我是按照readme都安装了的, 这里按回车也没用啊.

**Comment by Agamemnon-Peng** [comment]
> ![image](https://user-images.githubusercontent.com/73725434/225747966-9e5d0421-9d3a-44cf-acc9-168370fb4d05.png) 请问我这是卡在这里了吗...我是按照readme都安装了的, 这里按回车也没用啊.

这只是启动了server的服务，你要再去运行tiktoktool的

**Comment by octahedron-lh** [comment]
> 

我下一步运行了tiktoktool.py的, 显示的错误和1楼一样如下图
![image](https://user-images.githubusercontent.com/73725434/226077256-66e20f9d-a2ae-4e6b-96db-d1aeacdefd1d.png)
所以我怀疑是在上一步运行server.bat这里卡住了,因为下面好像没有批处理啊...别人的好像"Press CTRL+C to quit"下面还会出现很多行

**Comment by zhiben5201** [comment]
> 不好意思,我想我悟了哈哈. 需要另外开一个terminal终端运行... (原谅我0基础...) 已经下载成功啦.

你好，我也是0基础，请问前置的三个步骤怎么完成啊，我输入PIP那个命令，提示说不是可执行命令

**Comment by zhiben5201** [comment]
> ![image](https://user-images.githubusercontent.com/40727745/225631605-b1493b69-d47a-4bdf-9d43-d9cc6bd0f614.png)

按照步骤完成了第一部所有的安装，但运行server.bat的时候，UTIL文件夹中没有python Server.py这个文件，就没办法启动服务，求解

**Comment by zhiben5201** [comment]
> ![image](https://user-images.githubusercontent.com/73725434/225747966-9e5d0421-9d3a-44cf-acc9-168370fb4d05.png) 请问我这是卡在这里了吗...我是按照readme都安装了的, 这里按回车也没用啊.

请问用什么方法启动会出现你这样的界面？

**Comment by zhiben5201** [comment]
> > ![image](https://user-images.githubusercontent.com/40727745/225631605-b1493b69-d47a-4bdf-9d43-d9cc6bd0f614.png)
> 
> 按照步骤完成了第一部所有的安装，但运行server.bat的时候，UTIL文件夹中没有python Server.py这个文件，就没办法启动服务，求解 ![捕获2](https://user-images.githubusercontent.com/103325310/227000324-8304a0bf-a0f1-4234-ae08-6c1cc1d16578.JPG)

好家伙，自己把SERVER.BAT编辑了一下，将里面的PYTHON字样删除掉就能正常运行了，之前试图把文件
![捕获2](https://user-images.githubusercontent.com/103325310/227009896-21046643-6636-4cf6-a5e0-1125e52f954b.JPG)
名改一致都不行
