### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by luodingquan** [Johnserf-Seed/TikTokDownload#351]
![image](https://user-images.githubusercontent.com/47214142/225497000-65ec7d14-12e3-4aec-b893-e07247c07c5d.png)

没有返回数据 ？这是接口出问题了？

**Comment by CCMonkeyss** [comment]
是不是没运行server.bat

**Comment by luodingquan** [comment]
> 

不是 ，运行了 。我调试了一下 好像是接口数据没有返回

**Comment by luodingquan** [comment]
已经找到原因！启动的server 窗口被挂起了，导致本地服务不能用，

**Comment by luodingquan** [comment]
解决方案 ：回到server cmd窗口回车一下
