### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by huyin324** [Johnserf-Seed/TikTokDownload#352]
已按照readme运行了Util目录下的Server.py，终端窗口已经启动服务，也按照其他帖子上在终端窗口按了Enter，目前重复报同一错误，请各位老师帮忙看下。
![2](https://user-images.githubusercontent.com/99131421/225617031-f187056d-cbe3-47a4-b7d6-c932195a937f.png)
![1](https://user-images.githubusercontent.com/99131421/225617043-67e249ea-cb9c-45fc-81b6-7abf353366c2.png)

**Comment by Johnserf-Seed** [comment]
没有看完readme吗，node的依赖要安装
