### ISSUE TITLE
[BUG]pip install不成功

### ISSUE THREAD

**Issue by xx254** [Johnserf-Seed/TikTokDownload#358]
**描述出现的错误**
跑 pip install -r requirements.txt 不成功

**bug复现**
复现这次行为的步骤：
git clone
cd TikTokDownload
vim conf.ini // 添加了我的抖音链接
pip install -r requirements.txt

**截图**
![image](https://user-images.githubusercontent.com/20279502/226206971-e65b432a-f015-4ff3-836d-f3f950870d31.png)

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]
-vpn代理[例如开启、关闭]
-版本[如1.2.3]

**附文**
在此处添加有关此问题的文字。

**Comment by LingLi-su** [comment]
got the same issue, please help!

**Comment by BuCaicai** [comment]
试一下这个呢
pip install --upgrade setuptools

**Comment by xx254** [comment]
谢谢, 我直接下载了 PyQt6 就好了
