### ISSUE TITLE
请问配置文件的cookie格式是什么？

### ISSUE THREAD

**Issue by qidian11** [Johnserf-Seed/TikTokDownload#363]
cookie的值直接复制进去会报错。。是我的格式有问题吗？
我的格式类似:cookie = odin_tt=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;passport_csrf_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;

**Comment by zhiben5201** [comment]
不复制COOKIE，一切默认的话还能正常下载使用吗

**Comment by Johnserf-Seed** [comment]
![1679640765532](https://user-images.githubusercontent.com/40727745/227447341-b6952951-1fbe-4c51-99fd-5e98fcf7e1d5.png)

全部cookie粘贴也可以的

**Comment by 286615275** [comment]
> ![1679640765532](https://user-images.githubusercontent.com/40727745/227447341-b6952951-1fbe-4c51-99fd-5e98fcf7e1d5.png)
> 
> 全部cookie粘贴也可以的

![image](https://user-images.githubusercontent.com/32392758/227535643-33ab0092-9554-46e0-ac80-89e78747d076.png)


试了半天都还是报错，ttwid那个

**Comment by 286615275** [comment]
> > ![1679640765532](https://user-images.githubusercontent.com/40727745/227447341-b6952951-1fbe-4c51-99fd-5e98fcf7e1d5.png)
> > 全部cookie粘贴也可以的
> 
> ![image](https://user-images.githubusercontent.com/32392758/227535643-33ab0092-9554-46e0-ac80-89e78747d076.png)
> 
> 试了半天都还是报错，ttwid那个

![image](https://user-images.githubusercontent.com/32392758/227749963-12f0157e-dbfb-4fc7-9735-bd4bdcf3ad41.png)
yiujiejue已解决，居然不能加空行，这样才行

**Comment by zhiben5201** [comment]
> > > ![1679640765532](https://user-images.githubusercontent.com/40727745/227447341-b6952951-1fbe-4c51-99fd-5e98fcf7e1d5.png)
> > > 全部cookie粘贴也可以的
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/32392758/227535643-33ab0092-9554-46e0-ac80-89e78747d076.png)
> > 试了半天都还是报错，ttwid那个
> 
> ![image](https://user-images.githubusercontent.com/32392758/227749963-12f0157e-dbfb-4fc7-9735-bd4bdcf3ad41.png) yiujiejue已解决，居然不能加空行，这样才行

一直都显示要重新弄TTWID，各种复制了COOKIE也不行，有什么办法吗？

**Comment by Johnserf-Seed** [comment]
#311

**Comment by Johnserf-Seed** [comment]
odin_tt=xxx;sessionid_ss=xxx;ttwid=xxx;passport_csrf_token=xxx;msToken=xxx;
