### ISSUE TITLE
[BUG]运行出现错误47.115.200.238

### ISSUE THREAD

**Issue by cnmstudio** [Johnserf-Seed/TikTokDownload#368]
[  错误  ]:HTTPConnectionPool(host='47.115.200.238', port=80): Max retries exceeded with url: /xg/path?url=sec_user_id=MS4wLjABAAAAvS405blE94eUVHBDo9wxmMEkEC8iFSW9VR9yS6RcAag%26count=35%26max_cursor=0%26aid=1128%26version_name=23.5.0%26device_platform=android%26os_version=2333 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001550D05EC10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

这个，47.115.200.238是个什么服务器？

**Comment by hubbylei** [comment]
更新到最新源码,仔细看readme

**Comment by Johnserf-Seed** [comment]
现在使用的是本地服务解析
