### ISSUE TITLE
video_download 异常  [BUG]

### ISSUE THREAD

**Issue by lguowang** [Johnserf-Seed/TikTokDownload#371]
TikTokDownload.py 函数输入url = '0.74 XZZ:/ 复制打开抖音，看看【江疏影的作品】今天来分享一下我的皮肤管理小技巧！# 极萌大熨斗 ... https://v.douyin.com/AMhqKbW/'

出现一些错误，要如何解决？？

video_download(url, music, name, headers)
[  错误  ]:Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 12, in video_download
  File "D:\斗音\去水印\TikTokDownload-main\Util\XB.py", line 30, in __init__
    self.getXbogus(url)
  File "D:\斗音\去水印\TikTokDownload-main\Util\XB.py", line 50, in getXbogus
    self.params = response["result"][0]["paramsencode"]
UnboundLocalError: local variable 'response' referenced before assignment

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]
-vpn代理[例如开启、关闭]
-版本[如1.2.3]

**附文**
在此处添加有关此问题的文字。

**Comment by hubbylei** [comment]
本地服务启动了？

**Comment by WWRichard** [comment]
#361 [https://github.com/Johnserf-Seed/TikTokDownload/issues/361](url)

**Comment by Johnserf-Seed** [comment]
无效issues，请看完readme的指引再来提问，步骤百度都有

**Comment by Johnserf-Seed** [comment]
#311
