### ISSUE TITLE
用户信息如何爬取 接口地址 /aweme/v1/web/user/profile/other/

### ISSUE THREAD

**Issue by lzh2331258** [Johnserf-Seed/TikTokDownload#373]
用户详情信息如何爬取 接口地址 /aweme/v1/web/user/profile/other/
比如 参数如何构造

**Comment by 2424004764** [comment]
同问，接口字段不清楚怎么传

**Comment by Johnserf-Seed** [comment]
https://johnserf-seed.github.io/f2/guide/apps/douyin/#%E7%94%A8%E6%88%B7%E4%BF%A1%E6%81%AF-%F0%9F%9F%A2
