### ISSUE TITLE
[BUG] 手动添加ttwid cookie在conf.ini文件内后多个程序出现报错

### ISSUE THREAD

**Issue by EsperantoP** [Johnserf-Seed/TikTokDownload#378]
**描述出现的错误**
手动添加ttwid cookie在conf.ini文件内后多个程序出现报错

**bug复现**
我只更改了conf.ini文件内的cookie的值，从cookie = (空的) 更改到cookie = ttwid=1%7CcD2EOyU_esjoS8LcZ0332mfdwNKGed2WOlU_nUaKAb0%7C1680107715%7Cc5f74113bd376a000f0cfc007bbe97270032cc53a01417ee2c5b4fb57852b89b
我没有点击任何出了运行程序所必须的文件或操作。

**截图**
![image](https://user-images.githubusercontent.com/81968849/228620621-dcd4ab23-d2c9-40b1-891d-f9771b785051.png)
![image](https://user-images.githubusercontent.com/81968849/228622210-cf8fa72b-16cc-456f-9504-7ad4babbdfad.png)

**桌面：**
-操作系统：[Windows10 Pro 64bit]
-vpn代理[关闭]
-版本[13070]

**附文**
我今天刚遇到这个问题，并且查看了所有被issue了的，类似的问题，大多数并不适用。我还是在最新的那一篇有这个问题并且有解决方案的issue里面找到了添加cookie的方法。但是在执行以后，程序则出现报错，并且无法被还原。在删除配置文件内的cookie的值以后，问题仍在。

**Comment by Johnserf-Seed** [comment]
填这[odin_tt，sessionid_ss，ttwid，passport_csrf_token，msToken]5个cookie就可以了

**Comment by EsperantoP** [comment]
> 填这`odin_tt`，`sessionid_ss`，`ttwid`，`passport_csrf_token`，`msToken`5个cookie的值就可以了

好的，我试试

**Comment by EsperantoP** [comment]
> 填这`odin_tt`，`sessionid_ss`，`ttwid`，`passport_csrf_token`，`msToken`5个cookie的值就可以了

在填写变量并赋值之后，程序不报错了，但是还是需要我填写从web端获取的ttwid
![image](https://user-images.githubusercontent.com/81968849/230132381-dce61ae8-6cfc-4376-b5bf-8dfa2be92909.png)

**Comment by EsperantoP** [comment]
> 填这`odin_tt`，`sessionid_ss`，`ttwid`，`passport_csrf_token`，`msToken`5个cookie的值就可以

感谢兄弟，我发现了我填写的cookie的值有格式错误。我会把我解决的方式发出来

**Comment by Johnserf-Seed** [comment]
> > 填这`odin_tt`，`sessionid_ss`，`ttwid`，`passport_csrf_token`，`msToken`5个cookie的值就可以
> 
> 感谢兄弟，我发现了我填写的cookie的值有格式错误。我会把我解决的方式发出来

项目的配置文件里写清楚了的，去掉换行就可以了

**Comment by EsperantoP** [comment]
### 解决方法：

1. 请看这篇Issue：https://github.com/Johnserf-Seed/TikTokDownload/issues/365
    **以确保你的cookie文件格式是正确的。**
    要点：**一定一定要在 <变量=值>的后面加上”;“**
    **如果你使用的是VS Code编辑的文件，它会显示为绿色的，不必担心，因为这就是正确的格式。**
    PS：如果你不知道如何获取cookie的变量或者值，请使用Google Chrome 或 Opera... 浏览器登录抖音 （我将使用Opera进行演示）
![image](https://user-images.githubusercontent.com/81968849/230136773-982fe391-4d60-4dae-be43-fd9349eb6830.png)

    然后点击锁头的标志
![image](https://user-images.githubusercontent.com/81968849/230137127-567284ee-e914-4134-b71b-ca45bfea797c.png)

    就会出现三个选项，选择cookie那一栏
![image](https://user-images.githubusercontent.com/81968849/230137710-3dca387a-fc62-4a18-b338-d1f4ce593621.png)

    然后选择（点击）“douyin.com"并打开其中的文件
![image](https://user-images.githubusercontent.com/81968849/230138688-0e96d175-5755-45bd-8eb0-cb04ebeacef1.png)

    现在你就可以寻找你需要的变量以及值了。在列表内列出来的是“变量”，点击变量后出现的是详细信息包括其“值”
![image](https://user-images.githubusercontent.com/81968849/230139855-55f6336d-c7b1-4896-9e5b-7e99b185453a.png)

    在值内，值可能过长所以不会全部显示。建议使用Control+A（全选）来选择全部的值。
    然后就可以粘贴进conf.ini文件内了。

2. 在更改完配置文件后，**请一定重启server.bat**
    这样可以避免报错重现。

3. **一定一定不要更改任何除了conf.ini文件以外的文件**
    你将面临巨大的困境若你更改了其他配置文件并且对于编程一无所知（对，就是我）

4. 若上述方法对你的困境无效，请务必翻看所有已经被提出的Issue：https://github.com/Johnserf-Seed/TikTokDownload/issues
    若始终无法解决请创建一个新的Issue并详细表述你所遇到的问题。

**Comment by EsperantoP** [comment]
> > > 填这`odin_tt`，`sessionid_ss`，`ttwid`，`passport_csrf_token`，`msToken`5个cookie的值就可以
> > 
> > 
> > 感谢兄弟，我发现了我填写的cookie的值有格式错误。我会把我解决的方式发出来
> 
> 项目的配置文件里写清楚了的，去掉换行就可以了

是的，我的理解能力捉急，没看懂。。。

**Comment by EsperantoP** [comment]
> 我也碰到了和你一样的问题，不知道怎么搞

问题已经解决了，请看评论：https://github.com/Johnserf-Seed/TikTokDownload/issues/378#issuecomment-1497771674
