### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by huchengyong** [Johnserf-Seed/TikTokDownload#387]
**描述出现的错误**
运行TikTokDownload闪退, 日志里只有正常抓取内容。还有明明下载的最新版本, 每次都要提示更新版本, 输入y闪退, 输入n, 解析配置文件没一会闪退, 没有报错日志, 日志只到正在抓取内容那一步

**桌面（请填写以下信息）：**
-操作系统：[windows10 64bit]

**附文**
配置文件确定是utf8格式。

**Comment by Johnserf-Seed** [comment]
网络环境问题，自行解决
