### ISSUE TITLE
直播Live下载工具推荐

### ISSUE THREAD

**Issue by WangYan-Good** [Johnserf-Seed/TikTokDownload#388]
请问题主一般下载Live数据时推荐什么下载工具？
我是用迅雷可以下载，但是好像回看不了

**Comment by Cabernet-1922** [comment]
IDM

**Comment by Johnserf-Seed** [comment]
- 用potplayer可以一边看一边录制，因为抖音推流是编码很大所以先Ctrl + F1查看码率后选MPEG4 MP4，再提高500左右的码率录制即可
![1681057043175](https://user-images.githubusercontent.com/40727745/230784157-d7a4316e-f74c-41e2-af5a-60f3f1291d92.png)

- 只是下载就用IDM

**Comment by WangYan-Good** [comment]
感谢感谢，已经成功下载了
