### ISSUE TITLE
在批量下载的最后出现【请输入抖音链接】 这个提示

### ISSUE THREAD

**Issue by User4gith** [Johnserf-Seed/TikTokDownload#39]
另外频道主页显示有上万个视频，最后下载数量是300+。
检查频道主页下的视频内容，里面存在很多重复视频，是这个原因吗？

**Comment by Johnserf-Seed** [comment]
经测试，下载完成后并无出现【请输入抖音链接】 这个提示，重复视频是不会下载的

**Comment by User4gith** [comment]
用的大佬最新的程序
可以用这个测试一下不？ https://v.douyin.com/eE8EwPC/

最后出现的如下：

该页音频没有35个,已为您跳过

        使用方法: 1、添加为环境变量 2、输入命令
        -u<url 抖音复制的链接:https://v.douyin.com/JtcjTwo/>
        -m<music 是否下载音频,默认为yes可选no>
        
        例如：TikTokDownload.exe -u https://v.douyin.com/JtcjTwo/ -m yes
        
    
请输入抖音链接:

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/128871359-c4659736-605a-47ba-8e7f-18be5201698e.png)
![image](https://user-images.githubusercontent.com/40727745/128871520-c89df999-6968-414e-adb2-5a24163ea40a.png)
经测试一切正常哦，可能是有部分提示“音频”没有改回“视频”，其他无任何问题

**Comment by User4gith** [comment]
知道原因了，我没注释掉单条下载 。。。。。
