### ISSUE TITLE
[BUG]直接打开tool.exe闪退，用shell报错

### ISSUE THREAD

**Issue by Amakuas** [Johnserf-Seed/TikTokDownload#390]
**描述出现的错误**
 按照教程各项都安装完毕了，到最后报错。之前家里的台式直接就可以运行，这个笔记本不知道为什么各种闪退报错

**bug复现**
复现这次行为的步骤：
1.更改了什么什么
2.点击了什么什么
3.“……”

**截图**
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "TikTokTool.py", line 29, in <module>
    # 获取主页内容
    ^^^^^^^^^
  File "Util\Profile.py", line 82, in getProfile
    datas = Util.XBogus('sec_user_id=%s&count=35&max_cursor=0&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333' % (
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Util\XB.py", line 30, in __init__
    self.getXbogus(url)
  File "Util\XB.py", line 50, in getXbogus
    self.params = response["result"][0]["paramsencode"]
                  ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
[33964] Failed to execute script 'TikTokTool' due to unhandled exception!

**桌面（请填写以下信息）：**
-操作系统：w11 64bit
-vpn代理[例如开启、关闭]
-版本[如1.2.3]

**附文**
在此处添加有关此问题的文字。

**Comment by Johnserf-Seed** [comment]
这个报错#311 里写了
