### ISSUE TITLE
下载增加合集选项

### ISSUE THREAD

**Issue by idesign521** [Johnserf-Seed/TikTokDownload#40]
可以下载合集吗？有的知识博主合集整理得挺好的

**Comment by Johnserf-Seed** [comment]
可以下载，代码更新中

**Comment by RobotJohns** [comment]
别人的 uid 怎么获取？

**Comment by lei334453** [comment]
能不能在config配置的时候配置多个主页的uid，下载完一个，（或者通过配置参数去实现他应该连续下载还是单个下载）继续让它去下载配置好的下一个主页的视频，拿到config配置的时候做判断uid1 uid2 uid3或者更多遍历一下这个样子，不懂python，只是小迷弟的想法，哈哈哈

**Comment by Johnserf-Seed** [comment]
> 能不能在config配置的时候配置多个主页的uid，下载完一个，（或者通过配置参数去实现他应该连续下载还是单个下载）继续让它去下载配置好的下一个主页的视频，拿到config配置的时候做判断uid1 uid2 uid3或者更多遍历一下这个样子，不懂python，只是小迷弟的想法，哈哈哈

因为程序支持调用，暂时可以编写一个bat调用，不过程序下载完毕之后是有一个input的，你可以修改input重新使用build.bat进行编译。
例如：
```bat
@echo off
.\TikTokMulti.exe -u https://www.douyin.com/user/MS4wLjABAAAA5sofqwkCjeZqwtTMs00E5HAg8udRR-warVgfPykwwgk
.\TikTokMulti.exe -u https://www.douyin.com/user/MS4wLjABAAAA7EKo_lBub8KInuZgG92yuvyRqMJg8fDW4vzVFcDGHDW_ikp74iJsKToHXjoCmVoE
echo 下载完成
```

**Comment by shanlanCoding** [comment]
> 可以下载，代码更新中

合集还没有吗？
