### ISSUE TITLE
更新到了最新版, 但是突然下载不了了.

### ISSUE THREAD

**Issue by octahedron-lh** [Johnserf-Seed/TikTokDownload#409]
**描述出现的错误**
 出现以下截图中的错误, 不知道是哪里的问题... 希望得到大家的帮助~ 

**截图**
![image](https://user-images.githubusercontent.com/73725434/233844881-8f5a169b-0a4e-484a-8f13-b3216c9a2868.png)

**Comment by edgleaf** [comment]
把之前文件都删了，重新安装，好使
