### ISSUE TITLE
回车直接闪退

### ISSUE THREAD

**Issue by AstroboyPlus** [Johnserf-Seed/TikTokDownload#41]
直接闪退
![image](https://user-images.githubusercontent.com/79345447/128590863-51c98ef1-fff3-4ef9-99b4-62cc537c4ed2.png)

**Comment by Johnserf-Seed** [comment]
你的配置我测试了，一切正常，截一下报错看看

**Comment by AstroboyPlus** [comment]
在哪里看报错啊  哈哈哈

**Comment by Johnserf-Seed** [comment]
用cmd运行可以看到

**Comment by AstroboyPlus** [comment]
开了代理的原因 关了就好了
