### ISSUE TITLE
[BUG]UnboundLocalError: cannot access local variable 'response' where it is not associated with a value

### ISSUE THREAD

**Issue by ahlblzk** [Johnserf-Seed/TikTokDownload#413]
**描述出现的错误**

[  错误  ]:HTTPConnectionPool(host='127.0.0.1', port=8889): Max retries exceeded with url: /xg/path?url=aid=6383%26sec_user_id=MS4wLjABAAAA2QRVPqnJ5giG5HepkLciwuJ_ZKmzj7nIeyB9iy0B8SFSA_hvkxL0C4X-a1alOlu0%26count=35%26max_cursor=0%26cookie_enabled=true%26platform=PC%26downlink=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107999210>: Failed to establish a new connection: [Errno 61] Connection refused'))
Traceback (most recent call last):
  File "TikTokTool.py", line 32, in <module>
  File "Util/Profile.py", line 84, in getProfile
  File "Util/XB.py", line 30, in __init__
  File "Util/XB.py", line 50, in getXbogus
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
[32333] Failed to execute script 'TikTokTool' due to unhandled exception!

**桌面（请填写以下信息）：**
-操作系统：[macOS 64bit]
-版本 TikTokTool V1.3.0.80

**附文**
有人碰到这个错误没？

**Comment by arstum** [comment]
rebuild and then work

**Comment by doio** [comment]
楼上正解，安装依赖然后 Util 里面 npm i 就能解决了

**Comment by ahlblzk** [comment]
感谢 问题已解决
「关于UnboundLocalError: local variable 'response' referenced before assignment
没有正确启动本地Server服务，确保正确安装Node.js，终端进入Util目录输入npm i安装node依赖，然后启动Server.bat即可」
这个啥时候加的，我记得以前不需要启动这个服务
