### ISSUE TITLE
[BUG]闪退

### ISSUE THREAD

**Issue by summer990** [Johnserf-Seed/TikTokDownload#415]
请问这是什么问题？
![image](https://user-images.githubusercontent.com/52158736/234834996-96c15b5a-62a8-4dd7-b737-93b58aaf418f.png)

**Comment by Johnserf-Seed** [comment]
请阅读readme并按操作部署

**Comment by ZhouSong0** [comment]
> 请问这是什么问题？ ![image](https://user-images.githubusercontent.com/52158736/234834996-96c15b5a-62a8-4dd7-b737-93b58aaf418f.png)

请问问题解决了吗，我也是遇到这个问题了。。
