### ISSUE TITLE
[BUG]下载时，控制台屏闪问题

### ISSUE THREAD

**Issue by mj900912** [Johnserf-Seed/TikTokDownload#420]
**描述出现的错误**
使用windows terminal运行TikTokTool.py时，前期没什么问题，下载数据多了，上半部分就开始屏闪。我找不到解决办法，求助

https://user-images.githubusercontent.com/101454871/235333538-a3246658-7fbb-451c-9123-975983aee8ac.mp4

**桌面（请填写以下信息）：
windows10 64bit

**Comment by Johnserf-Seed** [comment]
升级了rich库之后，新版的代码这个问题稍微减轻了一点。
