### ISSUE TITLE
小白求助！！！

### ISSUE THREAD

**Issue by FigoY** [Johnserf-Seed/TikTokDownload#425]
[  错误  ]:HTTPConnectionPool(host='47.115.200.238', port=80): Max retries exceeded with url: /xg/path?url=sec_user_id=MS4wLjABAAAAoh3-GNimLQTbYbPB-TvbCXS7o530IPa6VNhMykrcT5A%26count=35%26max_cursor=0%26aid=1128%26version_name=23.5.0%26device_platform=android%26os_version=2333 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000115A620F750>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
Traceback (most recent call last):
  File "TikTokTool.py", line 29, in <module>
    profile.getProfile(cmd.setting())
  File "Util\Profile.py", line 82, in getProfile
    datas = Util.XBogus('sec_user_id=%s&count=35&max_cursor=0&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333' % (
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Util\XB.py", line 30, in __init__
    self.getXbogus(url)
  File "Util\XB.py", line 50, in getXbogus
    self.params = response["result"][0]["paramsencode"]
                  ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
[2604] Failed to execute script 'TikTokTool' due to unhandled exception!

**Comment by Johnserf-Seed** [comment]
用最新版
