### ISSUE TITLE
[BUG]我遇到了一个很神奇的bug。

### ISSUE THREAD

**Issue by mj900912** [Johnserf-Seed/TikTokDownload#433]
**截图**

https://github.com/Johnserf-Seed/TikTokDownload/assets/101454871/04a02c83-eec5-417b-b93c-ff7cd53da46e

cookie是全复制的。

**Comment by Johnserf-Seed** [comment]
rich库的progress有异常，不知道你的版本是什么，有可能是之前那个跳过显示已存在的视频版本？等待新版推送
