### ISSUE TITLE
[BUG] 在配置完成后运行TikTokTool出现“获取用户数据失败，请从web端获取新ttwid填入配置文件”报错

### ISSUE THREAD

**Issue by callmebobo** [Johnserf-Seed/TikTokDownload#437]
可否有高人帮助，

![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/43327521/25b84767-9bef-4cc3-945b-38bad1660815)

![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/43327521/51bf0c97-cb76-4183-9e0d-b12a35d7d6a2)

在配置完成后运行TikTokTool出现“获取用户数据失败，请从web端获取新ttwid填入配置文件”报错

请问该如何解决，万分感谢

**Comment by Johnserf-Seed** [comment]
cookie你没配置，请仔细阅读readme  ==

**Comment by kong6001** [comment]
请问cookie 如果配置呢，格式是是什么，copy cookie到配置了，但还是提示错

**Comment by Johnserf-Seed** [comment]
#311

**Comment by ZaiKL** [comment]
升级后 我也遇到了这个问题 


可以试试这个

更改 Cookies.py  
   # 'referer': 'https://www.douyin.com/',
两个都更改为任意用户主页 即可 也可以是当前爬取用户主页
 'referer': 'https://www.douyin.com/user/MS4wLjABAAAAhYUeN0tvYOPjxZIRuMmLtqwM0y0RbYpqmpad1_mZd-4',
后正常

**Comment by zgz682000** [comment]
> 

昨天试了改referer确实好使，今天又不行了

**Comment by ZaiKL** [comment]
改下 Cookies.py
`# self.conf[3] cookie`
更改为 
`self.conf[3] = '浏览器请求头->原始数据  找到->>Cookie : [ Cookie 所有value ] 粘贴到这里'`
![图片](https://github.com/Johnserf-Seed/TikTokDownload/assets/86660941/6e0523f3-aa1e-4df1-96b0-0e1a586ab77a)

**Comment by zhengjinzhj** [comment]
> 改下 Cookies.py `# self.conf[3] cookie` 更改为 `self.conf[3] = '浏览器请求头->原始数据 找到->>Cookie : [ Cookie 所有value ] 粘贴到这里'` ![图片](https://user-images.githubusercontent.com/86660941/240471877-6e0523f3-aa1e-4df1-96b0-0e1a586ab77a.png)

不好使啊

**Comment by zgz682000** [comment]
一会好使，一会不好使，感觉是不是跟ip有关啊

**Comment by andrewgf988** [comment]
same error, idk how to fix this, im not updatecode but still get this error 4 days ago

**Comment by 6986552** [comment]
配置好cookie很快就失效，而且重新配置的cookie内容和之前没变化也能继续好使，有时候新获取的cookie怎么配置都没用。

**Comment by fungchunhoeasy** [comment]
提示重新填写 ttwid 然后重新把整个cookie更新了 结果还是不行 已经试过好多次 之前是可以的

**Comment by LetMeCarryU** [comment]
> 

截止到一个小时前，下作者主页发布的视频，我的还是可以的。
把你的抖音账号退出，清空浏览器缓存，清空douyin域名和字节跳动域名下的所有cookie，重新登陆获取新的cookie，试一试。
