### ISSUE TITLE
INFO: 'bit_rate',因为每次不一定完全返回35条数据！WARNING: list index out of range[BUG]

### ISSUE THREAD

**Issue by LetMeCarryU** [Johnserf-Seed/TikTokDownload#444]
**描述出现的错误**
我用的是tiktoktool.py下载，下载like的时候，完成几百条以后，tiktoktool.py窗口自动退出，server端窗口没有异常信息。

日志显示INFO: 'bit_rate',因为每次不一定完全返回35条数据！WARNING: list index out of range[BUG]

![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/32630090/42e12627-16b7-4989-9664-7fa7e6fe41ae)

版本最新版的，开了自动更新。[1.3.0.80版本]

根据我的经验，具体下载到第几百条报越界不确定，少的200多条，最多的时候600多条。
因为能正常下载一部分，所以我觉得配制文件，操作步骤什么的应该没问题。
不懂怎么调试py，求帮助。

报错的日志：
[2023-06-07_142538.log](https://github.com/Johnserf-Seed/TikTokDownload/files/11673752/2023-06-07_142538.log)

我的配制文件：
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/32630090/721352e7-744f-45a1-95fd-ce57fb1dfcc7)

**Comment by LetMeCarryU** [comment]
现在开始学python！！

**Comment by LetMeCarryU** [comment]
能不能看一下这里怎么回事儿：

只取到了desc,后面俩取不到

```
                    self.author_list.append(str(result[v]['desc']))
                    self.url_list.append(str(result[v]['video']['bit_rate'][0]['play_addr']['url_list'][0]))
                    self.aweme_id.append(str(result[v]['aweme_id']))
```
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/32630090/46564224-9a0c-4c88-8940-0ac70967d0b6)


![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/32630090/3ba39ae3-d77d-41f7-9bfd-72eb511c4828)


---

附上response和result

[response.text.txt](https://github.com/Johnserf-Seed/TikTokDownload/files/11682571/response.text.txt)



[result.txt](https://github.com/Johnserf-Seed/TikTokDownload/files/11682570/result.txt)

**Comment by LetMeCarryU** [comment]
原来是有的视频没有bit_rate

我在这儿加了两句话，它好了。

![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/32630090/cc5ee2bc-9962-43ef-b8c8-19471fff6855)

**Comment by EsperantoP** [comment]
老哥真🐂🍺，学一天python就能修bug属实厉害
