### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by hezhengchao** [Johnserf-Seed/TikTokDownload#446]
**描述出现的错误**
您好！
Mac OS系统执行：Python3 TikTokTool.py
视频正常下载到post目录；但是pic目录下都是空。这个是啥原因啊？

**Comment by zhiben5201** [comment]
该用户发了图，才会下载到PIC里

**Comment by hezhengchao** [comment]
@zhiben5201 ,是的，就是用户发了图集。下载到pic目录，是空目录。

**Comment by Johnserf-Seed** [comment]
路径问题已经修复
