### ISSUE TITLE
批量下载失效，求更新

### ISSUE THREAD

**Issue by jayvzh** [Johnserf-Seed/TikTokDownload#45]
现在是www.iesdouyin.com/share/user/61991094632?XXXXXXXXXXXX
这种，跳转后是
https://www.douyin.com/user/MS4wLjABAAAAt7VyKvSkkHz_WufLbS8dKIR5tQwCprWUJATHh49BTRU
这种，
配置文件放上面两种都会失败闪退
求更新

**Comment by Johnserf-Seed** [comment]
注意看readme，配置文件中输入的是app内分享的链接，不是这种格式
