### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zuoweiya** [Johnserf-Seed/TikTokDownload#452]
**描述出现的错误**
1、MAC版本下，TikTokTool.py工具，图片类的抖音视频，会在pic目录中创建字目录，但是没有下载到图片
2、请问对于图片类的抖音视频，使用TikTokTool.py工具默认没有保存为视频格式，请问是否有支持下载为视频的选项

**Comment by Johnserf-Seed** [comment]
图集作品在抖音不是视频形式，是自动轮播图
