### ISSUE TITLE
[BUG]最新的90版本是不是用不上SERVER.BAT了？

### ISSUE THREAD

**Issue by zhiben5201** [Johnserf-Seed/TikTokDownload#454]
最新的90版本是不是用不上SERVER.BAT了？今天更新了最新的90版本，按照过去的流程打开SERVER再打开PY下载，发现SERVER在读取的时候不再像过去一样刷新信息了，是不是新版不依赖SERVER了？还是我哪个设置有问题？

**Comment by Johnserf-Seed** [comment]
是的，我写了PY的纯算法，不需要依赖node了。server继续保留可以自行调用

**Comment by zhiben5201** [comment]
> 是的，我写了PY的纯算法，不需要依赖node了。server继续保留可以自行调用

谢谢
