### ISSUE TITLE
I'm Very Beginner

### ISSUE THREAD

**Issue by radenhendriawan** [Johnserf-Seed/TikTokDownload#458]
sorry if I'm very beginner, how to overcome a display like this 
![Screenshot_1](https://github.com/Johnserf-Seed/TikTokDownload/assets/132964012/52837d77-d2fd-4f0b-a9ad-762460e25d6a)

**Comment by gaawinglf** [comment]
应该是编码方式的问题，你的终端没有正确识别出中文，你可以在终端上尝试更改一下编码方式

**Comment by radenhendriawan** [comment]
> 应该是编码方式的问题，你的终端没有正确识别出中文，你可以在终端上尝试更改一下编码方式

how to handle it? I've tried many ways on the internet but still can't

**Comment by gaawinglf** [comment]
> > 应该是编码方式的问题，你的终端没有正确识别出中文，你可以在终端上尝试更改一下编码方式
> 
> how to handle it? I've tried many ways on the internet but still can't

你可以试一下，我不是很确定是否有用，这个命令是将windows系统cmd的编码方式改为utf-8
打开cmd，之后在命令行输入 "chcp 65001"

**Comment by radenhendriawan** [comment]
> 

already but it doesn't work

**Comment by radenhendriawan** [comment]
> Download Windows Terminal from Microsoft Store.

thank you, it looks like it really has to be from cmd because it never works when using powershell

**Comment by scribe2433** [comment]
> > Download Windows Terminal from Microsoft Store.
> 
> thank you, it looks like it really has to be from cmd because it never works when using powershell

Hi @radenhendriawan, if your problem is solved, please do close the issue. If possible, please share your steps to resolve this issue in the event that other people encounter a similar issue. Thanks!

**Comment by radenhendriawan** [comment]
this solved if using cmd, if using powershell it doesn't work
