### ISSUE TITLE
批量下载视频数量不全

### ISSUE THREAD

**Issue by zxcvbnl3** [Johnserf-Seed/TikTokDownload#46]
使用您的项目下载了几个用户发布的视频，发现实际下载数量比发布的总数量少了三分之一
![image](https://user-images.githubusercontent.com/65781330/129309930-bad51cb3-4642-4133-a5c7-ca939f3de506.png)

**Comment by Johnserf-Seed** [comment]
方便给一下用户主页的链接吗
另外重复的视频是不会下载的

**Comment by zxcvbnl3** [comment]
https://v.douyin.com/eoALJYU/ 
可能有重复视频我开始没注意，开发大大辛苦了

**Comment by Johnserf-Seed** [comment]
> https://v.douyin.com/eoALJYU/
> 可能有重复视频我开始没注意，开发大大辛苦了

这个可能还是存在一些问题，因为官方接口有时候会返回下一页空白的数据，程序目前只会检测一次 所以有些用户的视频可能会存在下不完整的情况。之后会重新写一下这块的逻辑

**Comment by zxcvbnl3** [comment]
好的，感谢
