### ISSUE TITLE
该用户未开放喜欢页，请开放后重新运行

### ISSUE THREAD

**Issue by htwdjqr** [Johnserf-Seed/TikTokDownload#466]
**描述出现的错误**
like模式下运行提示“该用户未开放喜欢页，请开放后重新运行!”，但是我的抖音设置已经将”主页喜欢列表“设置为公开可见。
而且重新注册了一个抖音账号也是一样的错误提示。不过在post模式下能正常下载视频文件。

**bug复现**
复现这次行为的步骤：
按照文档步骤操作，并且按需修改了conf.ini

**截图**
![16879230281892](https://github.com/Johnserf-Seed/TikTokDownload/assets/26807197/bf3509da-bd45-458f-bad6-0c3720f35b7e)
![1687924261367](https://github.com/Johnserf-Seed/TikTokDownload/assets/26807197/824522c1-fd7b-4bee-aa52-fb67ee1d74d9)

**桌面（请填写以下信息）：**
-操作系统：windows10 64bit
-vpn代理：关闭
-版本：最新

**Comment by hp2577** [comment]
我也有一样的问题

**Comment by Johnserf-Seed** [comment]
新版本解决了这个问题，马上更新了 还在测试
