### ISSUE TITLE
运行时，中文字成了问号

### ISSUE THREAD

**Issue by ksskskksks** [Johnserf-Seed/TikTokDownload#47]
在运行时，中文字成了这样，请问是我设置的问题吗？
![image](https://user-images.githubusercontent.com/70839932/129483087-225271fe-d066-4ac2-9397-2c1649e66536.png)

**Comment by Johnserf-Seed** [comment]
控制台的编码 是936 简体中文GBK，推荐使用windows terminal
解决办法：cmd输入命令 CHCP 936  或者65001

**Comment by Johnserf-Seed** [comment]
如果无法解决，那需要将py文件的编码转换成UTF-8(仓库文件是UTF-8，可能是你有编辑过改掉了它的编码)

**Comment by ksskskksks** [comment]
感谢，问题已经解决。 
还有个问题是批量下载时，抖音号的作品数和下载数不符，下载数量会少一些。

**Comment by Johnserf-Seed** [comment]
> 感谢，问题已经解决。
> 还有个问题是批量下载时，抖音号的作品数和下载数不符，下载数量会少一些。

由于官方api页面的特性，会有空白页面出现。这个问题会在将来修复

**Comment by ksskskksks** [comment]
> > 感谢，问题已经解决。
> > 还有个问题是批量下载时，抖音号的作品数和下载数不符，下载数量会少一些。
> 
> 由于官方api页面的特性，会有空白页面出现。这个问题会在将来修复

好的，谢谢回复。

**Comment by Johnserf-Seed** [comment]
> > > 感谢，问题已经解决。
> > > 还有个问题是批量下载时，抖音号的作品数和下载数不符，下载数量会少一些。
> > 
> > 
> > 由于官方api页面的特性，会有空白页面出现。这个问题会在将来修复
> 
> 好的，谢谢回复。

不用客气😊
