### ISSUE TITLE
[BUG] 14000版本的程序貌似会随机卡住 + 虽然程序进程完成了，但是有些抓取的文件并没有被完全下载

### ISSUE THREAD

**Issue by EsperantoP** [Johnserf-Seed/TikTokDownload#489]
**描述出现的错误**
遇到bug先在issues中搜索，没有得到解决方案再提交。
对出现bug的地方做清晰而简洁的描述。
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/81968849/bf872fd7-c1c6-4cd4-a77b-61863e1cccf7)
就卡住了，不会弹出“自动退出“啥的
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/81968849/aa63f4ab-0f0b-4bd8-bc2d-aad4d5d1230a)
这个文件传输就卡住了

**bug复现**
复现这次行为的步骤：
1.首先更改了什么什么
  升级程序版本至14000
  添加了新的依赖库

2. N/A

3. 在Bash里面运行../tiktoktool.py正常执行，但是会卡在抓取和下载这两个部分。

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/81968849/69939f3c-2469-4ecd-866e-ccd87188fa05)

**桌面（请填写以下信息）：**
-操作系统：[Windows 10 Pro]
-vpn代理：[关闭]
-项目版本：[1.4.0]
-py版本：[3.11.4]
-依赖库的版本：[我不到哇] [pyinstaller 5.7.0]

**附文**
请开发者看看这是啥问题呗 :P

**Comment by EsperantoP** [comment]
我是想说。。这是正常的吗？

**Comment by EsperantoP** [comment]
我好像知道了，这个可能是因为抖音或者我的根服务器抽风了，导致没有完全下载玩这些文件，所以这个东西才没有自动结束

**Comment by Johnserf-Seed** [comment]
和网络环境有关，任务队列是等待下载complete=1后完毕才会处理下一页的作品。所以没完成的作品程序就会一直等待。重新运行试试

**Comment by 071012Jackie** [comment]
> 
这个bug很神奇 对于某些博主的视频 重复下载确实还是会在同一地方报错，有的不会出现这个问题

**Comment by Johnserf-Seed** [comment]
> > 
> 
> 这个bug很神奇 对于某些博主的视频 重复下载确实还是会在同一地方报错，有的不会出现这个问题

你指的是什么类型的报错呢

**Comment by EsperantoP** [comment]
> 和网络环境有关，任务队列是等待下载complete=1后完毕才会处理下一页的作品。所以没完成的作品程序就会一直等待。重新运行试试

感谢解释 <3

**Comment by EsperantoP** [comment]
> 和网络环境有关，任务队列是等待下载complete=1后完毕才会处理下一页的作品。所以没完成的作品程序就会一直等待。重新运行试试

验证了一下，其实是现实错误（

**Comment by EsperantoP** [comment]
Conclusion: 显示错误
