### ISSUE TITLE
你好，请问可以增加某个话题的下载吗？

### ISSUE THREAD

**Issue by 3dian** [Johnserf-Seed/TikTokDownload#49]
比如我喜欢宠物，就可以下载#宠物 话题下的所有视频
非常感谢～

**Comment by Johnserf-Seed** [comment]
可以考虑加入

**Comment by wanghaisheng** [comment]
@Johnserf-Seed  实现了吗

**Comment by YinHjie** [comment]
同问，是否可以加一个根据关键字搜索爬取和下载视频

**Comment by Johnserf-Seed** [comment]
嘿，这个问题和我们在 [#421](https://github.com/users/Johnserf-Seed/projects/1/views/1?pane=issue&itemId=35037885) 的那个问题一样。为了让所有的讨论都在一个地方，我要把这个问题关闭了。去那边看看吧！
