### ISSUE TITLE
[BUG]TikTokLive闪退无法使用

### ISSUE THREAD

**Issue by cmpunk160** [Johnserf-Seed/TikTokDownload#491]
粘贴直播间web链接后到图示这一步后便闪退了，无法继续操作
![SharedScreenshot](https://github.com/Johnserf-Seed/TikTokDownload/assets/126212735/ec72d007-7410-4e51-bd11-0e75b9e6f23a)

**Comment by EsperantoP** [comment]
新的版本更新了log文件，把那个发出来看看

**Comment by Johnserf-Seed** [comment]
Live模块在1.4.0版本中还没更新，等我推送
