### ISSUE TITLE
[BUG]无桌面环境ubuntu，无法显示二维码，是否可以添加手动添加cookies功能

### ISSUE THREAD

**Issue by tanmx** [Johnserf-Seed/TikTokDownload#495]
**描述出现的错误**
无法显示二维码

**bug复现**
复现这次行为的步骤：
1.创建 test.py
```
import Util

if __name__ == '__main__':
	# 获取命令行和配置文件
	cmd = Util.Command()
	config = cmd.config_dict
	dyheaders = cmd.dyheaders

	# 异步下载作品
	Util.asyncio.run(Util.Profile(config, dyheaders).get_Profile())
	input("[  提示  ]:下载完成，输入任意键退出。")
```
2.运行 test.py
```
# python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import Util
  File "/root/TikTokDownload/Util/__init__.py", line 70, in <module>
    from .Login import *
  File "/root/TikTokDownload/Util/Login.py", line 103
    match status:
          ^
SyntaxError: invalid syntax
```

**桌面（请填写以下信息）：**
-操作系统：ubuntu 20.04 lts
-项目版本：1.4.0
-py版本：3.8.10

**附文**
报错原因：在无桌面环境中 无法弹出二维码
```
        # 创建QR码图像
        qr_code_img = Util.qrcode.make(qrcode_url)

        # 显示QR码图像
        qr_code_img.show()

        Util.console.print("[  登录  ]:请扫描弹出的登录二维码。\r")
        Util.log.info("[  登录  ]:请扫描弹出的登录二维码。")
```

是否可以在命令行展示二维码或者提供开关自己在配置文件中设置 cookie ?

**Comment by Johnserf-Seed** [comment]
配置了cookie就不会要求扫码登录了

**Comment by tanmx** [comment]
> 配置了cookie就不会要求扫码登录了

你好，我在 conf.ini 配置了 cookie = xxxxxx
然后执行 python test.py 依旧报错
![iShot_2023-08-07_14.25.04.png](https://s2.loli.net/2023/08/07/xfgQwpHeFY9mZ6r.png)

**Comment by Johnserf-Seed** [comment]
py版本是3.11.1

**Comment by tanmx** [comment]
> py版本是3.11.1
好的 我在vps 更新一下 py，谢谢

**Comment by Alexo88** [comment]
> > 配置了cookie就不会要求扫码登录了
> 
> 你好，我在 conf.ini 配置了 cookie = xxxxxx 然后执行 python test.py 依旧报错 ![iShot_2023-08-07_14.25.04.png](https://camo.githubusercontent.com/3d5073e3f3ab46d238671d201c641977d15235da0708681b0cacc96c4aeeb0fd/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30382f30372f78666751777048654659396d5a36722e706e67)

how you add cookies?? which program?

**Comment by Johnserf-Seed** [comment]
> > > 配置了cookie就不会要求扫码登录了
> > 
> > 
> > 你好，我在 conf.ini 配置了 cookie = xxxxxx 然后执行 python test.py 依旧报错 ![iShot_2023-08-07_14.25.04.png](https://camo.githubusercontent.com/3d5073e3f3ab46d238671d201c641977d15235da0708681b0cacc96c4aeeb0fd/68747470733a2f2f73322e6c6f6c692e6e65742f323032332f30382f30372f78666751777048654659396d5a36722e706e67)
> 
> how you add cookies?? which program? i mean how you get cookies and what format.

use the "Developer Tool F12" that comes with the browser and find the domain of douyin.com in the network tab. The response header will contain the value of the cookie.
just like this
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/9742e9e1-05e5-4365-b384-c7faa8be4933)
