### ISSUE TITLE
能下载tiktok作品吗

### ISSUE THREAD

**Issue by ppptttttt** [Johnserf-Seed/TikTokDownload#50]
重编：知道不能下了
不知道怎么删贴

**Comment by Johnserf-Seed** [comment]
未来即将更新海外版的下载功能，并推出GUI界面

**Comment by Johnserf-Seed** [comment]
> 

Your suggestion is very good. The foreign version of tiktok will soon join the support. At present, it has been updated to version 1.2.5. If you allow, you can launch PR for this repository😀

**Comment by Evil0ctal** [comment]
> 重编：知道不能下了 不知道怎么删贴

你好，我的仓库支持TikTok，但是目前仅支持手动保存无水印视频，无法实现批量下载，有需要的话可以看一下。
仓库：
https://github.com/Evil0ctal/Douyin_TikTok_Download_API
