### ISSUE TITLE
小白请问如何安装运行起项目？

### ISSUE THREAD

**Issue by yik7707** [Johnserf-Seed/TikTokDownload#500]
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/74293458/a905fe5c-5e6e-4400-8820-3bc531fc810c)
安装环境已经准备好
1.如上图，这里安装/Installation命令是全部复制上去也不对，这里安装命令这里不是很了解，有了解的大神吗？
2.运行py是使用idea运行的吗

**Comment by bxiaoj** [comment]
> ![image](https://user-images.githubusercontent.com/74293458/259356225-a905fe5c-5e6e-4400-8820-3bc531fc810c.png) 安装环境已经准备好 1.如上图，这里安装/Installation命令是全部复制上去也不对，这里安装命令这里不是很了解，有了解的大神吗？ 2.运行py是使用idea运行的吗

[video-parser](https://github.com/bxiaoj/video-parser/), may be able to help you solve the problem, worth trying.
