### ISSUE TITLE
[BUG] 程序在某个节点就会卡住，无报错，只是程序不动弹了也不刷新了

### ISSUE THREAD

**Issue by EsperantoP** [Johnserf-Seed/TikTokDownload#511]
**描述出现的错误**
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/81968849/b7b5ed4b-8a89-467f-8443-8b471bf80754)

**bug复现**
复现这次行为的步骤：
#510 
看这里！！！（下面这个是图片）
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/81968849/eeb00642-6aea-4a6d-85fc-deb94b557c3a)

**桌面（请填写以下信息）：**
-操作系统：[Windows 10 Pro]
-vpn代理：[关闭]
-项目版本：[1.4.0]
-py版本：[3.11.4]
-依赖库的版本：
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/81968849/0291608c-0002-45dd-952a-23777ee0ef64)

**附文**
这回莫得Log了，因为根本就不报错..我觉得好像是程序在运行的中，但是被卡住了？

**Comment by Johnserf-Seed** [comment]
server.bat现在不需要单独运行了，保留它是为了方便本地调用接口。 这个问题我本地测试的时候极少数碰到过，进程好像是阻塞了

**Comment by EsperantoP** [comment]
> server.bat现在不需要单独运行了，保留它是为了方便本地调用接口。 这个问题我本地测试的时候极少数碰到过，进程好像是阻塞了

我也尝试了单独运行tiktoktool.py，或许是进程堵塞造成的，但是不知道通过什么方法解决…目前我觉得最有效的方法是等，过一段时间就好了。非常得玄学

**Comment by Johnserf-Seed** [comment]
新版加入了并发和异步任务的配置 可以自己调节，等推送再测试看看
