### ISSUE TITLE
[BUG]1.4.0版本运行TikTokTool.py文件，异常 string index out of range

### ISSUE THREAD

**Issue by fangyingwu** [Johnserf-Seed/TikTokDownload#513]
**描述出现的错误**
1.4.0版本运行TikTokTool.py文件，异常 string index out of range,具体如下：
[  提示  ]:异常，string index out of range
[2023-08-15 15:05:17,826] - Log.py] - ERROR: [  提示  ]:异常，string index out of range

**bug复现**

**截图**
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/35124617/595a7f13-66ff-45fb-8750-66fee93b6176)

**桌面（请填写以下信息）：**
-操作系统：[例如MacOS]
-vpn代理：[例如关闭]
-项目版本：[如1.4.0]
-py版本：[如3.11.2]
-依赖库的版本：[出错的库版本号]

**附文**
在此处添加有关此问题的其他备注。

**Comment by EsperantoP** [comment]
啊？解决了这是？请问这是咋整的？
