### ISSUE TITLE
作者不知道什么情况，扫码之后就不动了，环境一切都没有问题，不知道什么情况

### ISSUE THREAD

**Issue by GEM123668** [Johnserf-Seed/TikTokDownload#516]
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/121158914/051722da-21e5-431d-8614-c5e7c2507bfb)

**Comment by Johnserf-Seed** [comment]
有别的issue说换一个抖音号扫码可以成功，我还没验证过原因。如果后续没有提示登录重定向成功的话可以多尝试几次看看是否被风控了

**Comment by GEM123668** [comment]
使用更新以后的版本一切正常

**Comment by 6986552** [comment]
这个问题我也遇到过，后面就又可以了，可能是我前面那几次等的时间不够长，或者真的多试了几次就好了。
