### ISSUE TITLE
[BUG]用户作品只有一页时，会进入死循环

### ISSUE THREAD

**Issue by qingxuezhushang** [Johnserf-Seed/TikTokDownload#517]
**描述出现的错误**
用户作品只有一页时，会进入死循环。
只有一页作品，self.has_more为0，但不为空

**bug复现**
测试uid：https://www.douyin.com/user/MS4wLjABAAAAWqKYet-t7TP1qAjQpeF8oCQ3H90dPCYk2JrEnteMNlY

**截图**
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/49868326/e93d11a6-2d0d-47e4-9c52-5badf3067778)

**Comment by Johnserf-Seed** [comment]
是的，因为接口返回数量不是固定的 has_more=0的时候依然有作品 我考虑到了这一点但是此前代码这一环没测试出来。新的提交已经修复但未推送，我修复完几个issue一起推送。
