### ISSUE TITLE
[Problem] 图片类的文件有概率不会被程序等待至其下载完毕

### ISSUE THREAD

**Issue by EsperantoP** [Johnserf-Seed/TikTokDownload#519]
**描述出现的错误**
在 PullRequest #506  里面确保了文件通过异步下载的完整性。但是，貌似是针对视频做的改进；或者说图片类的文件有概率不会被程序等待至其下载完毕

**bug复现**
复现这次行为的步骤：
更新至14200
运行./tiktoktool.py
//问题显现

**桌面（请填写以下信息）：**
-操作系统：[Windows 10 Pro]
-vpn代理：[关闭]
-项目版本：[1.4.2.0]
-py版本：[3.11.4]
-依赖库的版本：
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/81968849/066031df-44e3-4382-af32-a78e136461f7)

**Comment by EsperantoP** [comment]
我去。。我刚才又试了一下，好了。。。
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/81968849/f164cf49-82ba-4850-82a7-9ee6384d6745)
我更改了一下Windows terminal的窗口大小。。然后就好了（？）这么玄学的吗？

**Comment by Johnserf-Seed** [comment]
> 我去。。我刚才又试了一下，好了。。。 ![image](https://user-images.githubusercontent.com/81968849/261594385-f164cf49-82ba-4850-82a7-9ee6384d6745.png) 我更改了一下Windows terminal的窗口大小。。然后就好了（？）这么玄学的吗？

是本地的网络波动问题 和服务器风控也有关系

**Comment by EsperantoP** [comment]
> > 我去。。我刚才又试了一下，好了。。。 ![image](https://user-images.githubusercontent.com/81968849/261594385-f164cf49-82ba-4850-82a7-9ee6384d6745.png) 我更改了一下Windows terminal的窗口大小。。然后就好了（？）这么玄学的吗？
> 
> 是本地的网络波动问题 和服务器风控也有关系

OK, 感谢解答
