### ISSUE TITLE
PROBLEM WITH conf.ini

### ISSUE THREAD

**Issue by thanhtuvietnam** [Johnserf-Seed/TikTokDownload#52]
Hi sir, i changed all the module inside conf.ini but it's still downloading videos from your default link. Help me, please!!!

**Comment by Johnserf-Seed** [comment]
Can you provide the contents of conf.ini

**Comment by thanhtuvietnam** [comment]
[url]	
#用户主页
uid = https://vt.tiktok.com/ZSJKgM5AP/

[music]	
#音频下载
musicarg = yes

[count]	
#单页下载个数 Max = 35 （无需改动）
count = 10

[save]	
#保存位置 你喜欢的名字
url = .\Download\

[mode]
#下载模式选择 like为点赞 post为发布
mode = post

**Comment by thanhtuvietnam** [comment]
Here sir, pleased to have your reply

**Comment by Johnserf-Seed** [comment]
> [url]
> #用户主页
> uid = https://vt.tiktok.com/ZSJKgM5AP/
> 
> [music]
> #音频下载
> musicarg = yes
> 
> [count]
> #单页下载个数 Max = 35 （无需改动）
> count = 10
> 
> [save]
> #保存位置 你喜欢的名字
> url = .\Download\
> 
> [mode]
> #下载模式选择 like为点赞 post为发布
> mode = post

Sorry, the current version does not support the overseas version of tiktok, but only the Chinese version ><

**Comment by thanhtuvietnam** [comment]
[url]	
#用户主页
uid = https://v.douyin.com/dh9mJws/

[music]	
#音频下载
musicarg = yes

[count]	
#单页下载个数 Max = 35 （无需改动）
count = 35

[save]	
#保存位置 你喜欢的名字
url = .\Download\

[mode]
#下载模式选择 like为点赞 post为发布
mode = post

**Comment by thanhtuvietnam** [comment]
here i try to switch on douyin, but it's still not working

**Comment by Johnserf-Seed** [comment]
If you open the agent tool on your computer, please try closing it first

**Comment by thanhtuvietnam** [comment]
it's great! i did it, thanks sir. Wish to have an oversea version in the future

**Comment by Johnserf-Seed** [comment]
now has been updated to 1.2.5😎
