### ISSUE TITLE
[BUG] 程序报错：异常，运行异常, 异常:

### ISSUE THREAD

**Issue by EsperantoP** [Johnserf-Seed/TikTokDownload#520]
**描述出现的错误**
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/81968849/c5b46996-084f-4195-8132-c5ee547e67e5)

**bug复现**
复现这次行为的步骤：
升级至14200
运行./tiktoktool.py
正常运行后报错

**桌面（请填写以下信息）：**
-操作系统：[Windows 10 Pro]
-vpn代理：[关闭]
-项目版本：[1.4.2]
-py版本：[3.11.4]
-依赖库的版本：
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/81968849/4c65e42b-3222-4300-b721-619020bc439c)

**附文**
[2023-08-18_122526.log](https://github.com/Johnserf-Seed/TikTokDownload/files/12378792/2023-08-18_122526.log)
基本上是什么信息都没给吧，就直接异常了 D:

**Comment by Johnserf-Seed** [comment]
aiohttp.ClientError() 为客户端报错所以没其他信息，是本地网络问题

**Comment by EsperantoP** [comment]
> aiohttp.ClientError() 为客户端报错所以没其他信息，是本地网络问题

感谢解答
