### ISSUE TITLE
[BUG]interval这个配置参数我按照格式配置了，如：interval = 2023-08-01|2023-09-01 可是还是下载全部的，这参数到底应该怎么配置呢

### ISSUE THREAD

**Issue by liu779900** [Johnserf-Seed/TikTokDownload#521]
**描述出现的错误**
遇到bug先在issues中搜索，没有得到解决方案再提交。
对出现bug的地方做清晰而简洁的描述。

**bug复现**
复现这次行为的步骤：
1.首先更改了什么什么
2.点击了什么什么
3.“……”

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]
-vpn代理：[例如开启、关闭]
-项目版本：[如1.4.2.2]
-py版本：[如3.11.1]
-依赖库的版本：[出错的库版本号]

**附文**
在此处添加有关此问题的其他备注。

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/5a445b87-1f5d-4749-b691-5479b14b4982)
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/2a84ad16-83a5-4c3a-9393-f219cb1beef7)
实测没问题，你修改完配置文件后保存了吗

**Comment by liu779900** [comment]
从新下载新版本，删除旧版本，问题解决
