### ISSUE TITLE
异常，本地网络请求异常。 异常: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8',  url=URL('https://www.douyin.com/aweme/v1/web/user/profile/other/?device_platform=webapp&aid=6383&sec_user_id=MS4wLjABAAAA4vgRHGrSG6rPlffm3RvwHWL8TBq7O4YnM5jHUNXz0-s&cookie_enabled=true& platform=PC&downlink=10&X-Bogus=DFSzswVuSYhANxXhtyf4ql9WX7J-')

### ISSUE THREAD

**Issue by Hkxuan** [Johnserf-Seed/TikTokDownload#532]
**描述出现的错误**
遇到bug先在issues中搜索，没有得到解决方案再提交。
对出现bug的地方做清晰而简洁的描述。

**bug复现**
复现这次行为的步骤：
1.首先更改了什么什么
2.点击了什么什么
3.“……”

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]
-vpn代理：[例如开启、关闭]
-项目版本：[如1.4.2.2]
-py版本：[如3.11.1]
-依赖库的版本：[出错的库版本号]

**附文**
在此处添加有关此问题的其他备注。

**Comment by Johnserf-Seed** [comment]
如题
