### ISSUE TITLE
[BUG ]现在mod选“like”的时候，已经不能下载了，返回None，直接在程序里报错“'NoneType' object is not iterable”。 另外，在界面点赞是“like”还是“favorite”？在主页面显示的“喜欢”mod是用like吗？如果是“like”，那链接估计换了

### ISSUE THREAD

**Issue by xj75q** [Johnserf-Seed/TikTokDownload#533]
**描述出现的错误**
现在mod选“like”的时候，已经不能下载了，返回None，直接在程序里报错“'NoneType' object is not iterable”。
另外，在界面点赞是“like”还是“favorite”？在主页面显示的“喜欢”mod是用like吗？如果是“like”，那链接估计换了

**bug复现**
复现这次行为的步骤：
1.手动在conf.ini里面改了mode = post为  like，listcollection;
2.运行python  TikTokTool.py;
3.当mode设置为like的时候，不能出现上述错误,其余两个模式下载正常

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。
```
  提示  ]:异常，'NoneType' object is not iterable
[2023-09-01 12:59:19,200] - Log.py] - ERROR: [  提示  ]:异常，'NoneType' object is not iterable，Traceback (most recent call last):
  File "/home/TikTokDownload/Util/Profile.py", line 481, in get_Profile
    aweme_data = await self.get_user_post_info(self.headers, self.profile_URL)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/TikTokDownload/Util/Profile.py", line 358, in get_user_post_info
    for item in aweme_list:
TypeError: 'NoneType' object is not iterable

```

**桌面（请填写以下信息）：**
-操作系统：linux-x64
-vpn代理：关闭
-项目版本：最新
-py版本：3.11.2
-依赖库的版本：[出错的库版本号]

**Comment by Johnserf-Seed** [comment]
刚刚测过了，没问题哦

**Comment by Johnserf-Seed** [comment]
mode配置只是给用户选择的

**Comment by Johnserf-Seed** [comment]
贴报错的话请按照issue的格式要求写，你这个描述我无法定位问题

**Comment by xj75q** [comment]
修改了格式重新填写了。在linux系统下执行的

**Comment by xj75q** [comment]
> 如果你填的用户主页没有开放喜欢 那就无法下载

你的conf里提到这两句话：
- 下载他人喜欢页、收藏视频请确保是开放所有人可见
- 如果是扫码登陆的下载自己的喜欢与收藏则无需设置所有人可见

我是下载的我自己的抖音主页，自己的主页设置的“仅自己可见”，但是在win和linux下都试过了，都会出现None这个问题。而且当在手机里进入设置界面，把自己的“喜欢”更改为“公开可见”，还是出现同样的问题，都是返回None。你可以换台别人的电脑试一下，是不是你用的代码不是main代码，而是其他分支的代码？

**Comment by Johnserf-Seed** [comment]
> > 如果你填的用户主页没有开放喜欢 那就无法下载
> 
> 你的conf里提到这两句话：
> 
> * 下载他人喜欢页、收藏视频请确保是开放所有人可见
> * 如果是扫码登陆的下载自己的喜欢与收藏则无需设置所有人可见
> 
> 我是下载的我自己的抖音主页，自己的主页设置的“仅自己可见”，但是在win和linux下都试过了，都会出现None这个问题。而且当在手机里进入设置界面，把自己的“喜欢”更改为“公开可见”，还是出现同样的问题，都是返回None。你可以换台别人的电脑试一下，是不是你用的代码不是main代码，而是其他分支的代码？

你前面并没有提到是自己的喜欢页，如果是自己的喜欢页只要登录了自己的cookie就可以下载了

**Comment by Johnserf-Seed** [comment]
有关喜欢页下载失败的近期只有你的issue，所以你需要这样检查
1. 删除配置文件中```cookie```的值并确保是最新的代码
2. 检查网页端自己的喜欢页是否可以正常查看
3. 重新扫码登录自己的账号，并将```mode```修改为```like```,```interval```为```all```
4. 重新运行TikTokTool
5. 如果继续报错请提供log文件

**Comment by xj75q** [comment]
> > > 如果你填的用户主页没有开放喜欢 那就无法下载
> > 
> > 
> > 你的conf里提到这两句话：
> > 
> > * 下载他人喜欢页、收藏视频请确保是开放所有人可见
> > * 如果是扫码登陆的下载自己的喜欢与收藏则无需设置所有人可见
> > 
> > 我是下载的我自己的抖音主页，自己的主页设置的“仅自己可见”，但是在win和linux下都试过了，都会出现None这个问题。而且当在手机里进入设置界面，把自己的“喜欢”更改为“公开可见”，还是出现同样的问题，都是返回None。你可以换台别人的电脑试一下，是不是你用的代码不是main代码，而是其他分支的代码？
> 
> 你前面并没有提到是自己的喜欢页，如果是自己的喜欢页只要登录了自己的cookie就可以下载了

cookie是正确的。是扫码登录自动保存到conf.ini里的cookie，但是在linux和win下都会出现None的错误。我今天已经被限制IP了（太快和频繁运行就会被禁止ip，可以加个sleep）。还有我发现如果是文件名称太长，就是“丢弃”此文件而不保存。所以我在fork里面增加了desc缩短字段的逻辑

**Comment by Johnserf-Seed** [comment]
> > > > 如果你填的用户主页没有开放喜欢 那就无法下载
> > > 
> > > 
> > > 你的conf里提到这两句话：
> > > 
> > > * 下载他人喜欢页、收藏视频请确保是开放所有人可见
> > > * 如果是扫码登陆的下载自己的喜欢与收藏则无需设置所有人可见
> > > 
> > > 我是下载的我自己的抖音主页，自己的主页设置的“仅自己可见”，但是在win和linux下都试过了，都会出现None这个问题。而且当在手机里进入设置界面，把自己的“喜欢”更改为“公开可见”，还是出现同样的问题，都是返回None。你可以换台别人的电脑试一下，是不是你用的代码不是main代码，而是其他分支的代码？
> > 
> > 
> > 你前面并没有提到是自己的喜欢页，如果是自己的喜欢页只要登录了自己的cookie就可以下载了
> 
> cookie是正确的。是扫码登录自动保存到conf.ini里的cookie，但是在linux和win下都会出现None的错误。我今天已经被限制IP了（太快和频繁运行就会被禁止ip，可以加个sleep）。还有我发现如果是文件名称太长，就是“丢弃”此文件而不保存。所以我在fork里面增加了desc缩短字段的逻辑

sleep会阻塞异步，不宜添加 修改并发和任务数即可。方便的话提供一下你的主页我测试一下

**Comment by xj75q** [comment]
> 

git@github.com:xj75q/TikTokDownload.git  我是fork的你的，你那里应该会有提醒吧……

**Comment by Johnserf-Seed** [comment]
为何要先质疑推送了这么久的仓库代码问题？ 我测试了功能一切正常，None就是因为response内容是空的所以报错，你也说了你ip被ban了那答案不是已经有了吗。

**Comment by xj75q** [comment]
> 有关喜欢页下载失败的近期只有你的issue，所以你需要这样检查
> 
> 1. 删除配置文件中`cookie`的值并确保是最新的代码
> 2. 检查网页端自己的喜欢页是否可以正常查看
> 3. 重新扫码登录自己的账号，并将`mode`修改为`like`,`interval`为`all`
> 4. 重新运行TikTokTool
> 5. 如果继续报错请提供log文件


新拉的代码，重新登录的，以下是截图，这个问题出现在ip被ban之前。我只下载了我收藏夹里的代码，“喜欢”列表里并下载不了

![20230901203525](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/88369e3b-e16e-4f6d-82c8-bb9372972f9d)
![20230901203549](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/87e230d6-9d8d-4b7c-94e1-f9585628dc50)
![20230901203629](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/2ef27717-b194-4546-b6fc-8c8532ebd7e5)
![20230901203804](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/3f113389-1527-4133-95e5-230a426d69ad)
![20230901203846](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/39ea7d34-3749-48c0-b36b-5db8cda3a1cb)
![20230901204000](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/c4caed70-541d-4fba-a5eb-167eb5108195)
![20230901204102](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/4bf01307-0dda-4d26-92c7-a1cc2d3a7006)

**Comment by Johnserf-Seed** [comment]
> 

![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/2e505d5f-5592-4344-8d83-28711a4f6489)
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/b1777db8-a1f0-437f-a2b3-df99c702b784)
符合无可置疑原则，你的本地网络环境问题，非代码问题

**Comment by joostshao** [comment]
> > 有关喜欢页下载失败的近期只有你的issue，所以你需要这样检查
> > 
> > 1. 删除配置文件中`cookie`的值并确保是最新的代码
> > 2. 检查网页端自己的喜欢页是否可以正常查看
> > 3. 重新扫码登录自己的账号，并将`mode`修改为`like`,`interval`为`all`
> > 4. 重新运行TikTokTool
> > 5. 如果继续报错请提供log文件
> 
> 新拉的代码，重新登录的，以下是截图，这个问题出现在ip被ban之前。我只下载了我收藏夹里的代码，“喜欢”列表里并下载不了
> 
> ![20230901203525](https://user-images.githubusercontent.com/29592219/265023301-88369e3b-e16e-4f6d-82c8-bb9372972f9d.jpg) ![20230901203549](https://user-images.githubusercontent.com/29592219/265023416-87e230d6-9d8d-4b7c-94e1-f9585628dc50.jpg) ![20230901203629](https://user-images.githubusercontent.com/29592219/265023424-2ef27717-b194-4546-b6fc-8c8532ebd7e5.jpg) ![20230901203804](https://user-images.githubusercontent.com/29592219/265023440-3f113389-1527-4133-95e5-230a426d69ad.jpg) ![20230901203846](https://user-images.githubusercontent.com/29592219/265023447-39ea7d34-3749-48c0-b36b-5db8cda3a1cb.jpg) ![20230901204000](https://user-images.githubusercontent.com/29592219/265023456-c4caed70-541d-4fba-a5eb-167eb5108195.jpg) ![20230901204102](https://user-images.githubusercontent.com/29592219/265023457-4bf01307-0dda-4d26-92c7-a1cc2d3a7006.jpg)

**Comment by joostshao** [comment]
是不是listcollection收藏的没有开放？ 我的也是，或者我的账户是私密账户。

**Comment by Johnserf-Seed** [comment]
> 是不是listcollection收藏的没有开放？ 我的也是，或者我的账户是私密账户。

不是，因为符合无可置疑原则

**Comment by joostshao** [comment]
我开放了收藏，貌似还是一样，是不是ip被ratelimit了?

**Comment by Johnserf-Seed** [comment]
> 我开放了收藏，貌似还是一样，是不是ip被ratelimit了?

登录了自己的账号是不需要开放喜欢或者收藏就可以下载的，出现这种情况只能是网络或者账号问题。如果网页端可以正常打开那么就是网络问题，具体的原因未知。

**Comment by xj75q** [comment]
> 



> > 我开放了收藏，貌似还是一样，是不是ip被ratelimit了?
> 
> 登录了自己的账号是不需要开放喜欢或者收藏就可以下载的，出现这种情况只能是网络或者账号问题。如果网页端可以正常打开那么就是网络问题，具体的原因未知。

一般账号被限要多少天才能恢复正常？我的网络是没有问题的，但是账号经常切换设备登录，不是在一台设备上的。网页上是可以访问的，在网页上也能看“喜欢”的内容，网络是没有问题的。 我感觉有可能是账号问题……
