### ISSUE TITLE
[BUG] None出现在IP被ban之前……你关闭了上一个issue，我只能把截图放到这个新的里面了

### ISSUE THREAD

**Issue by xj75q** [Johnserf-Seed/TikTokDownload#534]
新拉取的你的代码做测试。那个None出现在IP被ban之前。由于like一直不能出现None，我不能下载，我只下载了“post”和“listcollection”页里面。那个“desc”文件名问题，也是我在下载“listcollection”的时候发现的。在下午5-6点钟才被ban的ip。这个None是出现在ip被ban之前的：

以下是新的测试截图，log日志里也是出现了这个问题。另外，IP被ban，会出现一段短短的提示。

![20230901203525](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/edf67cf5-3b84-443f-87c1-c3f1e9bfc7cc)

![20230901203549](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/1305312a-92ef-41cd-8359-98ba6f719188)
![20230901203629](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/fb112fb6-3275-465f-8b74-651f8226e48b)
![20230901203804](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/b3bab6a3-adb7-43b3-9532-ce1b85717c4e)
![20230901203846](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/12dce77d-1392-44fa-9383-f03ccdac349f)
![20230901204000](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/f5c6ab17-9381-4bf5-aa7f-e64c91ad2c5b)
![20230901204102](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/9077a542-daf8-47ba-a970-399d0c870c9f)

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/f575fec0-12b3-4955-acbc-9b57aaf3fd11)
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/ad549055-07de-4799-b7f2-2cbf2b8d842b)
┑(¬‿¬) ┍

**Comment by xj75q** [comment]
我换了手机网络，依然是这个问题
以下是我换的手机网络：
![20230901210235](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/b1307cd1-d557-48b8-9dd1-8ea5ebc5d05c)
![20230901210524](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/114b1a10-d46d-4720-91da-9c48b616922f)

![20230901210606](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/9dc18a0e-543a-417d-a570-7e527fae9294)

**Comment by Johnserf-Seed** [comment]
那就得考虑是否是账号问题，你是程序员你应该会调试。手头环境如果没有ide的话就在报错的这几个异常处print一下这几个变量，答案就有了

**Comment by Johnserf-Seed** [comment]
为什么需要你逆向呢，我只是需要你调试的内容。关键的输出```aweme_list```你没有截下来，打印aweme_data的位置都没开始赋值当然是空的，你给我看它没用啊

**Comment by xj75q** [comment]
> 为什么需要你逆向呢，我只是需要你调试的内容。关键的输出`aweme_list`你没有截下来，打印`aweme_data`的位置都没开始赋值当然是空的，你给我看它没用啊

aweme_list在like模式下是None，也就是我一直提的这个报错；在post模式下是可以下载下来的，以下是最新截图：

![20230901213512](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/e061e1c8-41c7-4924-beaf-f67c52676468)
![20230901213613](https://github.com/Johnserf-Seed/TikTokDownload/assets/29592219/c23138a9-866b-468c-8a85-445aa9a2d92b)

**Comment by Johnserf-Seed** [comment]
> > 为什么需要你逆向呢，我只是需要你调试的内容。关键的输出`aweme_list`你没有截下来，打印`aweme_data`的位置都没开始赋值当然是空的，你给我看它没用啊
> 
> aweme_list在like模式下是None，也就是我一直提的这个报错；在post模式下是可以下载下来的，以下是最新截图：
> 
> ![20230901213512](https://user-images.githubusercontent.com/29592219/265036297-e061e1c8-41c7-4924-beaf-f67c52676468.jpg) ![20230901213613](https://user-images.githubusercontent.com/29592219/265036307-c23138a9-866b-468c-8a85-445aa9a2d92b.jpg)

None是接口返回的。总结为下面几个原因造成的
1. XB参数与ua对不上，本issue中可能性 0%
2. 代码问题，本issue中可能性 0%
3. 网络环境异常，本issue中可能性 40%
4. 账号被风控，本issue中可能性10%
5. 接口链接构造问题，本issue中可能性 0%
6. 配置文件的cookie格式不对，本issue中可能性 10%

请自行排查，所有的建议给你了。项目代码是没有问题的。

**Comment by Johnserf-Seed** [comment]
> > > 为什么需要你逆向呢，我只是需要你调试的内容。关键的输出`aweme_list`你没有截下来，打印`aweme_data`的位置都没开始赋值当然是空的，你给我看它没用啊
> > 
> > 
> > aweme_list在like模式下是None，也就是我一直提的这个报错；在post模式下是可以下载下来的，以下是最新截图：
> > ![20230901213512](https://user-images.githubusercontent.com/29592219/265036297-e061e1c8-41c7-4924-beaf-f67c52676468.jpg) ![20230901213613](https://user-images.githubusercontent.com/29592219/265036307-c23138a9-866b-468c-8a85-445aa9a2d92b.jpg)
> 
> None是接口返回的。总结为下面几个原因造成的
> 
> 1. XB参数与ua对不上，本issue中可能性 0%
> 2. 代码问题，本issue中可能性 0%
> 3. 网络环境异常，本issue中可能性 40%
> 4. 账号被风控，本issue中可能性10%
> 5. 接口链接构造问题，本issue中可能性 0%
> 6. 配置文件的cookie风控，本issue中可能性 10%
> 
> 请自行排查，所有的建议给你了。项目代码是没有问题的。

**Comment by xj75q** [comment]
> > > > 为什么需要你逆向呢，我只是需要你调试的内容。关键的输出`aweme_list`你没有截下来，打印`aweme_data`的位置都没开始赋值当然是空的，你给我看它没用啊
> > > 
> > > 
> > > aweme_list在like模式下是None，也就是我一直提的这个报错；在post模式下是可以下载下来的，以下是最新截图：
> > > ![20230901213512](https://user-images.githubusercontent.com/29592219/265036297-e061e1c8-41c7-4924-beaf-f67c52676468.jpg) ![20230901213613](https://user-images.githubusercontent.com/29592219/265036307-c23138a9-866b-468c-8a85-445aa9a2d92b.jpg)
> > 
> > 
> > None是接口返回的。总结为下面几个原因造成的
> > 
> > 1. XB参数与ua对不上，本issue中可能性 0%
> > 2. 代码问题，本issue中可能性 0%
> > 3. 网络环境异常，本issue中可能性 40%
> > 4. 账号被风控，本issue中可能性10%
> > 5. 接口链接构造问题，本issue中可能性 0%
> > 6. 配置文件的cookie风控，本issue中可能性 10%
> > 
> > 请自行排查，所有的建议给你了。项目代码是没有问题的。

好的，我都试一下。我明天再换个网络环境。另外，我也新注册个账号，也试一下。如果有问题，再提新的issue
