### ISSUE TITLE
[HELP] stuck in the middle when downloading

### ISSUE THREAD

**Issue by radenhendriawan** [Johnserf-Seed/TikTokDownload#536]
how to solve this, downloads a lot but stops in the middle and doesn't want to download again
- I downloaded 1 full profile containing 8000 videos with an average duration of 10-20 seconds, after 1800 videos were downloaded that's what happened. I've refreshed and completed the captcha again but there is no change.

do I have to log in to solve this problem?

Thank you in advance, this tool really helped me a lot
![Screenshot_2](https://github.com/Johnserf-Seed/TikTokDownload/assets/132964012/f661a00d-7d1a-4c93-a93e-5066bf348bb0)

**Comment by stupiding** [comment]
@radenhendriawan  how do you fix that?
