### ISSUE TITLE
运行时报错，链接正确，不清楚如何解决

### ISSUE THREAD

**Issue by tfeather4** [Johnserf-Seed/TikTokDownload#55]
Win10系统，确认链接没有问题，直接闪退

**Comment by tfeather4** [comment]
![011047](https://user-images.githubusercontent.com/19702690/133127503-341ce0f0-c8d1-44b3-8cbf-4182acbd7ce4.png)

**Comment by Johnserf-Seed** [comment]
请确认电脑端没有运行任何代理软件

**Comment by tfeather4** [comment]
果然是代理，谢谢，软件很棒
