### ISSUE TITLE
安装过程中遇到问题

### ISSUE THREAD

**Issue by SingleRottenChips** [Johnserf-Seed/TikTokDownload#57]
大佬你好，感谢你的开发。

我是零基础小白，安装了 python 和 pip 之后，再安装 TikTokDownload 显示如下图：
<img width="1115" alt="微信截图_20211001054509" src="https://user-images.githubusercontent.com/63144489/135534357-18f7f594-d80d-42e2-91f2-c625d5fe28d5.png">

然而我找不到TikTokDownload.exe文件，请问这个安装过程出现了什么问题吗？
万分感谢！

**Comment by SingleRottenChips** [comment]
拜托大佬看看我帮帮我┭┮﹏┭┮

**Comment by Johnserf-Seed** [comment]
> 大佬你好，感谢你的开发。
> 
> 我是零基础小白，安装了 python 和 pip 之后，再安装 TikTokDownload 显示如下图： <img alt="微信截图_20211001054509" width="1115" src="https://user-images.githubusercontent.com/63144489/135534357-18f7f594-d80d-42e2-91f2-c625d5fe28d5.png">
> 
> 然而我找不到TikTokDownload.exe文件，请问这个安装过程出现了什么问题吗？ 万分感谢！

首先将本仓库藏龙阁到本地之后，在文件目录中再次尝试一下看看

**Comment by Johnserf-Seed** [comment]
> 大佬你好，感谢你的开发。
> 
> 我是零基础小白，安装了 python 和 pip 之后，再安装 TikTokDownload 显示如下图： <img alt="微信截图_20211001054509" width="1115" src="https://user-images.githubusercontent.com/63144489/135534357-18f7f594-d80d-42e2-91f2-c625d5fe28d5.png">
> 
> 然而我找不到TikTokDownload.exe文件，请问这个安装过程出现了什么问题吗？ 万分感谢！

首先将本仓库clone到本地之后，在文件目录中再次尝试一下看看

**Comment by Johnserf-Seed** [comment]
> 拜托大佬看看我帮帮我┭┮﹏┭┮

非常抱歉，邮件有点多，没有看见你的issue

**Comment by SingleRottenChips** [comment]
> > 拜托大佬看看我帮帮我┭┮﹏┭┮
> 
> 非常抱歉，邮件有点多，没有看见你的issue

**Comment by SingleRottenChips** [comment]
> > 大佬你好，感谢你的开发。
> > 我是零基础小白，安装了 python 和 pip 之后，再安装 TikTokDownload 显示如下图： <img alt="微信截图_20211001054509" width="1115" src="https://user-images.githubusercontent.com/63144489/135534357-18f7f594-d80d-42e2-91f2-c625d5fe28d5.png">
> > 然而我找不到TikTokDownload.exe文件，请问这个安装过程出现了什么问题吗？ 万分感谢！
> 
> 首先将本仓库clone到本地之后，在文件目录中再次尝试一下看看

感谢大佬回复！抱歉现在才看到┭┮﹏┭┮ 
我按你说的做了，虽然不太清楚你说的“尝试”是指什么。我理解的是在那个目录下再次pip...... 然而结果是这样的：
<img width="1117" alt="微信截图_20211002133332" src="https://user-images.githubusercontent.com/63144489/135704953-aac39b18-8dea-492b-bec6-daa371b3ba66.png">
我试着去运行那个python程序，然而结果和之前一样：
<img width="616" alt="微信截图_20211002133626" src="https://user-images.githubusercontent.com/63144489/135705013-e3e92788-4518-450f-a900-7663aa645673.png">
如果我没看错的话，我记得你好像在哪里提到了exe文件，如果没问题的话应该会有吧......
请问我现在该怎么做呢？烦请大佬赐教，多谢。

**Comment by SingleRottenChips** [comment]
请问大佬现在有空指教一下嘛┭┮﹏┭┮

**Comment by SingleRottenChips** [comment]
文件目录中的文件只有这些，我找不到exe┭┮﹏┭┮
<img width="490" alt="微信截图_20211003083559" src="https://user-images.githubusercontent.com/63144489/135735822-9ec810eb-2c88-4758-9945-0753cfb5e480.png">
大佬帮帮我吧......

**Comment by SingleRottenChips** [comment]
> > 拜托大佬看看我帮帮我┭┮﹏┭┮
> 
> 非常抱歉，邮件有点多，没有看见你的issue

文件目录中的文件只有这些，我找不到exe┭┮﹏┭┮
<img width="490" alt="微信截图_20211003083559" src="https://user-images.githubusercontent.com/63144489/135735822-9ec810eb-2c88-4758-9945-0753cfb5e480.png">
大佬帮帮我吧......

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/tags你可以在这里下载到可执行文件，这个报错的提示是格式错误

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/TikTokDownload/tags
你可以在这里下载到可执行文件，这个报错的提示是格式错误

**Comment by SingleRottenChips** [comment]
> https://github.com/Johnserf-Seed/TikTokDownload/tags 你可以在这里下载到可执行文件，这个报错的提示是格式错误

太感谢了！非常好用（づ￣3￣）づ╭❤～
大佬你说的格式指的是pip的版本吗？我刚刚花了点时间升了级，但pip之后还是没看到执行文件......请问你可以再说得详细一点吗？

**Comment by Johnserf-Seed** [comment]
应该是pip包的问题，之后会修复掉这个问题
