### ISSUE TITLE
[Feature] 加入绝对路径下载

### ISSUE THREAD

**Issue by Yuhyeong** [Johnserf-Seed/TikTokDownload#572]
**描述你想要替换的功能或需要修改的解决方案**
传入用户主页后的批量下载，只能指定相对路径，无法使用绝对路径。因为我在linux服务器上挂在的NAS，平常使用NAS来存储东西。认为其实对于绝对路径的下载也是有需求的。可能这个功能涉及数据库部分代码的修改，会比较麻烦。
不过我觉得可以在每个用户目录内保留一个记录当迁移下载目录时，再次指定该目录仍能读取到之前的更新记录。

**Comment by Johnserf-Seed** [comment]
我提炼了issue大家提的最多的几个，新工具会支持https://github.com/Johnserf-Seed/f2

**Comment by Johnserf-Seed** [comment]
> fast-dl能兼容之前的命名方式吧?要不然一扫全部重下就尴尬了

f2的文件名可以随意组合，只根据作品id进行识别。如果想继承之前的作品命名规则也是可以的，先配置成之前的规则重建数据库，再随意组合即可。

**Comment by ttlttc** [comment]
那太好了,感谢大佬

**Comment by ttlttc** [comment]
提个小建议,下载的时候用临时扩展名区分一下,等真正全部下完了再改回mp4.

因为碰到很多下载半路中断了或者文件压根就是0字节,不盯着下载进度条根本不知道出错,重试的时候也会被自动跳过

**Comment by Johnserf-Seed** [comment]
> 提个小建议,下载的时候用临时扩展名区分一下,等真正全部下完了再改回mp4.
> 
> 因为碰到很多下载半路中断了或者文件压根就是0字节,不盯着下载进度条根本不知道出错,重试的时候也会被自动跳过

支持的，还支持断点续传
