### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zpq5935** [Johnserf-Seed/TikTokDownload#573]
**描述出现的错误**
应该是一个常规python install错误，这个问题在这儿提可能不太合适，但是google 百度了挺多尝试但是还是失败，想来是不是自己操作有问题，我并没有系统地学一遍python，是不是该先除了语法外其他细致学一下

**bug复现**
按如下步骤操作
1. python3 -m venv venv
2. source .\venv\Scripts\activate
3. pip install -r requirements.txt

然后就遇到了常规异常

`
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/aiohttp/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/aiohttp/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/aiohttp/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/aiohttp/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/aiohttp/
Could not fetch URL https://pypi.org/simple/aiohttp/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/aiohttp/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement aiohttp==3.8.5 (from versions: none)
ERROR: No matching distribution found for aiohttp==3.8.5
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
`

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。

**桌面（请填写以下信息）：**
-操作系统：centos7
-vpn代理：应该是关闭
-项目版本：1.4.22
-py版本：3.11.6（试过3.11.3 3.11.6）
-依赖库的版本：/

**附文**
这个问题在这儿提可能不太合适，但是google 百度了挺多尝试但是还是失败，想来是不是自己操作有问题

**Comment by Johnserf-Seed** [comment]
设置国内的pip镜像

**Comment by zpq5935** [comment]
谢谢回复 国内镜像也是设置了的，临时的永久的都试了，也用pip config list 确认了。
```
global.index-url='https://pypi.doubanio.com/simple'
global.timeout='6000'
global.trusted-host='pypi.org files.pythonhosted.org pypi.python.org'
install.trusted-host='pypi.doubanio.com[install]'
```
中间那些openssl版本也试过1.1.1和3.0.7 1，我想着把整台机子重装试下
