### ISSUE TITLE
配置文件中如何添加多个用户的url?

### ISSUE THREAD

**Issue by yuzhezz** [Johnserf-Seed/TikTokDownload#59]
我有很多和用户需要抓取 可是配置文件中好像不能配置多用户的url 所以我生成了很多个不同名字的配置文件 来对应每个用户 是否可以增加一个获取多用户url的功能 方便多用户的抓取 非常感谢

**Comment by Johnserf-Seed** [comment]
这个功能你可以自行二次开发
