### ISSUE TITLE
/aweme/v1/web/user/profile/other/?  接口报错

### ISSUE THREAD

**Issue by ZaiKL** [Johnserf-Seed/TikTokDownload#595]
**描述出现的错误**
抖音主页 抖主 信息接口返回无参数 

**截图**
![图片](https://github.com/Johnserf-Seed/TikTokDownload/assets/86660941/d919ee18-f3cc-4623-87e2-dcaf448b57a4)

**桌面（请填写以下信息）：**
-操作系统：windows10 64bit
-vpn代理：关闭
-项目版本：目前 14200 版本已是最新
-py版本：Python 3.11.5

**附文**
本地网络正常

**Comment by EsperantoP** [comment]
同样的问题

**Comment by WalterDSU** [comment]
同样问题。

**Comment by 6986552** [comment]
号被风控了，换号扫码。

**Comment by EsperantoP** [comment]
今天试了一下，可以使用了。
目前不清楚是自动解除风控了还是我人为接触的

可能的解决方案：
删除config.ini里面，cookie的所有值。
再次唤醒程序，它会要求你扫码。
再次扫码cookie就会自动写入。
我用的账号还是同一个账号。

希望对各位有帮助 ☺️

**Comment by WalterDSU** [comment]
> 今天试了一下，可以使用了。 目前不清楚是自动解除风控了还是我人为解除的
> 
> 可能的解决方案： 删除config.ini里面，cookie的所有值。 再次唤醒程序，它会要求你扫码。 再次扫码cookie就会自动写入。 我用的账号还是同一个账号。
> 
> 希望对各位有帮助 ☺️

正解，估计cookies过期了

**Comment by 6986552** [comment]
> 今天试了一下，可以使用了。 目前不清楚是自动解除风控了还是我人为解除的
> 
> 可能的解决方案： 删除config.ini里面，cookie的所有值。 再次唤醒程序，它会要求你扫码。 再次扫码cookie就会自动写入。 我用的账号还是同一个账号。
> 
> 希望对各位有帮助 ☺️

估计是解除了，我当时有问题的时候删除cookie重新扫码登录不上，换号就可以了。。
