### ISSUE TITLE
[BUG] 本地网络错误 status_code=429

### ISSUE THREAD

**Issue by zpq5935** [Johnserf-Seed/TikTokDownload#607]
**描述出现的错误**
遇到bug先在issues中搜索，没有得到解决方案再提交。
对出现bug的地方做清晰而简洁的描述。、

此命令行下载报错 
`docker run --rm  -v /home/ivy/douyin:/app/Download/post   tiktok-download-zpq:2.0   python3  TikTokTool.py  --interval '2023-01-01|2024-01-01'  -u https://www.douyin.com/user/MS4wLjABAAAAivZ1zSgTflhnL5z5QG-IVsQtUNSRM80j2JavA3ezL48  --naming '{create}_{id}'`

**bug复现**
复现这次行为的步骤：
此命令行下载报错 
`docker run --rm  -v /home/ivy/douyin:/app/Download/post   tiktok-download-zpq:2.0   python3  TikTokTool.py  --interval '2023-01-01|2024-01-01'  -u https://www.douyin.com/user/MS4wLjABAAAAivZ1zSgTflhnL5z5QG-IVsQtUNSRM80j2JavA3ezL48  --naming '{create}_{id}'`

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/44501567/284e698b-d9de-45e4-bf7a-f8b254adb762)

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]
-vpn代理：[例如开启、关闭]
-项目版本：[如1.4.2.2]
-py版本：[如3.11.1]
-依赖库的版本：[出错的库版本号]

**附文**
在此处添加有关此问题的其他备注。

**Comment by lskfaiz** [comment]
我也遇到这个问题了，题主你解决了吗

**Comment by Johnserf-Seed** [comment]
429是接口访问频率过快的问题，重试即可。频繁出现请从采集频率与代理入手。
