### ISSUE TITLE
请问 别人用户 uid  #用户主页 如何获取

### ISSUE THREAD

**Issue by RobotJohns** [Johnserf-Seed/TikTokDownload#61]
请问 别人用户 uid  #用户主页 如何获取

**Comment by RobotJohns** [comment]
#用户主页
#uid = https://v.douyin.com/JcjJ5Tq/
uid = https://www.douyin.com/user/MS4wLjABAAAA8U_l6rBzmy7bcy6xOJel4v0RzoR_wfAubGPeJimN__4?previous_page=app_code_link

在这里 可以直接修改

**Comment by esoman888** [comment]
这不是sec_uid
