### ISSUE TITLE
[BUG]    下载自己喜欢的视频   [  提示  ]:抓获0页数据为空，已跳过。

### ISSUE THREAD

**Issue by budingkak12** [Johnserf-Seed/TikTokDownload#613]
排除配置问题，因为之前都正常抓取的
排除抖音设置问题
下载的文件我都删除了   都不是覆盖下载

**截图**
<img width="686" alt="Snipaste_2023-12-17_10-26-22" src="https://github.com/Johnserf-Seed/TikTokDownload/assets/136218102/19e7ee8b-229c-4a9f-b310-3047da367e5e">

**桌面（请填写以下信息）：**
-操作系统：[windows10 64bit]
-vpn代理：关闭]
-项目版本：1.4.2.2]
-py版本：[3.11.1]

**Comment by Johnserf-Seed** [comment]
提示的很清楚，服务器拒绝了你的请求。更换网络环境或降低请求频率。
