### ISSUE TITLE
本地网络请求异常

### ISSUE THREAD

**Issue by huiyichenjiyi** [Johnserf-Seed/TikTokDownload#620]
下载视频出现问题
[  提示  ]:异常，本地网络请求异常。 异常: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8',
url=URL('https://www.douyin.com/aweme/v1/web/user/profile/other/?device_platform=webapp&aid=6383&sec_user_id=MS4wLjABAAAAB7geBosrrW1XPPqgd88hbbKF8fymijEvW5w
Tsq4qIK6mDkbb5Ycvl8_fxDrHCawy&cookie_enabled=true&platform=PC&downlink=10&X-Bogus=DFSzswVurS0ANxXhtNbLye9WX7Jy')
[2023-12-29 00:22:20,793] - Log.py] - ERROR: [  提示  ]:异常，本地网络请求异常。 异常: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://www.douyin.com/aweme/v1/web/user/profile/other/?device_platform=webapp&aid=6383&sec_user_id=MS4wLjABAAAAB7geBosrrW1XPPq，Traceback (most recent call last):vl8_fxDrHCawy&cookie_enabled=true&platform=PC&downlink=10&X-Bogus=DFSzswVurS0ANxXhtNbLye9WX7Jy')
  File "Util\Profile.py", line 309, in get_user_profile_info
    data = await response.json()
           ^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp\client_reqrep.py", line 1104, in json
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://www.douyin.com/aweme/v1/web/user/profile/other/?device_platform=webapp&aid=6383&sec_user_id=MS4wLjABAAAAB7geBosrrW1XPPqgd88hbbKF8fymijEvW5wTsq4qIK6mDkbb5Ycvl8_fxDrHCawy&cookie_enabled=true&platform=PC&downlink=10&X-Bogus=DFSzswVurS0ANxXhtNbLye9WX7Jy')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Util\Profile.py", line 453, in get_Profile
    user_profile_info = await self.get_user_profile_info(self.headers, self.sec_user_id)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Util\Profile.py", line 321, in get_user_profile_info
    raise RuntimeError(f"本地网络请求异常。 异常: {e}\r") from e
RuntimeError: 本地网络请求异常。 异常: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://www.douyin.com/aweme/v1/web/user/profile/other/?device_platform=webapp&aid=6383&sec_user_id=MS4wLjABAAAAB7geBosrrW1XPPqgd88hbbKF8fymijEvW5wTsq4qIK6mDkbb5Ycvl8_fxDrHCawy&cookie_enabled=true&platform=PC&downlink=10&X-Bogus=DFSzswVurS0ANxXhtNbLye9WX7Jy')

请问怎么解决

**Comment by Johnserf-Seed** [comment]
更换新cookie或网络环境

**Comment by huiyichenjiyi** [comment]
> 更换新cookie或网络环境

更换手机热点这些都不行，而且cookie我扫码后就已扫码，然后就卡着不执行下一步

**Comment by Orochi-sx** [comment]
不要扫码获取，直接把你登录成功后的浏览器里的token粘到conf.ini就行，保留'cookie:'

**Comment by Johnserf-Seed** [comment]
使用`--auto-cookie`的命令来获取cookie。 https://johnserf-seed.github.io/f2/site-config.html#%E9%85%8D%E7%BD%AEcookie
