### ISSUE TITLE
[BUG]SSLCertVerificationError

### ISSUE THREAD

**Issue by cander0327** [Johnserf-Seed/TikTokDownload#621]
**描述出现的错误**
开发者模式获取的cookie，填进conf文件中，运行报错
异常，网络连接异常，异常：Cannot connect to host www.douyin.com:443 ssl:True 
[SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self 
signed certificate in certificate chain (_ssl.c:992)')]

**截图**
![WX20231229-171109](https://github.com/Johnserf-Seed/TikTokDownload/assets/77658699/d81a3aa3-75e8-4aa8-9c92-482066193cd5)

**Comment by Johnserf-Seed** [comment]
这个是你本地网络环境问题，关闭代理后重试或将代理填入配置文件。

**Comment by Johnserf-Seed** [comment]
需注意如果py`urllib3`版本过低，那么代理配置中https的值仍然需要设置成同http一样的参数。
