### ISSUE TITLE
 No such command 'dy'

### ISSUE THREAD

**Issue by chopper1026** [Johnserf-Seed/TikTokDownload#623]
**描述出现的错误**
无法找到dy or douyin这个app

**bug复现**
1、python 3.11.1版本，正常安装f2未报错。
2、输入f2 -h 可以正常显示帮助界面
3、输入f2 dy -h 提示：
Usage: f2 [OPTIONS] COMMAND [ARGS]...

Error: No such command 'dy'.

**截图**
![QQ截图20240101115621](https://github.com/Johnserf-Seed/TikTokDownload/assets/148184648/345ba016-c0b7-4f28-a6ab-0e4667a243e0)

**桌面（请填写以下信息）：**
-操作系统：windows10 64bit
-vpn代理：关闭
-项目版本：Latest
-py版本：3.11.1
-依赖库的版本：0.0.1

**附文**
在此处添加有关此问题的其他备注。

**Comment by chopper1026** [comment]
补充：也无法进行dy配置文件的初始化
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/148184648/c1c57336-6c87-4af1-a7d7-ed7d597b001c)

**Comment by Johnserf-Seed** [comment]
已排查，是pyproject.toml遗漏了部分依赖文件。

**Comment by Johnserf-Seed** [comment]
等待国内镜像站同步再升级 ，或使用官方镜像立即升级。
```bash
pip install --upgrade f2 -i https://pypi.org/simple
```

**Comment by hyunicode** [comment]
尝试了一个上午，还以为mac的问题🤯
