### ISSUE TITLE
cli模式无法启动下载

### ISSUE THREAD

**Issue by chopper1026** [Johnserf-Seed/TikTokDownload#625]
**描述出现的错误**
使用文档中的启动命令指定配置文件无法运行。

**bug复现**
复现这次行为的步骤：
1、更新f2最新版本0.0.1.1。
2、验证[#623](https://github.com/Johnserf-Seed/TikTokDownload/issues/623)通过了。
3、已初始化配置文件成功，并通过auto-cookie获取到了cookie。
4、执行：f2 dy -c conf/dy.yaml，显示内容同f2 dy -h一致，并没有运行下载。

**截图**
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/148184648/20074c79-b979-4ebb-8707-8424da7268fc)
期望效果：
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/148184648/ff965a58-eae8-4c83-8e5c-b80dfadfdcbc)

**桌面（请填写以下信息）：**
-操作系统：windows10 64bit
-vpn代理：关闭
-项目版本：latest
-py版本：3.11.1
-依赖库的版本：f2 0.0.1.1

**附文**
在此处添加有关此问题的其他备注。

**Comment by chopper1026** [comment]
log：
[2024-01-01-15-21-41.log](https://github.com/Johnserf-Seed/TikTokDownload/files/13803837/2024-01-01-15-21-41.log)

**Comment by chopper1026** [comment]
补充：使用初始化的配置文件，不做任何改动，同样无法触发下载，只显示帮助界面

**Comment by Johnserf-Seed** [comment]
> 补充：使用初始化的配置文件，不做任何改动，同样无法触发下载，只显示帮助界面

不做改动怎么会下载呢？

**Comment by Johnserf-Seed** [comment]
> 补充：使用初始化的配置文件，不做任何改动，同样无法触发下载，只显示帮助界面

https://johnserf-seed.github.io/f2/site-config.html

**Comment by zaneyew** [comment]
Meet the same error, only help information while configured as instructed.

**Comment by Johnserf-Seed** [comment]
> Meet the same error, only help information while configured as instructed.

you need setup f2 conf about cookie for app  https://johnserf-seed.github.io/f2/site-config.html

**Comment by chopper1026** [comment]
> > 补充：使用初始化的配置文件，不做任何改动，同样无法触发下载，只显示帮助界面
> 
> https://johnserf-seed.github.io/f2/site-config.html

这块我是看过了的，但怎么说呢，文档的连贯性不是很好，上下文顺序有些问题，整体顺序更类似于：安装—>初始化配置—>改初始化配置的参数（cookie、mode、url等）—>指定配置文件运行，这个主配置文件在初次阅读时并不能知道具体用途，把它放在开发者指南中的话，仅作为使用者而非开发者的话很容易就忽略过去
