### ISSUE TITLE
cover,desc,folderize,music设置为no无法生效

### ISSUE THREAD

**Issue by chopper1026** [Johnserf-Seed/TikTokDownload#626]
**描述出现的错误**
cover,desc,folderize,music设置为no无法生效

**bug复现**
复现这次行为的步骤：
1、主配置文件（python311\Lib\site-packages\f2\conf\app.yaml）修改cover,desc,folderize,music参数值为no。
2、用户配置设置如下，同样配置cover,desc,folderize,music参数值为no
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/148184648/af86d11b-4eb4-4166-9c25-a1ed16b7aca5)

3、执行：f2 -d dy -c D:\Tools\f2\conf\dy2.yaml
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/148184648/9333c3dc-9cba-4276-93da-67055a129673)
可见cover,desc,folderize,music参数依旧遵循默认值。
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/148184648/a3648577-66a5-42cd-93ca-f56f2d478ded)
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/148184648/8ccfa8f5-a675-4a15-96f5-011b252e1d1a)

**Comment by Johnserf-Seed** [comment]
命令是正常的，造成这个的原因是--init-config生成的配置文件问题。参考https://github.com/Johnserf-Seed/TikTokDownload/issues/629#issuecomment-1876864355
已解决该问题，待推送。

**Comment by Johnserf-Seed** [comment]
请更新至v0.0.1.2版本 https://github.com/Johnserf-Seed/f2/releases/tag/v0.0.1.2
```bash
pip install --upgrade f2
```

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/f2/pull/39
