### ISSUE TITLE
[BUG] f2 没有apps命令 无法初始化配置

### ISSUE THREAD

**Issue by sd816224** [Johnserf-Seed/TikTokDownload#630]
**描述出现的错误**
f2 没有apps命令 无法初始化配置

**bug复现**
clone and pip install
 f2 apps --init-config apps.yaml 遇错无法继续安装

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]
-vpn代理：[例如开启、关闭]
-项目版本：[如1.5.0.0]
-py版本：[如3.11.1]
-依赖库的版本：[出错的库版本号]

**附文**
在此处添加有关此问题的其他备注。

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/f2/pull/16
