### ISSUE TITLE
一个半吊子暂时使用方法+遇到问题[BUG]

### ISSUE THREAD

**Issue by Virtual-human** [Johnserf-Seed/TikTokDownload#632]
目前只试用douyin download功能
测试使用方法如下：
1. 克隆项目后，安装f2插件
    pip install f2
2. 查看f2配置文件（全局使用命令行，Location显示f2路径）
   pip show f2
   Location: C:\Users\
   复制路径到计算机找到文件site-packages/f2/conf/app.yaml下，复制cookie到第6行
![屏幕截图 2024-01-04 174926](https://github.com/Johnserf-Seed/TikTokDownload/assets/56722099/7aba7420-ca6a-40c9-8549-03059e6bd867)
3. 将作品ID放置在url：后
4.使用命令行进行下载，默认下载位置为所使用命令行文件夹（如需更改直接设置目标文件夹路径）
 f2 apps --init-config apps.yaml
遇到问题[Error]
1. 无法对cover,desc,folderize,music设置为no无法生效
   应该是传参判断问题所导致（暂时可在f2/apps/cli.py中对其默认参数进行修改使用，异步下载默认参数修改暂时无效）
2. 视频只能首次加载文件，基本只能下载20条以内首次加载视频，未找到具体传参和修改方法
3. 自己比较菜，其他暂时还未进行测试

**Comment by Johnserf-Seed** [comment]
等修复版本推送后再使用--init-config命令。

**Comment by Johnserf-Seed** [comment]
请更新至v0.0.1.2版本 https://github.com/Johnserf-Seed/f2/releases/tag/v0.0.1.2
```bash
pip install --upgrade f2
```

**Comment by tanmx** [comment]
> 请更新至v0.0.1.2版本 https://github.com/Johnserf-Seed/f2/releases/tag/v0.0.1.2
> 
> ```shell
> pip install --upgrade f2
> ```
问题 4 无法对cover,desc,folderize,music设置为no无法生效
测试还是不可以

**Comment by Johnserf-Seed** [comment]
> > 请更新至v0.0.1.2版本 https://github.com/Johnserf-Seed/f2/releases/tag/v0.0.1.2
> > ```shell
> > pip install --upgrade f2
> > ```
> 
> 问题 4 无法对cover,desc,folderize,music设置为no无法生效 测试还是不可以

已经解决该问题，待更新 https://github.com/Johnserf-Seed/f2/issues/22#issuecomment-1878313729

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/f2/pull/39
