### ISSUE TITLE
[BUG]最新版无论怎么修改配置文件，仍然会下载封面原声文案等

### ISSUE THREAD

**Issue by zhiben5201** [Johnserf-Seed/TikTokDownload#634]
1.最新版无论怎么修改配置文件（已经修改了基础配置文件和自定义配置文件），仍然会下载封面原声文案等，那个选项无论是改成NO还是FALSE，都还会下载文案，封面，原声，以及单个文件夹等，修改了是无效的，求问怎么解决，
2.按时间段下载的功能通过设置文件也无法实现，命令行也无法实现
3.新版将文件前面的时间中的点替换成了横杠（图三上为旧版下为新版），因为下载速度极快，手动干预来不及，加上第二条暂时失效，就会导致重新下载一遍，有没有办法改回点，求教
4.会缺少下载文件，少的数量不等，暂时无法截图证明，比如同一个作者，旧版下载下来95个文件，新版F2下载下来有的时候68，有的时候80多
5.依然会有code 429报错
![屏幕截图 2024-01-07 033745](https://github.com/Johnserf-Seed/TikTokDownload/assets/103325310/3bd51d32-60f4-4156-9d7c-1d0afe436029)
![屏幕截图 2024-01-07 041027](https://github.com/Johnserf-Seed/TikTokDownload/assets/103325310/40161627-3847-4688-b63e-763d417d0967)
![屏幕截图 2024-01-07 044123](https://github.com/Johnserf-Seed/TikTokDownload/assets/103325310/75f7b0a2-622e-479d-9402-de2abf4c1647)
![屏幕截图 2024-01-07 134453](https://github.com/Johnserf-Seed/TikTokDownload/assets/103325310/cc668f5d-aae7-4faa-968e-2226c0a460e7)

**Comment by zpq5935** [comment]
+1

**Comment by zhiben5201** [comment]
> +1

第一个好解决，下载作者这个程序主页的抖音cli.py替换掉电脑上的f2>apps>douyin下的同名文件就行了，关键还是二三条

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/f2/commit/1d60f8dcb2d101f0a8112a3ea1693a06d2a7529e
https://github.com/Johnserf-Seed/f2/commit/6fa29e9f4303fbd7bf71cfbbc9da6b187feeb582
v0.0.1.2-pw1的分支把提到的问题已经全部推送了，但是还没发布

**Comment by Johnserf-Seed** [comment]
配置文件的这几个命令失效看这个提交，有说明。https://github.com/Johnserf-Seed/f2/commit/10990c45f6598d0b8dddc0f7837620b002047e89
v0.0.1.1会因为CLI优先权高挤掉默认配置的bool参数。
请不要发重复的issue

**Comment by zhiben5201** [comment]
> 配置文件的这几个命令失效看这个提交，有说明。[Johnserf-Seed/f2@10990c4](https://github.com/Johnserf-Seed/f2/commit/10990c45f6598d0b8dddc0f7837620b002047e89) v0.0.1.1会因为CLI优先权高挤掉默认配置的bool参数。 请不要发重复的issue

谢谢，本帖后续还有编辑更新

**Comment by Johnserf-Seed** [comment]
可以更新至`0.0.1.3`版本

**Comment by zhiben5201** [comment]
> 可以更新至`0.0.1.3`版本

非常感谢，我用笨办法手动更新您于两三个小时前修改的所有文件，重新尝试下载后，1.依然无法实现时间区间，2.文件名时间中依然是横杠
![屏幕截图 2024-01-07 213227](https://github.com/Johnserf-Seed/TikTokDownload/assets/103325310/ac4aac42-fbe4-4682-a3b5-3a9eed8d6d9a)
![屏幕截图 2024-01-07 213244](https://github.com/Johnserf-Seed/TikTokDownload/assets/103325310/b4bf13b1-b0df-43dc-b69c-47965fc20e7b)
![屏幕截图 2024-01-07 213310](https://github.com/Johnserf-Seed/TikTokDownload/assets/103325310/caf8a710-ba7d-4807-b519-b9196d7e0aff)
![屏幕截图 2024-01-07 213346](https://github.com/Johnserf-Seed/TikTokDownload/assets/103325310/75166ba0-1207-43ae-bb37-6b5fb958bfae)

**Comment by Johnserf-Seed** [comment]
最新上传的版本CLI测试是正常的。但关于配置文件的操作仍然还有部分问题。
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/e64b8e18-5de1-4045-b33a-de9a29fd6dd0)

待下个版本更新前该参数可以通过命令行传递，不要使用配置文件。

`-i "2022-01-01|2023-01-01"`

**Comment by zhiben5201** [comment]
> 最新上传的版本CLI测试是正常的。但关于配置文件的操作仍然还有部分问题。 ![image](https://private-user-images.githubusercontent.com/40727745/294761763-e64b8e18-5de1-4045-b33a-de9a29fd6dd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NjgzNTcsIm5iZiI6MTcwNDY2ODA1NywicGF0aCI6Ii80MDcyNzc0NS8yOTQ3NjE3NjMtZTY0YjhlMTgtNWRlMS00MDQ1LWIzM2EtZGU5YTI5ZmQ2ZGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDIyNTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMGYxZDI4N2YyY2EzMjdkY2FiOTM3YWI3MDZmYjBjYjlmMGI2ZmZjN2RhYzI4MWJlZTIxYzMyYzQxNzBkNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UbB2lqYjlb9WjA-lrz1TNFDXvMgQ5zWg2HvzdwecNUg)
> 
> 待下个版本更新前该参数可以通过命令行传递，不要使用配置文件。
> 
> `-i "2022-01-01|2023-01-01"`

原来命令是双引号，我唯独没试双引号，多谢指点
