### ISSUE TITLE
[BUG]日志文件不正常

### ISSUE THREAD

**Issue by 6986552** [Johnserf-Seed/TikTokDownload#637]
**描述出现的错误**
日志文件不正常输出，文件可以正常下载。

**bug复现**
复现这次行为的步骤：
1，执行f2 dy -c app.yaml

**截图**
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/35484288/2133645d-ad7a-4e57-b7cd-cb41d8877f07)

**桌面：**
-操作系统：windows11 64bit
-vpn代理：关闭
-项目版本：1.5.0.0
-py版本：3.11

**Comment by Johnserf-Seed** [comment]
非调试模式不记录debug输出
