### ISSUE TITLE
[BUG] ERROR    TS文件下载失败: range() arg 3 must not be zero

### ISSUE THREAD

**Issue by ahlblzk** [Johnserf-Seed/TikTokDownload#649]
**描述出现的错误**
下载直播偶尔会出现一下错误 导致无法正常下载直播视频：
WARNING  未找到m3u8文件的segments, 尝试获取嵌套的m3u8文件
ERROR    TS文件下载失败: range() arg 3 must not be zero
ERROR    TS文件下载失败: range() arg 3 must not be zero

**截图**
<img width="1091" alt="image" src="https://github.com/Johnserf-Seed/TikTokDownload/assets/7858842/27b90dbe-5d0d-40d4-978b-a26764e40c69">

**桌面（请填写以下信息）：**
-操作系统：mac
-vpn代理：关闭
-项目版本：1.5
-py版本：3.11

**Comment by Johnserf-Seed** [comment]
部分主播的流存在嵌套，下个版本将会解决该问题
