### ISSUE TITLE
[BUG]下载自己收藏的视频报错了

### ISSUE THREAD

**Issue by QQ920924960** [Johnserf-Seed/TikTokDownload#650]
<img width="1185" alt="image" src="https://github.com/Johnserf-Seed/TikTokDownload/assets/7412045/095d99f5-7dd7-418d-b60b-36cf8d0f0cd7">

**Comment by hksjfhkj** [comment]
同样的问题

**Comment by Johnserf-Seed** [comment]
已修复 https://github.com/Johnserf-Seed/f2/commit/d32fc4a56ce2525573e23848c6a5023adfc4ed8d
