### ISSUE TITLE
[BUG] f2 下载页面暂停打印信息了，但是后台依旧在下载

### ISSUE THREAD

**Issue by budingkak12** [Johnserf-Seed/TikTokDownload#652]
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/136218102/99057098-d3e6-4db5-bc92-41d324927f34)
日志信息不刷了一直反复卡在这，但是实际上还在继续下载

**截图**
如果适用，添加屏幕截图以帮助解释您的问题。

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]
-vpn代理：[例如、关闭]
-项目版本：[如1.5.0.0]
-py版本：[如3.11.1]
-依赖库的版本：[出错的库版本号]

**附文**
在此处添加有关此问题的其他备注。

**Comment by Johnserf-Seed** [comment]
你的截图显示已经下载完成了，如果一直在后台下载是无法输入新命令的。
