### ISSUE TITLE
v1.5版本更改yaml文件中path路径参数后不生效，仍下载到默认C:\Users\用户\Download文件夹[BUG]

### ISSUE THREAD

**Issue by huyin324** [Johnserf-Seed/TikTokDownload#657]
图片视频文件下载正常，但是在更改yaml文件中“path”参数后不生效，仍下载到默认路径。
使用如下几种方式更改path参数，仍不生效：
F:\抖音下载\
F:\\抖音下载\\
F:/抖音下载/

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/7a8b64b5-a3f7-4d30-9530-716fd879fff6)
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/0dfc0d1b-5ec7-424f-b452-d4794b416c3b)
经测试，你列举的这几个路径写法均可以。我不知道完整的信息，请严格按照issue模板填写，否则我无法提供更多支持。

**Comment by huyin324** [comment]
> ![image](https://private-user-images.githubusercontent.com/40727745/302309209-7a8b64b5-a3f7-4d30-9530-716fd879fff6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNDExODYsIm5iZiI6MTcwNzE0MDg4NiwicGF0aCI6Ii80MDcyNzc0NS8zMDIzMDkyMDktN2E4YjY0YjUtYTNmNy00ZDMwLTk1MzAtNzE2ZmQ4NzlmZmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDEzNDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNDYzYzExYWZhYmU4Y2E5MjE2ZjRjY2ViYmU5NmM0Mzc3MjM1NDU3NDZlNDMzODBiZjA1OTQzYzFhMDViMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XVbyLW61kXEAsXLAvRSPkAiA0sQ52I1AYZ5VCaJMuLc) ![image](https://private-user-images.githubusercontent.com/40727745/302309311-0dfc0d1b-5ec7-424f-b452-d4794b416c3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNDExODYsIm5iZiI6MTcwNzE0MDg4NiwicGF0aCI6Ii80MDcyNzc0NS8zMDIzMDkzMTEtMGRmYzBkMWItNWVjNy00MjRmLWI0NTItZDQ3OTRiNDE2YzNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDEzNDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ODViM2ZjYmY5YTNkNmRlYjFhOTAxZjhjNTM0NGRiOTllZWIxM2FjY2E0MWNjYzM1MjkzMmQzYjNhN2FmNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vt3MLeIWE-txUbmEz2u9cSXyEapvSjhPzNCzOtEk-tE)经测试，你列举的这几个路径写法均可以。我不知道完整的信息，请严格按照issue模板填写，否则我无法提供更多支持。

感谢，参考您给的的命令在终端中输入：f2 -d dy -c dy.yaml -p 'F:\抖音下载\'    ，已经可以正常下载到该指定目录。
之前不生效是将下载路径填写在了yaml文件中的path字段。
![微信截图_20240205220129](https://github.com/Johnserf-Seed/TikTokDownload/assets/99131421/080d6732-d6a8-4777-88db-6bba80501c44)

**Comment by Johnserf-Seed** [comment]
可以将f2更新至`0.0.1.4`，配置文件相关部分有修改，可以查看最新文档 https://johnserf-seed.github.io/f2/site-config.html 。
