### ISSUE TITLE
没有找到符合条件的作品

### ISSUE THREAD

**Issue by gkj17** [Johnserf-Seed/TikTokDownload#660]
**描述出现的错误**
遇到bug先在issues中搜索，没有得到解决方案再提交。
对出现bug的地方做清晰而简洁的描述。

**bug复现**
复现这次行为的步骤：
1.首先更改了什么什么
2.点击了什么什么
3.“……”

**截图**
C:\Users\***\TikTokDownload>python TikTokTool.py -c douyin.yaml
1.Douyin 2.TikTok: [1/2]: 1
INFO     主配置路径： C:\Users\***\AppData\Local\Programs\Python\Python312\Lib\site-packages\f2\conf\app.yaml
INFO     自定义配置路径： C:\Users\***\Desktop\TikTokDownload\douyin.yaml
WARNING  没有找到符合条件的作品
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/31543062/e88e83ff-d6a9-4945-8bab-e10ccad6f3a8)

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]
-vpn代理：[关闭]
-项目版本：[如1.5.0.0]
-py版本：[如3.12]

**附文**
拿抖音主页的视频，就会报没有找到符合条件的作品。

douyin:
url: https://www.douyin.com/user/MS4wLjABAAAAcK2zW4mkpARZ2XAENxsM9XYrmqZdHv1uDe6McovA94NxVsV2Slx17LdszObEVllX
cookie:***

### DEBUG信息

DEBUG    开启调试模式 (Debug mode on)
INFO     App: douyin
INFO     主配置路径： C:\Users\***\AppData\Local\Programs\Python\Python312\Lib\site-packages\f2\conf\app.yaml
INFO     自定义配置路径： C:\Users\***\AppData\Local\Programs\Python\Python312\Lib\site-packages\f2\conf\douyin.yaml
DEBUG    主配置参数：{'url': 'https://www.douyin.com/user/MS4wLjABAAAA1wMuf3tRz1UJFVViYSmD7J9Y8M8zCEs4Clv9STQdjjU',
         'mode': 'post', 'cookie': 'd_t***', 'cover': None, 'desc': None, 'folderize': None, 'interval': None, 'languages':
         None, 'max_connections': None, 'max_counts': None, 'max_retries': None, 'max_tasks': None, 'mode': None,
         'music': None, 'naming': None, 'page_counts': None, 'path': None, 'timeout': None, 'url':
         'https://www.douyin.com/user/MS4wLjABAAAAcK2zW4mkpARZ2XAENxsM9XYrmqZdHv1uDe6McovA94NxVsV2Slx17LdszObEVllX'}
DEBUG    CLI参数：{'url':
         'https://www.douyin.com/user/MS4wLjABAAAAcK2zW4mkpARZ2XAENxsM9XYrmqZdHv1uDe6McovA94NxVsV2Slx17LdszObEVllX',
         'mode': 'post', 'cookie': '***', 'naming': '{create}_{desc}', 'path': 'Download', 'timeout': 10, 'max_retries': 5,
         'max_connections': 5, 'max_counts': 0, 'max_tasks': 10, 'page_counts': 20, 'proxies': {'http': None, 'https':
         None}, 'music': None, 'cover': None, 'desc': None, 'folderize': None, 'interval': None, 'languages': 'zh_CN',
         'auto_cookie': None, 'sso_login': None, 'headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)
         AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36', 'Referer': 'https://www.douyin.com/'}}
DEBUG    BaseDownloader 请求头headers:{'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
         (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36', 'Referer': 'https://www.douyin.com/', 'Cookie':
         '***'}
DEBUG    用户信息接口地址:https://www.douyin.com/aweme/v1/web/user/profile/other/?device_platform=webapp&aid=6383&chann
         el_pc_web&pc_client_type=1&version_code=170400&version_name=17.4.0&cookie_enabled=true&screen_width=1920&scree
         n_height=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Edge&browser_version=117.0.2045.47&br
         owser_online=true&engine_name=Blink&engine_version=117.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&dev
         ice_memory=8&platform=PC&downlink=10&effective_type=4g&round_trip_time=100&msToken=***&sec_user
         _id=***

DEBUG    响应状态码: 200
DEBUG    开始爬取用户: MS4wLjABAAAAcK2zW4mkpARZ2XAENxsM9XYrmqZdHv1uDe6McovA94NxVsV2Slx17LdszObEVllX 发布的视频
DEBUG    =====================================
DEBUG    最大数量: inf 每次请求数量: 20
DEBUG    开始爬取第 0 页
DEBUG    主页作品接口地址:https://www.douyin.com/aweme/v1/web/aweme/post/?device_platform=webapp&aid=6383&channel=chann
         b&pc_client_type=1&version_code=170400&version_name=17.4.0&cookie_enabled=true&screen_width=1920&screen_height
         =1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Edge&browser_version=117.0.2045.47&browser_on
         line=true&engine_name=Blink&engine_version=117.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&device_memo
         ry=8&platform=PC&downlink=10&effective_type=4g&round_trip_time=100&msToken=***&max_cursor=0&cou
         nt=20&sec_user_id=***&X-Bogus=***
         uPk2ANxXhtoJGcl9WX7nj
DEBUG    响应状态码: 200
DEBUG    当前请求的max_cursor: 0
DEBUG    视频ID: ['7338700528261680399', '7338363569370647843', '7337994717247868175', '7337617113584078089',
         '7337267862526086438', '7336885099964714290', '7336489607334251814', '7336205442692943114',
         '7335764246384348442', '7335410893540396297', '7335032656838626587', '7334638414232407322',
         '7334315072543542565', '7333910937600118066', '7333533664090803506', '7333150674290560294',
         '7332791599325383945', '7332429765325917478', '7331992119944514879', '7331672725255146791'] 视频文案:
         ['第六十七天_临摹_#多宝塔碑_笔画极多和极少都难__#颜体楷书__#每天练字__#修身养性静心_',
         '第六十六天_临摹_#多宝塔碑_水又加太多__#颜体楷书__#写字是一种生活__#静心养性_',
         '第六十五天_临摹_#多宝塔碑__#颜体楷书__#练字打卡__#写字是一种生活方式_',
         '第六十四_临摹#多宝塔碑_#颜体楷书_#每天坚持练字_#写字是一种生活_#静心养性',
         '第六十三天_临摹#多宝塔碑_#颜体楷书_#每天坚持练字_#书法抖起来_#一起学书法',
         '第六十二天_临摹#多宝塔碑_#创作灵感_#颜体楷书_#每日一练_#习字修身',
         '第六十一天_临摹#多宝塔碑_#颜体楷书_#写字是一种生活_#每天坚持练字_#见字如面',
         '第六十天_临摹#多宝塔碑_#愿笔锋所至即心中所向_#颜体楷书_#每天坚持练字',
         '第五十九天_临摹#多宝塔碑_这个勾越写越不会了_#书法入门_#写字是一种生活_#每天坚持练字',
         '第五十八天_临摹#多宝塔碑_#创作灵感_#写字是一种生活_#颜体楷书_#每天坚持练字',
         '第五十七天_临摹#多宝塔碑_#每日一练_#颜体楷书_#汉字之美',
         '第五十六天_临摹#多宝塔碑_#写字是一种生活_#颜体楷书_#每天坚持练字',
         '第五十五天_临摹#多宝塔碑_#颜体楷书_#写字是一种生活_#一起学书法',
         '第五十四天_临摹#多宝塔碑_祝大家新年快乐_好运齐来__#颜体楷书_#每天坚持练字_#见字如面',
         '第五十三天_临摹#多宝塔碑_#写字是一种生活_#颜体楷书_#万事胜意',
         '第五十二天_临摹#多宝塔碑_#创作灵感_#写字是一种生活_#颜体楷书_#每天坚持练字',
         '第五十一天_临摹#多宝塔碑_让我看看哪位老师还没放假回家__#写字是一种生活_#一起学书法_#每天坚持练字',
         '第五十天_临摹#多宝塔碑_#创作灵感_#写字是一种生活_#颜体楷书',
         '第四十九天_临摹_#多宝塔碑__#颜体楷书__#日常练字打卡_',
         '第四十八天_临摹_#多宝塔碑_#颜体楷书_#日常练字打卡__#爱写字_'] 作者: ['山楂糖_', '山楂糖_', '山楂糖_',
         '山楂糖_', '山楂糖_', '山楂糖_', '山楂糖_', '山楂糖_', '山楂糖_', '山楂糖_', '山楂糖_', '山楂糖_', '山楂糖_',
         '山楂糖_', '山楂糖_', '山楂糖_', '山楂糖_', '山楂糖_', '山楂糖_', '山楂糖_']
DEBUG    =====================================
WARNING  没有找到符合条件的作品

**Comment by Johnserf-Seed** [comment]
interval没有配置，或者命令行加上-i all

**Comment by Holferzhang** [comment]
请求端点失败，请检查当前网络环境。 链接：https://mssdk-sg.tiktok.com/web/common?msToken=1Ab-7YxR9lUHSem0PraI_XzdKmpHb6j50L8AaXLAd2aWTdoJCYLfX_67rVQFE4UwwHVHmyG_NfIipqrlLT3kCXps-5PYlNAqtdwEg7TrDyTAfCKyBrOLmhMUjB55oW8SPZ4_EkNxNFUdV7MquA==，代理：{'http://': None, 'https://':
         None}，异常类名：TokenManager，异常详细信息：timed out

**Comment by Johnserf-Seed** [comment]
> 请求端点失败，请检查当前网络环境。 链接：https://mssdk-sg.tiktok.com/web/common?msToken=1Ab-7YxR9lUHSem0PraI_XzdKmpHb6j50L8AaXLAd2aWTdoJCYLfX_67rVQFE4UwwHVHmyG_NfIipqrlLT3kCXps-5PYlNAqtdwEg7TrDyTAfCKyBrOLmhMUjB55oW8SPZ4_EkNxNFUdV7MquA==，代理：{'http://': None, 'https://':
>          None}，异常类名：TokenManager，异常详细信息：timed out

请配置好代理再请求，看文档

**Comment by zsmlgy** [comment]
> interval没有配置，或者命令行加上-i all

-i 如果想指定区间如何使用呢？有详细文档吗大佬
