### ISSUE TITLE
[BUG]下载拥有超过一页视频数量的用户下的作品只能下载第一页

### ISSUE THREAD

**Issue by NightMoonIsland** [Johnserf-Seed/TikTokDownload#662]
**描述出现的错误**
下载拥有超过一页视频数量的用户下的作品只能下载第一页，第二页直接就抓不到了，我试了下好几个用户都是这样，似乎是API有变？

**Comment by NightMoonIsland** [comment]
当第一页下载完后
当请求第二页时 
请求'https://www.douyin.com/aweme/v1/web/aweme/post/?aid=6383&sec_user_id=MS4wLjABAAAA3XuLmc-M1h7Cl3Bx4ZseMXIvSX5cJVIo7EsR6pcdF6V_lptbJjiwRuyjlPWhMlnd&count=20&max_cursor=1708525459000&cookie_enabled=true&platform=PC&downlink=10&X-Bogus=DFSzswVuFhzANxXhtouAIe9WX7je'
仅仅返回{'status_code': 0}

**Comment by hdwmp123** [comment]
遇到同样问题 master 分支

**Comment by pingping99** [comment]
我测试了之后发现是cookie复制不对，是一串很长的，而不是到标点符号就截止了

**Comment by Johnserf-Seed** [comment]
拿不到数据全是cookie的问题，自行排除ck可用性，刷新ck状态就重新打开web版抖音然后使用`--auto-cookie`

**Comment by pingping99** [comment]
感谢大佬！！！
