### ISSUE TITLE
如何下载合集，或者说能不能下载一个作者的所有作品，然后按照合集分类？

### ISSUE THREAD

**Issue by gkj17** [Johnserf-Seed/TikTokDownload#663]
**桌面：**
-操作系统：[windows10 64bit]
-vpn代理：[关闭]
-项目版本：[1.5.0.0]
-py版本：[3.12]
-依赖库的版本：[出错的库版本号]

**附文**
如何下载合集，或者说能不能下载一个作者的所有作品，然后按照合集分类？
比如：https://www.douyin.com/collection/6745735330906769412/1

我使用mode:mix  然后 url填写【https://www.douyin.com/collection/6745735330906769412/1】 会报错：
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/31543062/e1212da8-3751-42ed-9f03-87b83b789841)

**Comment by Johnserf-Seed** [comment]
不需要合集链接，直接输入作品链接。如果是合集作品会自动从头下载所有合集作品。

**Comment by gkj17** [comment]
感谢！
