### ISSUE TITLE
路径的问题

### ISSUE THREAD

**Issue by gkj17** [Johnserf-Seed/TikTokDownload#664]
设置了绝对路径还是会新建一些内容：
比如我设置了路径为/User/My/Test
然后实际上他会在Test生成一个文件夹【douyin】然后在【douyin】文件夹生成一个【post】

我如果想让视频都生成在【/User/My/Test】有什么办法吗

**Comment by Johnserf-Seed** [comment]
没有，因为就是这样设计的

**Comment by gkj17** [comment]
ok，谢谢！！！
