### ISSUE TITLE
[BUG]我用1.5版本的分支，在mac上按配置文件的指引操作，下载指定url时down目录下已创建了抖音用户名称的文件夹，但控制台提示没有找到符合条件的作品

### ISSUE THREAD

**Issue by Alrict** [Johnserf-Seed/TikTokDownload#666]
**描述出现的错误**
遇到bug先在issues中搜索，没有得到解决方案再提交。
对出现bug的地方做清晰而简洁的描述。

**bug复现**
复现这次行为的步骤：
在mac上操作
1.初始化并生成dy.yaml文件
2.同步cookie
3.在dy.yaml文件中配置了mode为post，url:xxxx
4.在控制台执行 f2 dy -c ./dy.yaml 指令
5.项目生成了download文件夹，里面有抖音用户名，控制台显示的是没有找到符合条件的作品
**截图**
如果适用，添加屏幕截图以帮助解释您的问题。

**桌面（请填写以下信息）：**
-操作系统：[例如windows10 64bit]
-vpn代理：[例如开启、关闭]
-项目版本：[如1.5.0.0]
-py版本：[如3.11.1]
-依赖库的版本：[出错的库版本号]

**附文**
在此处添加有关此问题的其他备注。

**Comment by Johnserf-Seed** [comment]
没有配置interval参数，请设置为all

**Comment by Alrict** [comment]
感谢作者大大，已起飞

**Comment by Alrict** [comment]
配置interval参数，设置为all
