### ISSUE TITLE
批量视频下载有 个例 出现闪退现象

### ISSUE THREAD

**Issue by c-disk** [Johnserf-Seed/TikTokDownload#67]
uid ：https://v.douyin.com/RvnR8UX/

多次闪退以为没配置成功，测试 
uid1 ：https://v.douyin.com/Rvn4EvB/和
uid2：https://v.douyin.com/evLNohM/
后发现均能正常进行批量下载

**Comment by c-disk** [comment]
![微信图片编辑_20211211232303](https://user-images.githubusercontent.com/55422862/145681933-bcca95d2-1bdd-41d1-892e-f298943f0130.jpg)

**Comment by Johnserf-Seed** [comment]
v1.2.5已经更新
