### ISSUE TITLE
建议增加网页版获取的主页链接支持

### ISSUE THREAD

**Issue by ciring** [Johnserf-Seed/TikTokDownload#68]
网页版链接直接带sec_id
例如：https://www.douyin.com/user/MS4wLjABAAAAt7VyKvSkkHz_WufLbS8dKIR5tQwCprWUJATHh49BTRU

**Comment by doxuyenxo** [comment]
Same here.

**Comment by Johnserf-Seed** [comment]
下个版本加入

**Comment by doxuyenxo** [comment]
> 下个版本加入

非常感谢你

**Comment by JDZW2018** [comment]
老板， 这个版本什么时间有啊

**Comment by Johnserf-Seed** [comment]
> 老板， 这个版本什么时间有啊

忘记回复了，年前更新了
