### ISSUE TITLE
I accidentally sent the wrong message, don't worry about it.

### ISSUE THREAD

**Issue by zhawaqa** [Johnserf-Seed/TikTokDownload#689]
**描述出现的错误**
用示例代码分析视频 https://www.tiktok.com/@73.boxego/video/7347406180823747882时提示如下：
正在获取视频数据API: https://api16-normal-c-useast1a.tiktokv.com/aweme/v1/feed/?aweme_id=7347406180823747882
获取视频信息失败！原因:'NoneType' object is not subscriptable
正在获取视频数据API: https://api16-normal-c-useast1a.tiktokv.com/aweme/v1/feed/?aweme_id=7347406180823747882
获取视频信息失败！原因:'NoneType' object is not subscriptable
Error: RetryError[<Future at 0x2229ef04d90 state=finished raised TypeError>]
麻烦老大看下

**bug复现**
用如下示例代码运行出现的错误，按网上的改成api22的接口也不行
安装解析库：pip install douyin-tiktok-scraper

import asyncio
from douyin_tiktok_scraper.scraper import Scraper

api = Scraper()

async def hybrid_parsing(url: str) -> dict:
    # Hybrid parsing(Douyin/TikTok URL)
    result = await api.hybrid_parsing(url)
    print(f"The hybrid parsing result:\n {result}")
    return result

asyncio.run(hybrid_parsing(url=input("Paste Douyin/TikTok/Bilibili share URL here: ")))

**截图**
无

**桌面（请填写以下信息）：**
-操作系统：windows10 64bit
-vpn代理：开启
-项目版本：最新
-py版本：3.10.1
-依赖库的版本：

**附文**
在此处添加有关此问题的其他备注。

**Comment by zhawaqa** [comment]
I accidentally sent the wrong message, don't worry about it.

**Comment by Johnserf-Seed** [comment]
发错地方了，做删除处理
