### ISSUE TITLE
以后会出能直接双击运行就能用的版本吗？

### ISSUE THREAD

**Issue by ZX828** [Johnserf-Seed/TikTokDownload#695]
不会用，弄不明白。
之前用过个，好像就是这个的1.4版本的，写好配置文件，双击exe文件就能直接开始下载了。
要不是那个用不了了，还真不想研究这个。
到现在我也没弄明白怎么用……

## 以后还会出能直接双击运行就能用的版本吗？

**Comment by Johnserf-Seed** [comment]
不会，它们本质上是相同的，都需要配置。但命令比以往的方式更加容易使用，也方便开发者调用。

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/f2-webui
可以关注这个库，以后会出webui版本
