### ISSUE TITLE
mac电脑上，执行f2 dy -u  命令，提示：不存在该模式: None 

### ISSUE THREAD

**Issue by fangyingwu** [Johnserf-Seed/TikTokDownload#697]
**描述出现的错误**
mac系统，执行 f2  dy  -u https://www.douyin.com/user/MS4wLjABAAAA5F9FRDcnbzcglnqt3JYiks6d1uPkynOsWFyrz9FkOus时，提示：ERROR    不存在该模式: None 

**截图**
![tk](https://github.com/Johnserf-Seed/TikTokDownload/assets/35124617/5261cfab-8af3-44cf-a7de-789eb628682b)

**桌面（请填写以下信息）：**
-操作系统：[Mac os]
-vpn代理：[开启]
-项目版本：[1.5.0.0]
-py版本：[3.12.3]

**附文**
在此处添加有关此问题的其他备注。

**Comment by Johnserf-Seed** [comment]
配置`mode`就好了，先看文档和help。
