### ISSUE TITLE
想请教很基本的问题

### ISSUE THREAD

**Issue by yuta2021** [Johnserf-Seed/TikTokDownload#7]
我下载好软件后双击打开conf 是Notepad软件打开的，和你用的软件感觉不一样没问题吗？

然后想下载的视频uid放进去，还有保存位置在桌面的话怎么填写？
其他的地方不知道要改哪里，所以准备不动。

下面就不知道怎么做了。是用特殊的软件打开TikTokDownload软件吗？
.py 的文件是用编写python的软件打开吗？

我等大家的回复

**Comment by yuta2021** [comment]
我已经下载好了Notepad++软件，页面和说明图上一样了

**Comment by Johnserf-Seed** [comment]
你好，推荐使用Notepad++打开配置文件，因为记事本的UTF-8格式可能会有意想不到的问题出现。

保存位置在桌面的话可以填  "C:\\Users\\你的用户名\\Desktop\\任意名字\\"  (不包含双引号) 

然后你可以适当的把下载数33调大一点 如 60，因为抖音的api的问题，最多只能抓出最新的33左右的视频。

如果没有安装python需要前往[python.org](https://python.org/)主页下载，版本需要大于3.7.5 。然后代码所要求安装的库也需要安装，安装教程可以根据百度的教程来（需要注意环境变量）

还有任何问题欢迎继续提问

**Comment by Johnserf-Seed** [comment]
打包编译的项目在这
https://github.com/Johnserf-Seed/TikTokDownload/tags
