### ISSUE TITLE
WARNING  第 N 次响应内容为空

### ISSUE THREAD

**Issue by ZX828** [Johnserf-Seed/TikTokDownload#703]
我遇到了 WARNING  第 N 次响应内容为空
按照 QA文档 https://johnserf-seed.github.io/f2/question-answer/qa.html  设置了cookie
cookie: 'douyin.com; xgplayer_user_id=
但还是相应为空
WARNING  第 5 次响应内容为空, 状态码: 200,                                     
         URL:https://www.douyin.com/aweme/v1/web/aweme/favorite/?device_platfor
yaml的位置是这样的，不知道是不是我路径写错了没找到。
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/144084680/cc10827a-010a-48a6-99be-b7f3f83e013d)

###有没有能从程序里获取到配置信息的方法啊？方便检查配置文件是不是有问题的那种？
这个labels能不能没有？我这只算问问题，不算是提交故障或者建议吧……
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/144084680/6c0a105f-f5a1-466f-8b8b-251c6fc86923)

**Comment by Johnserf-Seed** [comment]
代码片段里就是直接从代码获取数据的方法，配置cookie就可以。直接检查配置文件是否有问题输入命令查看'f2 -d DEBUG dy -c 配置文件路径'

**Comment by ZX828** [comment]
命令我不会用，所以我把配置文件里的
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/144084680/6d9b1d04-cd28-4b36-9c52-ee9f68b1c303)
来回改了几次，貌似没什么变化。
所以应该是配置没生效。
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/144084680/ea818b9d-9f3b-4e47-b726-4e622275a0ff)
我的配置文件为什么不生效啊？
我除了配置文件的路径，其他的都是从示例复制的，到底是哪的问题呢？

**Comment by Johnserf-Seed** [comment]
你可以像这样从配置文件生成`kwargs`
```python
import asyncio
from f2.apps.douyin.handler import DouyinHandler
from f2.utils.conf_manager import ConfigManager

kwargs = {
    "headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
        "Referer": "https://www.douyin.com/",
    },
    "proxies": {"http://": None, "https://": None},
    "timeout": 10,
    "cookie": "YOUR_COOKIE_HERE",
}

kwargs |= ConfigManager("你的自定义配置路径").get_config("douyin")

...
```
