### ISSUE TITLE
[BUG] Error Downloading TikTok Posts Due to msToken API Error

### ISSUE THREAD

**Issue by iDataist** [Johnserf-Seed/TikTokDownload#719]
## 错误的详细描述
在使用 `f2 tk` 命令尝试下载抖音帖子时，我经常遇到错误。相同的设置过程用于下载抖音（Douyin）时正常工作。

## 系统平台
<details>
<summary>点击展开</summary>

- **操作系统**: Windows 11
- **Python 版本**: Python 3.11.1
- **F2 版本**: 0.0.1.5
- **浏览器**: Firefox
- **网络环境**: 美国，无代理

</details>

## 错误复现步骤
<details>
<summary>点击展开</summary>

1. 在 `douyin\Lib\site-packages\f2\conf\app.yaml` 文件中设置抖音配置。
2. 运行命令 `f2 tk --auto-cookie firefox`。
3. 运行命令 `f2 tk -u https://www.tiktok.com/@xxxx`。

**配置文件（app.yaml）**：
```yaml
tiktok:
  cookie: ak_bmsc=xxxx; passport_csrf_token=xxxx; passport_csrf_token_default=xxxx; multi_sids=xxxx; cmpl_token=xxxx; passport_auth_status=xxxx; passport_auth_status_ss=xxxx; sid_guard=xxxx; uid_tt=xxxx; uid_tt_ss=xxxx; sid_tt=xxxx; sessionid=xxxx; sessionid_ss=xxxx; ssid_ucp_v1=xxxx; tt-target-idc-sign=xxxx; tt_chain_token=xxxx; bm_sv=xxxx; store-idc=xxxx; ttwid=xxxx; odin_tt=xxxx; msToken=xxxx; tiktok_webapp_theme=light
  cover: false
  desc: false
  folderize: false
  interval: all
  languages: en_US
  max_connections: 5
  max_counts: 0
  max_retries: 4
  max_tasks: 6
  mode: post
  music: false
  naming: '{create}_{aweme_id}_{desc}'
  page_counts: 20
  path: ./Download
  timeout: 6
```

**错误信息**：
```plaintext
ERROR    msToken API错误：msToken 内容不符合要求
INFO     生成虚假的msToken
INFO     生成虚假的msToken
ERROR    解析
         https://www.tiktok.com/api/user/detail/?WebIdLastTime=1716643217&aid=1988&app_language=zh-Hans&app_name=tiktok_web&browser_language=zh-CN&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0%20(Windows%20NT%2010.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36&channel=tiktok_web&cookie_enabled=true&device_id=7306060721837852167&device_platform=web_pc&focus_state=true&from_page=user&history_len=4&is_fullscreen=false&is_page_visible=true&language=zh-Hans&os=windows&priority_region=&referer=&region=SG&root_referer=https://www.tiktok.com/&screen_height=1080&screen_width=1920&webcast_language=zh-Hans&tz_name=Asia/Hong_Kong&msToken=BsX4yCeHR4DH+4Z1kGkzncqJnTIraH3-ZL85kv0lC3us+O04tDhlndLqN7Ff8zZq134EIxtk06RDjnRFvhQRVgIHJFhJDRee+RcSZ8d6dWQ9k22tf5uVDevFoNkO3q43FlszpFZ1X2WzgFM9MP==&secUid=MS4wLjABAAAA1TQUIEMS7ThX22wMrfKDn1G_yIYHRQ4kCM3WxsgDUJbLYN5SExsIbJH_-L5YG-gY&uniqueId=&X-Bogus=DFS...
接口 JSON 失败： Expecting property name enclosed in double quotes: line 2 column 5 (char 6)      
ERROR    API内容请求失败，请更换新cookie后再试
```

**调试命令**：
请运行命令 `f2 -d DEBUG` 并附上日志目录中的日志文件，以提供日志信息进行诊断。

</details>

## 预期行为
我希望帖子能够成功下载，而不会遇到 msToken 错误。

## 截图
如果适用，请添加截图以帮助解释您的问题。

## 日志文件
请附上调试日志文件，以帮助诊断问题。

## 其他信息
任何有助于解决问题的额外信息。

- [x] 我已经查看了[文档](https://johnserf-seed.github.io/f2/quick-start.html)和[已关闭的问题](https://github.com/Johnserf-Seed/f2/issues?q=is%3Aissue+is%3Aclosed)以寻找可能的解决方案。
- [x] 我在[常见问题解答](https://johnserf-seed.github.io/f2/question-answer/qa.html)中没有找到我的问题。
- [x] 这个问题是公开的，并且我已删除所有敏感信息。
- [x] 我理解未按照模板提交的问题将不予优先处理。

**Comment by iDataist** [comment]
Has anyone else encountered this issue?

**Comment by Richard0818** [comment]
一模一样

**Comment by zmzimpl** [comment]
same error

**Comment by iDataist** [comment]
I wonder if TikTok download is working for anyone. I can download from Douyin without any issues, and both are configured the same way (following similar steps). I don't think it's a configuration problem on my end. Any suggestions would be greatly appreciated!

**Comment by Johnserf-Seed** [comment]
会更新文档说明如何解决这个问题
