### ISSUE TITLE
[FEATRUE / REQUEST] naming 中的可用参数有哪些？

### ISSUE THREAD

**Issue by RallyQ** [Johnserf-Seed/TikTokDownload#732]
配置文件说明文档中 https://johnserf-seed.github.io/f2/site-config.html 
只提到了 naming: '{create}_{desc}'，两个参数，想知道抖音单个视频的naming还有哪些可用参数？谢谢！

**Comment by Johnserf-Seed** [comment]
https://johnserf-seed.github.io/f2/guide/apps/douyin/cli.html
