### ISSUE TITLE
[BUG] ERROR    msToken API错误：msToken 内容不符合要求 INFO     生成虚假的msToken

### ISSUE THREAD

**Issue by qq517739813** [Johnserf-Seed/TikTokDownload#733]
根据多方面查看tiktok配置了代理获取了cookie之后报错 msToken API错误：msToken 内容不符合要求 INFO
尝试退出登录重新获取cookie依然这样
![Snipaste_2024-06-22_15-26-10](https://github.com/Johnserf-Seed/TikTokDownload/assets/41685147/e364a897-e390-4b19-bd0b-4af7c533e0c7)

**Comment by Johnserf-Seed** [comment]
更新`conf.yaml`中`msToken`的配置即可，根据`mssdk-sg.tiktok.com/web/common`这个字段或者`mssdk-sg.tiktok.com/web/report`在开发者工具中复制请求负载即可。

**Comment by iDataist** [comment]
@Johnserf-Seed , 我按着你所指导的方法复制了开发者工具中的msToken，并且替换了`\Lib\site-packages\f2\conf\conf.yaml`中的两处msToken，还是看到了相同的错误。让我有点儿迷惑的是错误信息里的msToken并不是`conf.yaml`中的值。

我没有用代理。请帮忙指点有什么设置可能出了问题。我只是不能下载tiktok，可以下载抖音。
![2](https://github.com/Johnserf-Seed/TikTokDownload/assets/46846986/9ae09a97-0bfa-4971-be7b-500f0219fb43)
![new1](https://github.com/Johnserf-Seed/TikTokDownload/assets/46846986/1a8b978a-20ce-4296-81a7-481e0a88d72c)


```
ERROR    msToken API错误：msToken 内容不符合要求
INFO     生成虚假的msToken
ERROR    解析
         https://www.tiktok.com/api/user/detail/?WebIdLastTime=1719353366&aid=1988&app_language=zh-Hans&
         app_name=tiktok_web&browser_language=zh-CN&browser_name=Mozilla&browser_online=true&browser_pla
         tform=Win32&browser_version=5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2         F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F119.0.0.0%20Safari%2F537.36&channel=tiktok_w         eb&cookie_enabled=true&device_id=*******&device_platform=web_pc&focus_state=true&fr         om_page=user&history_len=4&is_fullscreen=false&is_page_visible=true&language=zh-Hans&os=windows         &priority_region=&referer=&region=SG&root_referer=https%3A%2F%2Fwww.tiktok.com%2F&screen_height         =1080&screen_width=1920&webcast_language=zh-Hans&tz_name=Asia%2FHong_Kong&msToken=1VlvmMfNmSIkS         vlIOMQj53-80ZC4nrhj7xbm16bpPFoSkA2v0RTekOAKNRggonqy-IbLLW54mw+hEVyfvkJMbDXLuGZ01wmkbJVEhHWtE7C4         c6tN8vGVjfXKl-qicgxqXbUKoJdKsxoRX0BMrH==&secUid=********* 接口 JSON 失败：  
         Expecting property name enclosed in double quotes: line 2 column 5 (char 6)
请前往QA文档 https://johnserf-seed.github.io/f2/question-answer/qa.html 查看相关帮助
ERROR    API内容请求失败，请更换新cookie后再试

```

**Comment by Johnserf-Seed** [comment]
> @Johnserf-Seed , 我按着你所指导的方法复制了开发者工具中的msToken，并且替换了`\Lib\site-packages\f2\conf\conf.yaml`中的两处msToken，还是看到了相同的错误。让我有点儿迷惑的是错误信息里的msToken并不是`conf.yaml`中的值。
> 
> 我没有用代理。请帮忙指点有什么设置可能出了问题。我只是不能下载tiktok，可以下载抖音。 ![2](https://private-user-images.githubusercontent.com/46846986/342949404-9ae09a97-0bfa-4971-be7b-500f0219fb43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NzE3NjIsIm5iZiI6MTcxOTU3MTQ2MiwicGF0aCI6Ii80Njg0Njk4Ni8zNDI5NDk0MDQtOWFlMDlhOTctMGJmYS00OTcxLWJlN2ItNTAwZjAyMTlmYjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDEwNDQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiM2M2ZWU2OTk4ZTlkMDdhZmUzZDc0ODk3MzM3ZjI4MDZmYjIzYWQ1OGNhNTE1ODExYjE1MzZlZTg1NGE1YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hjuj5xu6YetbnEx4tjEg6TYfGxghhfLhwUoqoZwbQDc) ![new](https://private-user-images.githubusercontent.com/46846986/342951449-3f21423b-1e52-499e-9366-d54a9920dc3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NzE3NjIsIm5iZiI6MTcxOTU3MTQ2MiwicGF0aCI6Ii80Njg0Njk4Ni8zNDI5NTE0NDktM2YyMTQyM2ItMWU1Mi00OTllLTkzNjYtZDU0YTk5MjBkYzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDEwNDQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZmRmNzEwNGYzNjRhNWJlYzY5YjM0YjZmYWRjODdmNmU5YTk2NjRiZWJhOWQ5YWQyYjgyZTYwZWM4ZWI5NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LYlioBajic6DO8LaidD0Lpn9wOVHFJe7diABpLIu0bw)
> 
> ```
> ERROR    msToken API错误：msToken 内容不符合要求
> INFO     生成虚假的msToken
> ERROR    解析
>          https://www.tiktok.com/api/user/detail/?WebIdLastTime=*****&aid=****&app_language=zh-Hans&
>          app_name=tiktok_web&browser_language=zh-CN&browser_name=Mozilla&browser_online=true&browser_pla
>          tform=Win32&browser_version=5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2         F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F119.0.0.0%20Safari%2F537.36&channel=tiktok_w         eb&cookie_enabled=true&device_id=*******&device_platform=web_pc&focus_state=true&fr         om_page=user&history_len=4&is_fullscreen=false&is_page_visible=true&language=zh-Hans&os=windows         &priority_region=&referer=&region=SG&root_referer=https%3A%2F%2Fwww.tiktok.com%2F&screen_height         =1080&screen_width=1920&webcast_language=zh-Hans&tz_name=Asia%2FHong_Kong&msToken=1VlvmMfNmSIkS         vlIOMQj53-80ZC4nrhj7xbm16bpPFoSkA2v0RTekOAKNRggonqy-IbLLW54mw+hEVyfvkJMbDXLuGZ01wmkbJVEhHWtE7C4         c6tN8vGVjfXKl-qicgxqXbUKoJdKsxoRX0BMrH==&secUid=********* 接口 JSON 失败：  
>          Expecting property name enclosed in double quotes: line 2 column 5 (char 6)
> 请前往QA文档 https://johnserf-seed.github.io/f2/question-answer/qa.html 查看相关帮助
> ERROR    API内容请求失败，请更换新cookie后再试
> ```
> 
> 还有就是观察到这个错误：缺乏URL参数，详情看命令帮助。
> 
> ```
> (douyin) PS C:\Users\***i\Downloads\TikTokDownload> f2 tk --auto-cookie firefox
> INFO     App: tiktok
> 是否要使用命令行的参数更新配置文件？`C:\Users\***\Downloads\TikTokDownload\douyin\Lib\site-packages\f2\conf\app.yaml` [Y/n]: Y
> 配置文件已更新!
> INFO     主配置路径：C:\Users\***\Downloads\TikTokDownload\douyin\Lib\site-packages\f2\conf\app.yaml    
> INFO     自定义配置路径：C:\Users\***\Downloads\TikTokDownload\douyin\Lib\site-packages\f2\conf\app.yaml
> ERROR    缺乏URL参数，详情看命令帮助
> ```

除了msToken值以外还包括这次请求的负载。
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/7e172ade-1666-484c-a237-26a1984f4f9f)

`0.0.1.6-pw2`版本已发布，更新即可。

**Comment by iDataist** [comment]
@Johnserf-Seed, 多谢答复。已经安装了“0.0.1.6-pw2” (pip install git+https://github.com/Johnserf-Seed/f2.git@v0.0.1.6-pw2)。执行 `f2 tk --auto-cookie firefox`  后  `f2/conf/app.yaml`如下。请帮忙指点是哪出了问题。
```
tiktok:
  cookie: ak_bmsc=***~***~***; bm_sv=***~***; cmpl_token=***; msToken=***;
    multi_sids=***; odin_tt=***;
    passport_auth_status=***; passport_auth_status_ss=***;
    passport_csrf_token=***; passport_csrf_token_default=***;
    sessionid=***; sessionid_ss=***;
    sid_guard=***;
    sid_tt=***; sid_ucp_v1=***;
    ssid_ucp_v1=***;
    store-country-code=***; store-country-code-src=***; store-idc=***; tt-target-idc=***;
    tt-target-idc-sign=***;
    tt_chain_token=***; tt_csrf_token=***;
    ttwid=***;
    uid_tt=***; uid_tt_ss=***;
    passport_fe_beating_status=***; tiktok_webapp_theme=***; tiktok_webapp_theme_auto_dark_ab=***;
    last_login_method=***
  cover: false
  desc: false
  folderize: false
  interval: all
  lyric: false
  max_connections: 5
  max_counts: 0
  max_retries: 5
  max_tasks: 10
  mode: post
  music: false
  naming: '{create}_{aweme_id}'
  page_counts: 20
  path: Download
  timeout: 10
```
抖音下载依旧正常。Tiktok还是不能下载，我没有用代理或者VPN，Tiktok登录正常。
```
ERROR    HTTP状态错误, 尝试GET请求失败:                                                                                                         
         https://v16-webapp-prime.us.tiktok.com/video/tos/useast2a/tos-useast2a-ve-0068c001-euttp/o82MXJiNTi2eMSqfglErQ8Yf4TfcyQAXVaeMA8/?a=1988
         &bti=ODszNWYuMDE6&ch=0&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C&cv=1&br=734&bt=367&cs=0&ds=6&ft=4KJMyMzm8Zmo0mPfK-4jVZ_edpWrKsd.&mime_type=vide
         o_mp4&qs=0&rc=cnF8b2hsc2d3SkBwaHIxaDFybndmNWc6ZWg0NDU8ZjY7NTg3NUBpMzZrdHg5cmVuczMzZjczM0BjRl5Nc3FePmJKYSNvYF90aHFmOiMuYS0wYDViNjUxYWMvY
         zI1YSMwY2tsMmRzcWNgLS1kMWNzcw%3D%3D&btag=e00088000&expire=1719973129&l=202407022018377735B7B21D54990BFF93&ply_type=2&policy=2&signature
         =43dde3d1d4d04aa65143f38e1d330d6e&tk=tt_chain_token, 错误详情: Client error '403 Forbidden' for url                                    
         'https://v16-webapp-prime.us.tiktok.com/video/tos/useast2a/tos-useast2a-ve-0068c001-euttp/o82MXJiNTi2eMSqfglErQ8Yf4TfcyQAXVaeMA8/?a=198
         8&bti=ODszNWYuMDE6&ch=0&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C&cv=1&br=734&bt=367&cs=0&ds=6&ft=4KJMyMzm8Zmo0mPfK-4jVZ_edpWrKsd.&mime_type=vid
         eo_mp4&qs=0&rc=cnF8b2hsc2d3SkBwaHIxaDFybndmNWc6ZWg0NDU8ZjY7NTg3NUBpMzZrdHg5cmVuczMzZjczM0BjRl5Nc3FePmJKYSNvYF90aHFmOiMuYS0wYDViNjUxYWMv
         YzI1YSMwY2tsMmRzcWNgLS1kMWNzcw%3D%3D&btag=e00088000&expire=1719973129&l=202407022018377735B7B21D54990BFF93&ply_type=2&policy=2&signatur
         e=43dde3d1d4d04aa65143f38e1d330d6e&tk=tt_chain_token'
         For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403
```
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/46846986/f7d3451a-0a9f-46d8-91f5-10275b23efb5)

**Comment by qq517739813** [comment]
感谢作者的无私回复，但是我这里更新msToken后和magec的依然无法爬取tk的视频，已经是根据多方查阅但是不能解决，期望作者回复
![Uploading 修改图.png…]()

**Comment by qq517739813** [comment]
![修改图](https://github.com/Johnserf-Seed/TikTokDownload/assets/41685147/82f491ca-db9f-4f65-8156-2dcf8f7bbbe7)

**Comment by Johnserf-Seed** [comment]
> @Johnserf-Seed, 多谢答复。已经安装了“0.0.1.6-pw2” (pip install git+[https://github.com/Johnserf-Seed/f2.git@v0.0.1.6-pw2)。执行](https://github.com/Johnserf-Seed/f2.git@v0.0.1.6-pw2)%E3%80%82%E6%89%A7%E8%A1%8C) `f2 tk --auto-cookie firefox` 后 `f2/conf/app.yaml`如下。请帮忙指点是哪出了问题。
> 
> ```
> tiktok:
>   cookie: ak_bmsc=***~***~***; bm_sv=***~***; cmpl_token=***; msToken=***;
>     multi_sids=***; odin_tt=***;
>     passport_auth_status=***; passport_auth_status_ss=***;
>     passport_csrf_token=***; passport_csrf_token_default=***;
>     sessionid=***; sessionid_ss=***;
>     sid_guard=***;
>     sid_tt=***; sid_ucp_v1=***;
>     ssid_ucp_v1=***;
>     store-country-code=***; store-country-code-src=***; store-idc=***; tt-target-idc=***;
>     tt-target-idc-sign=***;
>     tt_chain_token=***; tt_csrf_token=***;
>     ttwid=***;
>     uid_tt=***; uid_tt_ss=***;
>     passport_fe_beating_status=***; tiktok_webapp_theme=***; tiktok_webapp_theme_auto_dark_ab=***;
>     last_login_method=***
>   cover: false
>   desc: false
>   folderize: false
>   interval: all
>   lyric: false
>   max_connections: 5
>   max_counts: 0
>   max_retries: 5
>   max_tasks: 10
>   mode: post
>   music: false
>   naming: '{create}_{aweme_id}'
>   page_counts: 20
>   path: Download
>   timeout: 10
> ```
> 
> 抖音下载依旧正常。Tiktok还是不能下载，我没有用代理或者VPN，Tiktok登录正常。
> 
> ```
> ERROR    HTTP状态错误, 尝试GET请求失败:                                                                                                         
>          https://v16-webapp-prime.us.tiktok.com/video/tos/useast2a/tos-useast2a-ve-0068c001-euttp/o82MXJiNTi2eMSqfglErQ8Yf4TfcyQAXVaeMA8/?a=1988
>          &bti=ODszNWYuMDE6&ch=0&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C&cv=1&br=734&bt=367&cs=0&ds=6&ft=4KJMyMzm8Zmo0mPfK-4jVZ_edpWrKsd.&mime_type=vide
>          o_mp4&qs=0&rc=cnF8b2hsc2d3SkBwaHIxaDFybndmNWc6ZWg0NDU8ZjY7NTg3NUBpMzZrdHg5cmVuczMzZjczM0BjRl5Nc3FePmJKYSNvYF90aHFmOiMuYS0wYDViNjUxYWMvY
>          zI1YSMwY2tsMmRzcWNgLS1kMWNzcw%3D%3D&btag=e00088000&expire=1719973129&l=202407022018377735B7B21D54990BFF93&ply_type=2&policy=2&signature
>          =43dde3d1d4d04aa65143f38e1d330d6e&tk=tt_chain_token, 错误详情: Client error '403 Forbidden' for url                                    
>          'https://v16-webapp-prime.us.tiktok.com/video/tos/useast2a/tos-useast2a-ve-0068c001-euttp/o82MXJiNTi2eMSqfglErQ8Yf4TfcyQAXVaeMA8/?a=198
>          8&bti=ODszNWYuMDE6&ch=0&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C&cv=1&br=734&bt=367&cs=0&ds=6&ft=4KJMyMzm8Zmo0mPfK-4jVZ_edpWrKsd.&mime_type=vid
>          eo_mp4&qs=0&rc=cnF8b2hsc2d3SkBwaHIxaDFybndmNWc6ZWg0NDU8ZjY7NTg3NUBpMzZrdHg5cmVuczMzZjczM0BjRl5Nc3FePmJKYSNvYF90aHFmOiMuYS0wYDViNjUxYWMv
>          YzI1YSMwY2tsMmRzcWNgLS1kMWNzcw%3D%3D&btag=e00088000&expire=1719973129&l=202407022018377735B7B21D54990BFF93&ply_type=2&policy=2&signatur
>          e=43dde3d1d4d04aa65143f38e1d330d6e&tk=tt_chain_token'
>          For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/46846986/345191016-f7d3451a-0a9f-46d8-91f5-10275b23efb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNjUxNDksIm5iZiI6MTcyMDM2NDg0OSwicGF0aCI6Ii80Njg0Njk4Ni8zNDUxOTEwMTYtZjdkMzQ1MWEtMGE5Zi00NmQ4LTkxZjUtMTAyNzViMjNlZmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE1MDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMzkyMGFmZjU1MTUxOTEyYjM5OTRjMjRhOGJmOWMzMmRmODdiZDg0M2ZiZGY3MGMxNDMyOTU2NDFjNjdjMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lfz8Z4WtcjP-14kvt22nXwQ7eEk8_13isZClHKSFeJg)

可以参考
qa: https://johnserf-seed.github.io/f2/question-answer/qa.html#tiktok-403-forbidden
issue: https://github.com/Johnserf-Seed/f2/issues/79

**Comment by Johnserf-Seed** [comment]
> ![修改图](https://private-user-images.githubusercontent.com/41685147/346344731-82f491ca-db9f-4f65-8156-2dcf8f7bbbe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNjUxOTEsIm5iZiI6MTcyMDM2NDg5MSwicGF0aCI6Ii80MTY4NTE0Ny8zNDYzNDQ3MzEtODJmNDkxY2EtZGI5Zi00ZjY1LTgxNTYtMmRjZjhmN2JiYmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE1MDgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYjM1ODU5ZjI4OTRlODYxZWY0Yjg1NzI0M2RjMjI0ZjQ1NjlhODFkNzE5YWU0ZGY4ZjZjNDY1YjJmZTYyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LKddaAa1d7xU_orh6OAYCjvRQFjP0PgCEUigEA2cRus)

可以更新到`0.0.1.6`版本
