### ISSUE TITLE
抖音最新的链接闪退

### ISSUE THREAD

**Issue by zhouye93** [Johnserf-Seed/TikTokDownload#74]
抖音最新的链接闪退（个人主页的）

**Comment by zhouye93** [comment]
我下载的exe文件

**Comment by zhouye93** [comment]
批量下载直接回车，单一视频下载直接粘贴视频链接：https://v.douyin.com/evLhSNB/
----读取配置完成----
----为您下载多个视频----
----用户的sec_id=MS4wLjABAAAAR6-Ad84N3ae22LP_M7CHbOdLo0VMWxj-P8CHFm5TctA----


https://v.douyin.com/evLhSNB/这个链接现在已经拿不到了只有
https://www.douyin.com/user/MS4wLjABAAAAR6-Ad84N3ae22LP_M7CHbOdLo0VMWxj-P8CHFm5TctA    之前的exe 不能解析用户的sec_id utools也是解析不了

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/147638140-3ca81949-543c-4d01-ab28-d17ac414b8fe.png)
可以解析哦，电脑不要开代理

**Comment by Johnserf-Seed** [comment]
![image](https://user-images.githubusercontent.com/40727745/147638415-b72261bd-5afc-4eda-a4f1-20b9ca609532.png)
65个全部下载完成

**Comment by zhouye93** [comment]
https://www.douyin.com/user/MS4wLjABAAAAR6-Ad84N3ae22LP_M7CHbOdLo0VMWxj-P8CHFm5TctA   这个链接 ？电脑不要开代理在哪配置
