### ISSUE TITLE
[BUG] pull最新提交后对接f2 0.0.1.6运行抛异常

### ISSUE THREAD

**Issue by iray1024** [Johnserf-Seed/TikTokDownload#740]
- [x] 我查看了 [文档](https://johnserf-seed.github.io/f2/quick-start.html) 以及 [已关闭的问题](https://github.com/Johnserf-Seed/f2/issues?q=is%3Aissue+is%3Aclosed) 以寻找可能的解决方案。
- [x] 我在 [常见的问题与解决办法](https://johnserf-seed.github.io/f2/question-answer/qa.html) 中找不到我的问题。
- [ ] ~~*你的问题是公开的，请注意删除个人敏感内容再上传*~~
- [ ] 不按照模板填写的问题将不会得到优先的处理。

- 如果错误问题是可视化的，请在**屏幕截图**贴截图。如果你是开发者请在**错误重现**提供一个最小的代码示例来演示该问题。
- 相同的问题将会被标记`重复(duplicate)`，如果你的问题被标记为`已确认(confirmed)`则会在后续的推送中修复，请时刻留意。
- 退订邮件提醒请点击邮件的底部`unsubscribe`。

**详细描述错误**
简明扼要地描述遇到的错误。

**系统平台**
<details>
<summary>单击展开</summary>
Q:你在哪个平台（Win/Linux/Mac）上运行？你使用的是什么浏览器？你使用的是什么终端软件？你使用的F2是什么版本？

A: 

 - 操作系统: Win11 23H2
 - 浏览器 Chrome 126.0.6478.127
 - 终端 Terminal 1.20.11381.0
 - F2版本 0.0.1.6

</details>

**错误重现**
<details>
<summary>单击展开</summary>
Q: 请你复制并粘贴出错时运行的命令和配置文件内容，以及重现该行为的步骤。如果你一次性就提供完整信息，就会节省很多解决问题的时间。

A: 重新初始化的配置，并且使用了auto-cookie指定

Q: 请添加调试命令`f2 -d DEBUG`重新运行出错的命令并提供日志目录下的日志文件。

A: 下面的调试模式的堆栈异常文件中

Q: 如果是开发者请提供最小的代码示例

A: 

```python

```

</details>

**预期行为**
简明扼要地描述期望发生的事情。

**屏幕截图**
![Snipaste_2024-06-30_19-46-37](https://github.com/Johnserf-Seed/TikTokDownload/assets/49387318/59ce0122-ac17-4866-9904-5cb271f0c044)

**日志文件**
堆栈异常：[log.txt](https://github.com/user-attachments/files/16044195/log.txt)
调试模式的堆栈异常：[debug-log.txt](https://github.com/user-attachments/files/16044204/debug-log.txt)

**其他**
如有，可以添加有关问题的其他信息。

**Comment by iray1024** [comment]
f2 dy -c configs\dy.yaml

**Comment by iray1024** [comment]
f2 dy -c configs\dy.yaml

**Comment by Johnserf-Seed** [comment]
这是0.0.1.5版本就更新的内容，在f2 的readme中有说明更新注意。
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/095c96e9-298f-46f9-ad2c-383088335356)

**Comment by iray1024** [comment]
原来如此，跨两个版本没更新了，没注意这个，删掉db后没问题了
