### ISSUE TITLE
[BUG]单个作品下载失败“没有找到符合条件的作品”

### ISSUE THREAD

**Issue by IHGhog** [Johnserf-Seed/TikTokDownload#742]
操作系统: [e.g. Win11 x64 21H2 22000.1936]
浏览器 [e.g. Chrome 126.0.6478.127]
终端 [e.g. Terminal  1.20.11381.0]
F2版本 [e.g. 0.0.1.6]

单个作品下载 找不到作品、主页可以正常下载；已更新过几次cookie还是不行；

![Snipaste_2024-06-30_22-29-16](https://github.com/Johnserf-Seed/TikTokDownload/assets/63387583/0e9a2dfb-5c15-4f01-9f7e-9d1adeae8325)

**Comment by Johnserf-Seed** [comment]
https://johnserf-seed.github.io/f2/question-answer/qa.html#warning-%E6%B2%A1%E6%9C%89%E6%89%BE%E5%88%B0%E7%AC%A6%E5%90%88%E6%9D%A1%E4%BB%B6%E7%9A%84%E4%BD%9C%E5%93%81

**Comment by IHGhog** [comment]
谢谢大佬指点，找到原因了，0.0.1.5升级到0.0.1.6，app.yaml被覆盖了；

![640](https://github.com/Johnserf-Seed/TikTokDownload/assets/63387583/072d2493-2f22-443d-8802-aced1619a2d8)
