### ISSUE TITLE
auto-cookie 报错 请关闭所有已打开的浏览器重试，并且你有适当的权限访问浏览器！

### ISSUE THREAD

**Issue by solpower** [Johnserf-Seed/TikTokDownload#745]
f2 tiktok -c app.yaml --auto-cookie edge
请关闭所有已打开的浏览器重试，并且你有适当的权限访问浏览器！

![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/102137370/a4d84178-cfed-4e45-86ab-b2924eca8344)

**Comment by solpower** [comment]
win 11 管理员启动的终端 也不行

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/Johnserf-Seed/TikTokDownload/assets/40727745/ea92da8e-87cb-4026-89e4-efc357616d1f)

**Comment by solpower** [comment]
f2 tiktok -c f2/conf/app.yaml --auto-cookie chrome
f2 tiktok -c tiktok.yaml --auto-cookie chrome

之前使用 edge 不行， 使用chrome可以了， 上述两种都能自动获取到cookie

**Comment by Johnserf-Seed** [comment]
> f2 tiktok -c f2/conf/app.yaml --auto-cookie chrome
> f2 tiktok -c tiktok.yaml --auto-cookie chrome
> 
> 之前使用 edge 不行， 使用chrome可以了， 上述两种都能自动获取到cookie

新版的内核都会有驻留后台，在托盘中关闭允许后台运行即可
