### ISSUE TITLE
[BUG] 期望下载url用户的收藏，但是实际下载的是ck用户的收藏

### ISSUE THREAD

**Issue by Mr-Zhang-Cn** [Johnserf-Seed/TikTokDownload#768]
- [ ] 我查看了 [文档](https://johnserf-seed.github.io/f2/quick-start.html) 以及 [已关闭的问题](https://github.com/Johnserf-Seed/f2/issues?q=is%3Aissue+is%3Aclosed) 以寻找可能的解决方案。
- [ ] 我在 [常见的问题与解决办法](https://johnserf-seed.github.io/f2/question-answer/qa.html) 中找不到我的问题。
- [ ] ~~*你的问题是公开的，请注意删除个人敏感内容再上传*~~
- [ ] 不按照模板填写的问题将不会得到优先的处理。

- 如果错误问题是可视化的，请在**屏幕截图**贴截图。如果你是开发者请在**错误重现**提供一个最小的代码示例来演示该问题。
- 相同的问题将会被标记`重复(duplicate)`，如果你的问题被标记为`已确认(confirmed)`则会在后续的推送中修复，请时刻留意。
- 退订邮件提醒请点击邮件的底部`unsubscribe`。

**详细描述错误**
简明扼要地描述遇到的错误。
我期望下载张三用户的收藏，但是实际下载之后发现，下载的是ck用户的收藏，而不是url用户的收藏。
![1730612685384](https://github.com/user-attachments/assets/e1284e5d-450a-4e8b-849c-544eacbb5186)

**系统平台**
<details>
<summary>单击展开</summary>
Q:你在哪个平台（Win/Linux/Mac）上运行？你使用的是什么浏览器？你使用的是什么终端软件？你使用的F2是什么版本？

A: 

操作系统: [ Win10 x64 操作系统名称 Microsoft Windows 10 专业版 10.0.19045 版本 19045 ]
浏览器 [goole chrome 130.0.6723.70 ]
F2版本 [ 0.0.1.6]

</details>

**错误重现**
<details>
<summary>单击展开</summary>
Q: 请你复制并粘贴出错时运行的命令和配置文件内容，以及重现该行为的步骤。如果你一次性就提供完整信息，就会节省很多解决问题的时间。
![image](https://github.com/user-attachments/assets/2c3225fe-6061-4b6a-a119-72c7de87d2a3)

A: 

1. 
2. 
3. 

Q: 请添加调试命令`f2 -d DEBUG`重新运行出错的命令并提供日志目录下的日志文件。
f2 dy -c config/app.yaml
A: 

Q: 如果是开发者请提供最小的代码示例

A: 

```python

```

</details>

**预期行为**
简明扼要地描述期望发生的事情。
期望下载https://v.douyin.com/xxxx/用户的收藏，但是实际下载的是ck用户的收藏
**屏幕截图**
请添加截图以帮助解释你的问题。
![image](https://github.com/user-attachments/assets/d3da7dff-0988-45e8-9a90-b17e4b3e38d1)

**日志文件**
请添加调试日志文件以帮助解释你的问题。

**其他**
如有，可以添加有关问题的其他信息。

**Comment by Mr-Zhang-Cn** [comment]
我是在https://github.com/Johnserf-Seed/TikTokDownload/issues/767的基础上，发现了https://github.com/Johnserf-Seed/TikTokDownload/issues/768这个问题的。简单说就是，我期望用A用户的ck模拟登陆，下载B用户的收藏作品，但是实际运行之后发现 下载的是A用户的收藏，而我期望的是B用户的收藏作品。

**Comment by Johnserf-Seed** [comment]
这是由于网页版的个人收藏接口与收藏夹是需要根据ck来返回数据的，这一点你可以从请求负载和文档的[代码片段](https://johnserf-seed.github.io/f2/guide/apps/douyin/#%E7%94%A8%E6%88%B7%E6%94%B6%E8%97%8F%E4%BD%9C%E5%93%81%E6%95%B0%E6%8D%AE-%F0%9F%9F%A2)中发现，因为没有传`sec_uid`参数。这一点在源码中均有注释。

![image](https://github.com/user-attachments/assets/71a0caf0-4b71-4118-8acf-977dc60537a9)
