### ISSUE TITLE
like模式批量下载报错

### ISSUE THREAD

**Issue by adam2rdam** [Johnserf-Seed/TikTokDownload#77]
**同一个账号在post模式可以正常下载但是like模式报错：**

批量下载直接回车，单一视频下载直接粘贴视频链接：
----读取配置完成----
----为您下载多个视频----
----用户的sec_id=MS4wLjABAAAAs_Dkw8_CynCMjVN601UkAa8M3TGfDgLJqYUn2tKeyy_iEDch9ifarviMtWSjD4qN----
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-2-6256bfbbea5e> in <module>
      1 import TikTokMulti as MTK
      2 
----> 3 MTK.TikTok()
      4 
      5 #单视频下载

~\Desktop\TikTokDownload-main\TikTokMulti.py in __init__(self)
     99 
    100         print('----读取配置完成----\r')
--> 101         self.judge_link()
    102 
    103     def out_Print(self):

~\Desktop\TikTokDownload-main\TikTokMulti.py in judge_link(self)
    146         response = requests.get(url = api_post_url,headers = self.headers)
    147         html = json.loads(response.content.decode())
--> 148         self.nickname = html['aweme_list'][0]['author']['nickname']
    149         if not os.path.exists(self.save + self.mode + "\\" + self.nickname):
    150                 os.makedirs(self.save + self.mode + "\\" + self.nickname)

IndexError: list index out of range

**Comment by eenapol** [comment]
self.nickname = html['aweme_list'][0]['author']['nickname']
批量获取，nickname没取到

**Comment by Johnserf-Seed** [comment]
现已经修复，可以重新拉取一下代码试试

**Comment by adam2rdam** [comment]
现在主代码里面没有tiktokdownloader哈，我把之前的那个拉进来以后还是报错
IndexError                                Traceback (most recent call last)
<ipython-input-1-6256bfbbea5e> in <module>
      1 import TikTokMulti as MTK
      2 
----> 3 MTK.TikTok()
      4 
      5 #单视频下载

~\Downloads\TikTokDownload New\TikTokDownload-main\TikTokMulti.py in __init__(self)
     99 
    100         print('----读取配置完成----\r')
--> 101         self.judge_link()
    102 
    103     def out_Print(self):

~\Downloads\TikTokDownload New\TikTokDownload-main\TikTokMulti.py in judge_link(self)
    149         response = requests.get(url = api_post_url, headers = self.headers)
    150         html = json.loads(response.content.decode())
--> 151         self.nickname = html['aweme_list'][0]['author']['nickname']
    152         if not os.path.exists(self.save + self.mode + "\\" + self.nickname):
    153                 os.makedirs(self.save + self.mode + "\\" + self.nickname)

IndexError: list index out of range

**Comment by Johnserf-Seed** [comment]
> 现在主代码里面没有tiktokdownloader哈，我把之前的那个拉进来以后还是报错 IndexError Traceback (most recent call last) in 1 import TikTokMulti as MTK 2 ----> 3 MTK.TikTok() 4 5 #单视频下载
> 
> ~\Downloads\TikTokDownload New\TikTokDownload-main\TikTokMulti.py in **init**(self) 99 100 print('----读取配置完成----\r') --> 101 self.judge_link() 102 103 def out_Print(self):
> 
> ~\Downloads\TikTokDownload New\TikTokDownload-main\TikTokMulti.py in judge_link(self) 149 response = requests.get(url = api_post_url, headers = self.headers) 150 html = json.loads(response.content.decode()) --> 151 self.nickname = html['aweme_list'][0]['author']['nickname'] 152 if not os.path.exists(self.save + self.mode + "\" + self.nickname): 153 os.makedirs(self.save + self.mode + "\" + self.nickname)
> 
> IndexError: list index out of range

没有拉取好，本地测试没问题才会push

**Comment by Johnserf-Seed** [comment]
> 现在主代码里面没有tiktokdownloader哈，我把之前的那个拉进来以后还是报错 IndexError Traceback (most recent call last) in 1 import TikTokMulti as MTK 2 ----> 3 MTK.TikTok() 4 5 #单视频下载
> 
> ~\Downloads\TikTokDownload New\TikTokDownload-main\TikTokMulti.py in **init**(self) 99 100 print('----读取配置完成----\r') --> 101 self.judge_link() 102 103 def out_Print(self):
> 
> ~\Downloads\TikTokDownload New\TikTokDownload-main\TikTokMulti.py in judge_link(self) 149 response = requests.get(url = api_post_url, headers = self.headers) 150 html = json.loads(response.content.decode()) --> 151 self.nickname = html['aweme_list'][0]['author']['nickname'] 152 if not os.path.exists(self.save + self.mode + "\" + self.nickname): 153 os.makedirs(self.save + self.mode + "\" + self.nickname)
> 
> IndexError: list index out of range

![image](https://user-images.githubusercontent.com/40727745/149902122-daccecaf-8ee4-4a56-9b76-11608d0f9f73.png)

**Comment by adam2rdam** [comment]
拉了最新的代码还是报错呀，请问是要怎么解决？谢谢啦！
![image](https://user-images.githubusercontent.com/20933169/150031721-8abe8211-cd5c-488a-9e8f-e5016ab1c3ac.png)

**Comment by Johnserf-Seed** [comment]
建议使用v1.2.5版本

**Comment by Johnserf-Seed** [comment]
like模式将在下个版本中完全修复，目前会生成很多作者文件夹但是视频没有保存在对应目录中

**Comment by Bigsea13** [comment]
运行TikTokMulti.py  like模式，就会出现一下错误，post模式正常，请问怎么回事？：
[  警告  ]:未检测到命令，将使用配置文件进行批量下载!
[  提示  ]:读取本地配置完成!
[  提示  ]:批量下载直接回车：
[  提示  ]:为您下载多个视频!
[  提示  ]:用户的sec_id=MS4wLjABAAAAaZEW4Yq59EumbVkMzJuuF7aVsHppjZi-Xjunksay7q8
[  警告  ]: list index out of range 可以复制此报错内容发issues
[  提示  ]:未输入命令或意外出错，自动退出!

进程已结束,退出代码0
