### ISSUE TITLE
[BUG]跪求大佬，下载视频不全。出现。第 1731964703000 页没有找到作品。文件夹里下载只保留了20个视频。出现了类似#761这样的问题。

### ISSUE THREAD

**Issue by jo-sos** [Johnserf-Seed/TikTokDownload#774]
下载的视频网址：https://www.douyin.com/user/MS4wLjABAAAAwCxFjP911H9NlyBpa3BIrLOGFYvrUMNp8p5vC89vXRM?from_tab_name=main

![image](https://github.com/user-attachments/assets/c4b2e710-8601-44f4-adef-4d39dd037632)

操作系统: [e.g. Windows 11]
浏览器 [Firefox]
终端 [cmd命令]
F2版本 [0.0.1.6](更新到最新版了）
命令：
f2 dy --auto-cookie firefox

f2  dy  -u https://www.douyin.com/user/MS4wLjABAAAAwCxFjP911H9NlyBpa3BIrLOGFYvrUMNp8p5vC89vXRM?from_tab_name=main

配置文件内容：
douyin:
cookie:
cover: false
desc: no
folderize: false
interval: all
languages: zh_CN
max_connections: 5
max_counts: 0
max_retries: 4
max_tasks: 6
mode: post
music: false
naming: '{create}{desc}{nickname}'
page_counts: 20
path: ./Download
timeout: 20

  问题：类似#761，视频下载不全。第 1731964703000 页没有找到作品。文件夹里下载只保留了20个视频。

请求：
跪求大佬，这个问题要如何解决？

**Comment by Johnserf-Seed** [comment]
等待0.0.1.7版本，着急可以去切换git分支源码安装

**Comment by Johnserf-Seed** [comment]
#220
