### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by iray1024** [Johnserf-Seed/TikTokDownload#775]
- [√ ] 我查看了 [文档](https://johnserf-seed.github.io/f2/quick-start.html) 以及 [已关闭的问题](https://github.com/Johnserf-Seed/f2/issues?q=is%3Aissue+is%3Aclosed) 以寻找可能的解决方案。
- [√ ] 我在 [常见的问题与解决办法](https://johnserf-seed.github.io/f2/question-answer/qa.html) 中找不到我的问题。
- [ ] ~~*你的问题是公开的，请注意删除个人敏感内容再上传*~~
- [ ] 不按照模板填写的问题将不会得到优先的处理。

- 如果错误问题是可视化的，请在**屏幕截图**贴截图。如果你是开发者请在**错误重现**提供一个最小的代码示例来演示该问题。
- 相同的问题将会被标记`重复(duplicate)`，如果你的问题被标记为`已确认(confirmed)`则会在后续的推送中修复，请时刻留意。
- 退订邮件提醒请点击邮件的底部`unsubscribe`。

**详细描述错误**
无法自动导入cookie

**系统平台**
<details>
<summary>单击展开</summary>
Q:你在哪个平台（Win/Linux/Mac）上运行？你使用的是什么浏览器？你使用的是什么终端软件？你使用的F2是什么版本？

A: 

 - 操作系统: Windows 11 专业版 26100.2605
 - 浏览器 Chrome 131.0.6778.205
 - 终端 WT 1.21.3231.0
 - F2版本 0.0.1.6

</details>

**错误重现**
<details>
<summary>单击展开</summary>
Q: 请你复制并粘贴出错时运行的命令和配置文件内容，以及重现该行为的步骤。如果你一次性就提供完整信息，就会节省很多解决问题的时间。

A: f2 dy -c configs\dy.yaml --auto-cookie chrome -d DEBUG

配置文件
douyin:
  cookie: ***
  cover: true
  desc: false
  folderize: true
  headers:
    Referer: https://www.douyin.com/
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
      like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
  interval: all
  languages: zh_CN
  lyric: null
  max_connections: null
  max_counts: 0
  max_retries: 5
  max_tasks: 10
  mode: post
  music: true
  naming: '{create}_{desc}'
  page_counts: 20
  path: Download
  timeout: null
  url: https://www.douyin.com/user/***

Q: 请添加调试命令`f2 -d DEBUG`重新运行出错的命令并提供日志目录下的日志文件。

A: 
WARNING  您当前使用的版本 0.0.1.6 可能已过时，请考虑及时升级到最新版本 0.0.1.6，请使用 pip install -U f2 更新
INFO     应用：douyin
ERROR    自动获取Cookie失败：Unable to get key for cookie decryption

Q: 如果是开发者请提供最小的代码示例

A: 

```python

```

</details>

**预期行为**
能自动导入cookie

**屏幕截图**
![image](https://github.com/user-attachments/assets/6f2bb19f-b858-48eb-8062-844792eab52f)

**日志文件**
请添加调试日志文件以帮助解释你的问题。

**其他**
如有，可以添加有关问题的其他信息。

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/f2/issues/193#issuecomment-2490225119

**Comment by iray1024** [comment]
> [Johnserf-Seed/f2#193 (comment)](https://github.com/Johnserf-Seed/f2/issues/193#issuecomment-2490225119)

**Comment by iray1024** [comment]
自己手动从document.cookie中获取的不知道是不是有问题，post获取不全，107个公开的作品，只下载了十几个

**Comment by Johnserf-Seed** [comment]
> 自己手动从document.cookie中获取的不知道是不是有问题，post获取不全，107个公开的作品，只下载了十几个

是的，document.cookie获取的ck是不完整的，你需要在网络的xhr请求中复制请求头里的cookie
![image](https://github.com/user-attachments/assets/bc1a6505-55a3-49ce-a64c-d8726917497e)

**Comment by iray1024** [comment]
OK，没问题了，谢谢~
