### ISSUE TITLE
针对批量下载的几个疑问，求助大佬

### ISSUE THREAD

**Issue by JDZW2018** [Johnserf-Seed/TikTokDownload#79]
**描述出现的错误**
大佬您好，我经常使用的是批量下载，针对批量下载我有几个疑问：
1，短链接的获取方式：https://v.douyin.com/efrHYf2/
https://www.douyin.com/user/MS4wLjABAAAAo0hDbJvN_-xEvV3BP6mQJ7azqbhmErfLoPcQES5Lkq4
上述的两个链接，都是标识一个账号的主页， 目前只能用短链接才能下载，长连接无法批量下载，想问下如何获取短链接，或者是否有什么方式支持长连接。

2，是否可以允许以 脚本的形式传递参数来批量下载视频如：
python exmple.py --play-list 'https://v.douyin.com/efrHYf2/'  --dir ./download/ --musicarg no --count 35 

以这种方式来执行批量下载操作，好处是方便对接外部定时调用程序

大佬这个完全可以对标 youtube-dl ，或者 you-get 这种工具， 以上两个问题，谢谢！~

**Comment by Johnserf-Seed** [comment]
传参的功能在单文件下载中是有的，批量下载下次更新里加入，另外长短链接的问题已经解决 配合图形界面版本更新一起发布，年前更新发布新版本

**Comment by JDZW2018** [comment]
感谢~，等待老大更新

**Comment by Johnserf-Seed** [comment]
GUI预览版明天发布，目前GUI目录下面暂未实现功能，这几天把这提到的几个建议全部肝完了。赶紧来试试
