### ISSUE TITLE
能否下载海外的tiktok视频

### ISSUE THREAD

**Issue by cdh1991** [Johnserf-Seed/TikTokDownload#8]

**Comment by Johnserf-Seed** [comment]
后续会加入的

**Comment by LuckyDog301** [comment]
求支持TikTok海外版

**Comment by Mayaman5566** [comment]
挺好的项目，希望支持海外版抖音

**Comment by leilintao** [comment]
赞，期待能够支持下载tiktok的视频

**Comment by Evil0ctal** [comment]
> _No description provided._



> 求支持TikTok海外版



> 挺好的项目，希望支持海外版抖音



> 赞，期待能够支持下载tiktok的视频

你好，我的仓库支持TikTok，但是目前仅支持手动保存无水印视频，无法实现批量下载，有需要的话可以看一下。
仓库：
https://github.com/Evil0ctal/Douyin_TikTok_Download_API
