### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by iq3600** [Johnserf-Seed/TikTokDownload#80]
**描述出现的错误**
执行exmple.py后，就提示：
G:\dydown>exmple.py
Traceback (most recent call last):
  File "G:\dydown\exmple.py", line 2, in <module>
    import TikTokMulti as MTK
  File "G:\dydown\TikTokMulti.py", line 12, in <module>
    import requests,json,os,time,configparser,re,sys
ModuleNotFoundError: No module named 'requests'

是现在不能用了吗？我这刚才在mac下不能用，后来看看说是不支持mac，换了win10，刚下了python的最新版，还是出错，不会了…………谁能教教我啊？

**Comment by Johnserf-Seed** [comment]
这个原因是因为Python库的依赖没有安装，需要用pip安装一下

**Comment by Johnserf-Seed** [comment]
example文件是包含2条代码的，执行批量下载应该运行那个multi文件

**Comment by iq3600** [comment]
谢谢老大指点~但是我在mac里面就是直接用终端执行就可以pip安装了，在win下面执行
pip install TikTokDownload==1.2.3
这个的时候，就提示：
'pip' 不是内部或外部命令，也不是可运行的程序或批处理文件。
在IDLE Shell里面执行的话，是提示：
SyntaxError: invalid syntax

搞不明白………………

**Comment by Johnserf-Seed** [comment]
这是你在安装Python的时候没有选add path，添加环境变量，你需要手动设置一下就可以了

**Comment by iq3600** [comment]
![微信截图_20220125133741](https://user-images.githubusercontent.com/90752439/150917625-0a922162-fddb-4f71-9570-1f6a7357ea57.png)
这是已经添加了

然后执行pip install TikTokDownload==1.2.3
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: TikTokDownload==1.2.3 in c:\users\iq360\appdata\roaming\python\python310\site-packages (1.2.3)
Requirement already satisfied: requests>=2.23.0 in c:\users\iq360\appdata\roaming\python\python310\site-packages (from TikTokDownload==1.2.3) (2.27.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\iq360\appdata\roaming\python\python310\site-packages (from requests>=2.23.0->TikTokDownload==1.2.3) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\iq360\appdata\roaming\python\python310\site-packages (from requests>=2.23.0->TikTokDownload==1.2.3) (2.0.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\iq360\appdata\roaming\python\python310\site-packages (from requests>=2.23.0->TikTokDownload==1.2.3) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\iq360\appdata\roaming\python\python310\site-packages (from requests>=2.23.0->TikTokDownload==1.2.3) (2021.10.8)

这应该是没有提示出错吧？
然后执行批量下载那个还是提示出错
======================= RESTART: G:\dydown\TikTokMulti.py ======================
Traceback (most recent call last):
  File "G:\dydown\TikTokMulti.py", line 13, in <module>
    import TikTokDownload
  File "G:\dydown\TikTokDownload.py", line 12, in <module>
    from retrying import retry
ModuleNotFoundError: No module named 'retrying'

**Comment by Johnserf-Seed** [comment]
这不是还有个retrying的包嘛

**Comment by iq3600** [comment]
完全不懂…………这个retrying的包是在哪搞啊？

**Comment by iq3600** [comment]
感觉自己没一点基础，挺笨的，给您添麻烦了…………

**Comment by Johnserf-Seed** [comment]
那你可以直接下载编译好的版本https://github.com/Johnserf-Seed/TikTokDownload/releases/tag/1.2.3
没有添麻烦，解决issue是仓库作者应该的

**Comment by iq3600** [comment]
哇！这个太棒了！直接就能用！谢谢啦！

提示音频下载失败，musicarg = no

**Comment by iq3600** [comment]
然后再运行就行了，真是太棒了！世界有你真好！
