### ISSUE TITLE
1.2.5功能问题 [也不算是BUG]

### ISSUE THREAD

**Issue by ciring** [Johnserf-Seed/TikTokDownload#84]
**描述出现的错误**
配置文件是抖音主页的网址
![image](https://user-images.githubusercontent.com/33834625/152113328-f2c3734e-1394-4359-8253-771b4f908bd3.png)

**多次实验**

> 1.2.3版本可以双击运行，然后回车，就能自动加载配置并下载

> 1.2.5版本和1.2.3版本的配置在同一目录下，双击显示

    [  警告  ]:未检测到命令，将使用配置文件进行批量下载!
    [  提示  ]:读取本地配置完成!
    [  提示  ]:批量下载直接回车：
    然后回车  闪退

> 1.2.5版本  清除配置文件 ，双击，输入主页链接地址，回车，显示相同提示；

                然后文件夹下有自动生成的配置文件，双击exe，回车，闪退

> 1.2.5 版本在cmd里使用 tiktokdownload -u *** 正常下载

**截图**
![image](https://user-images.githubusercontent.com/33834625/152113126-99e367ab-1b26-4ffa-aaf6-84f7d2cbeeff.png)

**桌面（请填写以下信息）：**
-操作系统：windows10 64bit
-vpn代理：关闭
-版本[1.2.5]

**Comment by Johnserf-Seed** [comment]
已经修复了~
