### ISSUE TITLE
[BUG]长链接无法下载下页视频

### ISSUE THREAD

**Issue by gaucnet** [Johnserf-Seed/TikTokDownload#87]
**描述出现的错误**
应该是大佬忘记改了
使用长链接时无法下载下页视频，短连接正常

**截图**
![捕获](https://user-images.githubusercontent.com/74766282/152982208-bd7c66a0-ca41-40b7-8419-ef90bc91901d.PNG)

**Comment by Johnserf-Seed** [comment]
因为网页复制的链接中有时候会有?previous_page=app_code_link参数，为了不影响key结果做二次过滤,之前没有考虑到这个情况

**Comment by Johnserf-Seed** [comment]
可以重新拉取一下
