### ISSUE TITLE
拓展名出错，导致文件空白[BUG]

### ISSUE THREAD

**Issue by boluohong** [Johnserf-Seed/TikTokDownload#89]
今天开始出现
已发现两例
拓展名出错，导致文件空白

example1:
https://v.douyin.com/LsUeoBA/

![捕获](https://user-images.githubusercontent.com/58325940/153592066-c3b18de2-5585-47d9-8031-6752394d6900.PNG)

example2:
https://v.douyin.com/LsDDMt6/

![002](https://user-images.githubusercontent.com/58325940/153592422-c6a4e965-2b93-484a-b2c4-bd914b10de5f.PNG)

**Comment by RobotJohns** [comment]
可以去看下我提交的版本，里面有针对这个bug 的修改，
应为 视频是以 标题名称作为 文件名保存的；如果标题 有特殊符号 或者 名字过长； 就会出异常

**Comment by boluohong** [comment]
好的，谢谢，我去找找

**Comment by PengJiang520** [comment]
视频里面带有水印itools.cn
