### ISSUE TITLE
抖音主页视频不能全部下载

### ISSUE THREAD

**Issue by zhou8898** [Johnserf-Seed/TikTokDownload#93]
用户主页视频数量比较多，有四万多，程序运行后只下载了400个左右就自动关闭了，不知道怎么回事，重试后，就是提示视频已存在，跑了几分钟自动推出了，期望作者解决，谢谢

**Comment by Johnserf-Seed** [comment]
我本地测试，一小时稳定未报错，下载了1w5个视频，能否提供下链接测试一下

**Comment by Simp1e49** [comment]
https://v.douyin.com/NQj8eLp/
这个链接有737发布的视频，可是下载的只有25个
![image](https://user-images.githubusercontent.com/23161308/160800556-7b067d9a-4ec9-485b-ace5-e35ae146a49c.png)
配置的不对么？   还麻烦帮忙指点一下 谢谢
