### ISSUE TITLE
[Feature]交互对于批量下载视频相当不友好。

### ISSUE THREAD

**Issue by huangsijun17** [Johnserf-Seed/TikTokDownload#99]
**描述您想要的功能**
能较方便得在有视频的链接时，较为方便得批量下载。

**描述你想要替换的功能或需要修改的解决方案**
取消掉单一视频下载完后的“按任意键继续”，或提供单纯运行输入多个视频地址的方式。
并在终端中打印出下载的视频名。当然，可以指定下载后的存放地址，那就最好了。

**附文**
```
.\TikTokDownload.exe -u https://v.douyin.com/XXXX/ -m no
下载完成，按任意键退出...
```

**Comment by Johnserf-Seed** [comment]
可以使用bat脚本实现，例如
@echo off
TikTokDownlaod -u xxx -m no
TikTokDownlaod -u xxx -m no
TikTokDownlaod -u xxx -m no
TikTokDownlaod -u xxx -m no
TikTokDownlaod -u xxx -m no
TikTokDownlaod -u xxx -m no
TikTokDownlaod -u xxx -m no
echo 下载完成

单视频保存路径选项将会更新

**Comment by huangsijun17** [comment]
> 可以使用bat脚本实现，例如 @echo off TikTokDownlaod -u xxx -m no TikTokDownlaod -u xxx -m no TikTokDownlaod -u xxx -m no TikTokDownlaod -u xxx -m no TikTokDownlaod -u xxx -m no TikTokDownlaod -u xxx -m no TikTokDownlaod -u xxx -m no echo 下载完成
> 
> 单视频保存路径选项将会更新

然而因为每个视频都会提示`按任意键继续`，所以并不行。

**Comment by huangsijun17** [comment]
> 用python 帮你按
> 
> ```
> import subprocess
> import time
> 
> while True:
>     subprocess.call(["开始下载.bat"])
>     time.sleep(5)
>     # 运行bat并且模拟按下回车键
>     print("按下回车键\n¯¯¯¯¯¯¯¯¯¯¯")
> ```

1. 已经修复了。
2. 我当时复制多条命令，中间加几个换行，再一起粘贴在PS里就可以临时解决。
3. 你这代码没用。
